### ISSUE TITLE
Map asks for location permission with myLocation and myLocationButton set to false

### ISSUE THREAD

**Issue by aMUSiC** [mapsplugin/cordova-plugin-googlemaps#2362] opened 2018-07-27 13:01 UTC
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report

**OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
In an empty project with just the map plugin, when I try to initialize the map passing the following map options:

```
{
      camera: {
        target: {
          lat: 43.0741704,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      },
      controls: {
        myLocation: false
      }
}
```
the map will request location permission from the user.

The same thing happens with the map options having controls.myLocationButton = false

**Expected behavior:**

The map shouldn't ask for location permission from the user since it is not needed.

**Additional info/Workaround:**

If the keys controls.myLocation and controls.myLocationButton do not exist at all, then the map will correctly not ask for location permission

**Comment by wf9a5m75** [comment] 2018-07-27 14:14
Share the project files on GitHub

**Comment by wf9a5m75** [comment] 2018-07-27 20:07
ping

**Comment by aMUSiC** [comment] 2018-07-27 20:19
I will on Monday

**Comment by wf9a5m75** [comment] 2018-07-30 16:06
ping

**Comment by aMUSiC** [comment] 2018-07-31 11:59
https://github.com/aMUSiC/gmapbugs

In src/pages/home/home.ts lines 33 and 34, comment/uncomment myLocationButton/myLocation to see the behavior described above.

**Comment by wf9a5m75** [comment] 2018-07-31 14:13
You have to specify both.

**Comment by aMUSiC** [comment] 2018-07-31 15:04
I have tried all possible combinations before submitting the bug report.

```
controls: {
        myLocation: false
      }
```

Result: Map requests location permission

```
controls: {
        myLocationButton: false
      }
```

Result: Map requests location permission

```
controls: {
        myLocation: false,
        myLocationButton: false
      }
```

Result: Map requests location permission

```
controls: {
        myLocation: true
      }
```

Result: Map requests location permission

```
controls: {
        myLocationButton: true
      }
```

Result: Map requests location permission

```
controls: {
        myLocation: true,
        myLocationButton: true
      }
```

Result: Map requests location permission

```
controls: {
      }
```

Result: Map *DOES NOT* request location permission

**Comment by wf9a5m75** [comment] 2018-07-31 15:40
I see. I will check it more deeply later.

**Comment by aMUSiC** [comment] 2018-07-31 15:58
Take your time, as I've worked this around in my production project by deleting the keys if I don't need them.

**Comment by wf9a5m75** [comment] 2018-08-01 00:27
Here is the proof that the maps plugin works as expected with your shared project (I added little code).

test code
https://github.com/wf9a5m75/gmapbugs

record
https://youtu.be/fnEtAsy_03A

**Comment by wf9a5m75** [comment] 2018-08-01 00:34
I believe you didn't test with shared project because map is not displayed with your committed code.
Since you specified `rootPage:any = HomePage;` before `platform.ready()`, ionic can not find the native  maps plugin.

https://github.com/aMUSiC/gmapbugs/blob/6a8271c1fd147462c66358d21862c662f185335b/src/app/app.component.ts#L10-L21

**Comment by wf9a5m75** [comment] 2018-08-01 00:37
Here is the code logic.

```js
Map.prototype.getMap = function(meta, div, options) {
  ...
  if (options.controls) {
    this.set("myLocation", options.controls.myLocation === true);
    this.set("myLocationButton", options.controls.myLocationButton === true);
  }
  ...
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/5867c424a4437a111959c39f73bc9a0c32da8fa2/www/Map.js#L89-L92

```objc
- (void)_setOptions:(NSDictionary *)initOptions requestMethod:(NSString *)requestMethod command:(CDVInvokedUrlCommand *)command {
  ...
      //myLocationButton
      if ([controls valueForKey:@"myLocationButton"] != nil) {
        isEnabled = [[controls valueForKey:@"myLocationButton"] boolValue];
        if (isEnabled == true) {
          self.mapCtrl.map.settings.myLocationButton = YES;
        } else {
          self.mapCtrl.map.settings.myLocationButton = NO;
        }
      }
      //myLocation
      if ([controls valueForKey:@"myLocation"] != nil) {
        isEnabled = [[controls valueForKey:@"myLocation"] boolValue];
        if (isEnabled == true) {
          self.mapCtrl.map.myLocationEnabled = YES;
        } else {
          self.mapCtrl.map.myLocationEnabled = NO;
        }
      }
   ...
```
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/5867c424a4437a111959c39f73bc9a0c32da8fa2/src/ios/GoogleMaps/PluginMap.m#L766-L783

**Comment by wf9a5m75** [comment] 2018-08-01 00:39
If you still believe this is bug, please modify the shared project that reproduce your issue 100%.

**Comment by wf9a5m75** [comment] 2018-08-01 16:08
ping

**Comment by wf9a5m75** [comment] 2018-08-03 00:58
ping

**Comment by wf9a5m75** [comment] 2018-08-03 19:19
Since there is no response, and I can't reproduce the issue, I close this thread.

**Closed by wf9a5m75** 2018-08-03 19:19 UTC
Labels: need more information

**Comment by aMUSiC** [comment] 2018-08-03 21:50
Please be a bit patient. We are on different timezones and I've been very busy with work these couple of days. I'll modify the project accordingly and open a new issue ticket.

**Comment by wf9a5m75** [comment] 2018-08-03 22:24
Well, I pinged two times, but you didn't reply anything.
