### ISSUE TITLE
map locking error

### ISSUE THREAD

**Issue by manuvalentim** [mapsplugin/cordova-plugin-googlemaps#1866] opened 2017-11-06 16:59 UTC
My map is experiencing a problem when exiting and re-entering the screen. Instead of maps and instead of uploads.

This happens every time I exit and return to the screen
![23335916_1599924516695870_2124722160_o](https://user-images.githubusercontent.com/20819292/32453232-d418686a-c302-11e7-8534-af422e1270ed.jpg)

**Comment by wf9a5m75** [comment] 2017-11-06 17:01
What is this?

**Comment by wf9a5m75** [comment] 2017-11-06 17:19
Please share your project files on github if you want to check your project by me. Otherwise, I can not help anything.

**Comment by manuvalentim** [comment] 2017-11-06 17:22
https://gist.github.com/manuvalentim/fb0f0ccdecb980e6f8641d8b47bf0f18

**Comment by manuvalentim** [comment] 2017-11-06 17:22
This is my maps.

**Comment by wf9a5m75** [comment] 2017-11-06 17:45
Thank you. 

First of all, you should not use `ionViewWillEnter`.
Because the view page is not ready.
`this.mapElement = document.getElementById('map');` might return `null`.
(It is depends on how faster the `getcurrentPosition()` returns the data).
I recommend you use `ionViewLoaded()`

Unfortunately, I can not build your code, because there are missing files.
If you share your project files (including other files), I can build, then I can test it for you.

By the way, I recommend you specify the ID of map div, instead of DOM element.
```
this.map = this.googleMaps.create('map', mapOptions);
```
Because the wrapper plugin waits the proper timing until the div element is ready.
(You need to use `@ionic-native/google-maps@4.3.3`)

**Comment by wf9a5m75** [comment] 2017-11-06 17:47
The important thing is to reproduce your issue on my side. I'm not interested in your application itself. So I don't leak your code.

**Comment by wf9a5m75** [comment] 2017-11-07 17:28
Thank you for sharing your private project. Let me confirm one thing. Is this for PhoneGap instead of Cordova?

**Comment by wf9a5m75** [comment] 2017-11-08 00:21
Okay, this trouble happens on me on another project also.
I guess the `out-of-memory`

**Comment by wf9a5m75** [comment] 2017-11-08 00:33
@manuvalentim Could you tell me how to run your project files?
I thought the `phonegap` CLI, but it seems it is not.

**Comment by wf9a5m75** [comment] 2017-11-09 07:33
This error occurs only you create more than 2 maps.
Until you share your project files, no more update.

**Comment by wf9a5m75** [comment] 2017-11-10 05:37
ping

**Comment by wf9a5m75** [comment] 2017-11-14 22:02
Since there is no update for a while, I close this thread. But you can reply anytime

**Closed by wf9a5m75** 2017-11-14 22:02 UTC
Labels: confirmed, need more information
