### ISSUE TITLE
Fatal crash V2

### ISSUE THREAD

**Issue by marijnroukens** [mapsplugin/cordova-plugin-googlemaps#1353] opened 2017-03-11 21:11 UTC
Situation:

I am using Ionic and I have a slide box delegate (ionicSlideBoxDelegate) that displays a few cards on top of the map. When I slide a card, the map goes (using animateCamera) to the corresponding location from that card.

After sliding through a few cards (6-7) the app freezes and it makes my whole iPhone (6s) unusable. The whole phone freezes and is not responding to anything untill I disconnect the USB cable from Xcode that forces the app to quit.

Cordova: V6.3.1
Ionic: V2.2.1
cordova-plugin-googlemaps 2.0.0-beta
com.googlemaps.ios 2.1.1 

Log:

> 2017-03-11 22:03:44.088503 TestApp[2170:477777] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x174a51970> was mutated while being enumerated.'
> *** First throw call stack:
> (0x18f4c41c0 0x18defc55c 0x18f4c3c08 0x1000f6e28 0x195600ea8 0x195346f50 0x18f3b11a4 0x18f3b10a0 0x195346a88 0x195600ea8 0x195346f50 0x18f3b11a4 0x18f3b10a0 0x195346a88 0x195600ea8 0x1955e99ac 0x195311a98 0x1955e9874 0x1955e9bb8 0x195af7020 0x195afa3d4 0x195af4720 0x18f472278 0x18f471b50 0x18f46f7c0 0x18f39e048 0x190e21198 0x195378628 0x195373360 0x100025b90 0x18e3805b8)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb) 

Thanks in advance and I hope you have enough information to work with! Feel free to ask if I missed something.

**Comment by wf9a5m75** [comment] 2017-03-11 22:39
I have no idea.

**Comment by qbix0r** [comment] 2017-03-23 15:22
+1, same thing is happening to me. I dont think that overlaying elements are the problem here, because I don't have anything on top. However what is common in our crashes, @marijnroukens and I, we are using animateCamera.
I have ~50 markers and using animateCamera to current GPS position. It crashes itself after some time, no user interaction.

**Comment by marijnroukens** [comment] 2017-03-23 15:52
Some more crash info:

`*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[2]
0   CoreFoundation                  ___exceptionPreprocess
1   libobjc.A.dylib                 _objc_exception_throw
2   CoreFoundation                  -[__NSPlaceholderArray initWithObjects:count:]
3   CoreFoundation                  +[NSArray arrayWithObjects:count:]
4   CoreFoundation                  -[NSDictionary allKeys]
5   AppName                        -[PluginMap clear:]
6   AppName                        -[CordovaGoogleMaps _destroyMap:]
7   AppName                        ___28-[CordovaGoogleMaps onReset]_block_invoke
8   libdispatch.dylib               __dispatch_call_block_and_release
9   libdispatch.dylib               __dispatch_client_callout
10  libdispatch.dylib               __dispatch_main_queue_callback_4CF
11  CoreFoundation                  ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
12  CoreFoundation                  ___CFRunLoopRun
13  CoreFoundation                  _CFRunLoopRunSpecific
14  CoreFoundation                  _CFRunLoopRunInMode
15  GraphicsServices                _GSEventRunModal
16  GraphicsServices                _GSEventRun
17  UIKit                           _UIApplicationMain
18  AppName                        _main
19  libdyld.dylib                   _start
`

**Comment by wf9a5m75** [comment] 2017-03-23 16:09
Could you guys provide any example code that reproduce the issue 100%?

**Comment by marijnroukens** [comment] 2017-03-23 16:19
This is how I place the markers after the promise of a start_map() function resolves:

`            // For each tab add a marker
            angular.forEach($rootScope.tabs, function (tab)
            {
                // Add a marker
                $rootScope.map.addMarker({
                    'title': tab.title,
                    // Get the tabs position
                    'position': new plugin.google.maps.LatLng(tab.latitude, tab.longitude)
                }, function (marker)
                {
                    // When a user clicks on the marker, navigate the slidebox to the correct one
                    marker.addEventListener(window.plugin.google.maps.event.MARKER_CLICK, function() {
                        // Show the marker window
                        marker.showInfoWindow();
                        // Change the slider depending on the chosen tab in the map
                        $ionicSlideBoxDelegate.slide(tab.slideBoxIndex, 350);
                    });
                });

                $rootScope.map.addCircle({
                    'center': new plugin.google.maps.LatLng(tab.latitude, tab.longitude),
                    'radius': 100,
                    'strokeColor' : '#FFFFFF',
                    'strokeWidth': 1,
                    'fillColor' : '#FFFFFF'
                });

            });`

Each tab represents a slide, and this is the callback function for a slideboxdelegate:

`            $scope.slideHasChanged = function(index)
            {
                var tabs = $rootScope.tabs;

                // Add something to the lat to center the map
                var new_latitude            = parseFloat(tabs[index].latitude) + 0.004;
                var new_longitude           = parseFloat(tabs[index].longitude) - 0.004;
                var bearing                 = 140 + Math.floor((Math.random() * 25) + 1);
                var tilt                    = 60 + Math.floor((Math.random() * 25) + 1);

                $rootScope.map.animateCamera({
                    'target': new window.plugin.google.maps.LatLng(new_latitude, new_longitude),
                    'tilt': tilt,
                    'zoom': 13,
                    'bearing': bearing,
                    'duration': 600 // 0.6 seconds
                });

                $scope.current_tab = tabs[index];
            };`

**Comment by wf9a5m75** [comment] 2017-03-23 16:26
I guess you execute `map.animateCamera()`  during the map camera moving.
You should wait the `CAMERA_MOVE_END` event before execute next `map.animateCamera()`

**Comment by marijnroukens** [comment] 2017-03-23 16:43
Isn't it possible to cancel the CAMERA_MOVE before it ends to start another?

**Comment by wf9a5m75** [comment] 2017-03-23 18:04
Currently there is no way to cancel the map moving.

How about `map.moveCamera()` instead of `map.animateCamera()`

**Comment by marijnroukens** [comment] 2017-03-23 18:18
The animation given by `map.animteCamera()` is part of our UX, changing it to `map.moveCamera()` is not an option. At least now we know what it is causing.

**Comment by b4tch** [comment] 2017-04-03 23:19
Possible resolution? https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1384#issuecomment-291305733

**Comment by wf9a5m75** [comment] 2017-04-29 00:08
@marijnroukens This issue should be fixed in the latest code.
Please reinstall the plugin, and test it.

**Closed by wf9a5m75** 2017-04-29 00:08 UTC

**Comment by amjadyahya** [comment] 2018-02-22 07:48
@wf9a5m75, still crashes when using animateCamera
