### ISSUE TITLE
Map not getting displayed on android sdk 22

### ISSUE THREAD

**Issue by mosinconsrv** [mapsplugin/cordova-plugin-googlemaps#698] opened 2015-10-27 11:26 UTC
Hi there,
I am developing an ionic app in which I am using this plugin. Its working fine on android SDK 19. But recently I updated my android SDK to android 22 as I want to integrate crosswalk in my app. 
The map is appearing blank with only google logo placed at the footer. I have verified my api key and SHA fingerprint both are correct. Its not giving any error while building apk.
I also referred the tutorial to install this plugin for crosswalk but still no luck.﻿

I have tried regenerating new api key but still the problem persists.

My Configuration:
Cordova Version : 5.0.0
Android SDK : 22

Do we need to add google play services manually?
As in your older version 1.2.5 there was google play services in the dependent list.

**Comment by Hirbod** [comment] 2015-10-27 11:43
Follow the wiki. It clearly points out that you have to install the Android Support and Google Repository inside of SDK Manager. They will be included automatically with the framwork-tag

**Closed by Hirbod** 2015-10-27 11:43 UTC

**Comment by mosinconsrv** [comment] 2015-10-27 12:12
@Hirbod Yes I have referred the wiki and have also installed the Android Support and Google Repository. After installing your plugin the following meta tag get included in android manifest file

<meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="My API Key" />
        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

I verified the api key on developer console its correct.

Its not giving any error neither while compiling nor during inspect.

**Comment by Hirbod** [comment] 2015-10-27 12:21
Please, just start a new project from scratch and read carefully trough the wiki. The plugin is working as intended, there is an error on your side (maybe you included the release key instead of the debug key?).

Double check, that you key and package identifiers are inside of the google developer console and the API is active.
