### ISSUE TITLE
Problem with Framework7 Alerts and cordova-plugin-googleMaps

### ISSUE THREAD

**Issue by MDavidMR** [mapsplugin/cordova-plugin-googlemaps#1946] opened 2017-12-12 21:34 UTC
Hi there!

I'm having a big problem and I'd like some help.

I'm using Framework7 and Google Maps to build my app, but I'm having a little problem that is going to kill my self:

I have a `#map_canvas` `div` and all HTML tag code is inside it. Sometimes when I call framework7 confirms or alerts it works fine but not always. Even if the content is the same. I mean the `alert.show()` works but I can't click the button alert because the drag map function is active. I though use z-index, position: fixed, put the HTML alert inside #map_canvas but is the same thing.

I appreciate the help.
Pd. I'm sorry for my English

**Comment by wf9a5m75** [comment] 2017-12-12 22:02
Try the edge version, please.
```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps

$> git checkout multiple_maps

$> git pull

$> cd (project dir)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add (path to)/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." 
```

**Comment by MDavidMR** [comment] 2017-12-12 22:51
Thank you for your reply

I was using 2.1.1 version, now, I'm using `cordova-plugin-googlemaps 2.1.2-beta-20171208-1415 "cordova-plugin-googlemaps"` but the map does not load correctly. Something was wrong.

**Comment by wf9a5m75** [comment] 2017-12-12 23:01
Please share your project files on github. I will check it.

**Comment by candraekas** [comment] 2017-12-12 23:41
I also have the same problem, 

My Code 
`import { Component } from '@angular/core';
import { NavController, NavParams, Events, Platform, LoadingController } from 'ionic-angular';
import { Storage } from '@ionic/storage';
import { Geolocation } from '@ionic-native/geolocation';
import { AndroidPermissions } from '@ionic-native/android-permissions';

import { Config } from '../../app/config';
import {
    GoogleMaps,
    GoogleMap,
    LatLng,
    GoogleMapsEvent,
    GoogleMapOptions,
    MarkerOptions,
    Marker
} from '@ionic-native/google-maps';

@Component({
    selector: 'page-rs-terdekat-peta',
    templateUrl: 'rs-terdekat-peta.html',
    providers: [Geolocation, HomeService]
})
export class RsTerdekatPetaPage
{
    mapOptions(arg0: any, arg1: any): any
    {
        throw new Error("Method not implemented.");
    }
    lat         : any;
    lng         : any;
    map         : GoogleMap;
    data = {};
    constructor(public navCtrl: NavController,
                public storage: Storage,
                public navParams: NavParams,
                public googleMaps: GoogleMaps,
                public event: Events,
                public platform: Platform,
                public geolocation: Geolocation,
                public androidPermissions: AndroidPermissions,
                public loadingCtrl : LoadingController)
    {
        this.event.publish('setToolbarColor', 'e68a8a');

        platform.ready().then(() => {
            if(this.platform.is('android'))
            {
                this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.ACCESS_FINE_LOCATION).then(
                    result  => {
                        if(result.hasPermission)
                        {
                            this.getLocation();
                        }
                        else
                        {
                            this.requestPermission();
                        }
                    },
                    err => {
                        this.requestPermission();
                    }
                ).catch(() => {
                    this.event.publish('openAlert', 'Kesalahan', 'Gagal memeriksa perijinan untuk akses GPS');
                });
            }
            else if(this.platform.is('ios'))
            {
                this.getLocation();
            }
        });
    }

    requestPermission()
    {
        this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.ACCESS_FINE_LOCATION).then(
            success => {
                this.getLocation();
            },
            err     => {
                this.event.publish('openAlert', 'Informasi', 'Aplikasi gagal mendapatkan ijin untuk mengakses GPS');
            }
        ).catch(() => {
            this.event.publish('openAlert', 'Kesalahan', 'Aplikasi tidak diijinkan untuk mengakses GPS');
        });
    }

    timeout : any;
    getLocation()
    {
        let loading = this.loadingCtrl.create({
            showBackdrop : false,
        });
        loading.present();

        this.timeout = setTimeout(() => {
            this.getMap(loading);
        }, 5000);

        this.geolocation.getCurrentPosition({
            enableHighAccuracy : true
        }).then((resp) => {
            this.lat = resp.coords.latitude;
            this.lng = resp.coords.longitude;
            this.getMap(loading);

            clearTimeout(this.timeout);
        }, error => {
            this.getMap(loading);
            clearTimeout(this.timeout);
        }).catch(() => {
            this.getMap(loading);
            clearTimeout(this.timeout);
        });
    }

    getMap(loading)
    {
        if(this.lat == '')
        {
            this.lat = Config.map.lat;
        }
        if(this.lng == '')
        {
            this.lng = Config.map.lng;
        }

        let mapOptions: GoogleMapOptions = {
            controls    : {
                compass         : true,
                myLocationButton: true,
                indoorPicker    : true,
            },
            gestures    : {
                scroll  : true,
                tilt    : true,
                rotate  : true,
                zoom    : true
            },
            camera  : {
                target  : {
                    lat : this.lat,
                    lng : this.lng
                },
                zoom    : 15,
                tilt    : 30
            },
            preferences : {
                 building   : true
            },
        };

        this.map = GoogleMaps.create('map', mapOptions);
        this.map.one(GoogleMapsEvent.MAP_READY).then(
            () => {
                loading.dismiss();
            },
            () => {
                loading.dismiss();
                this.event.publish('openAlert', 'Kesalahan', 'Gagal memuat Peta, Err 1');
            }
        ).catch(() => {
            loading.dismiss();
            this.event.publish('openAlert', 'Kesalahan', 'Gagal memuat Peta, Err 2');
        });
    }
}
`

**Comment by wf9a5m75** [comment] 2017-12-12 23:47
As I said,

>  Please share your project files on github. I will check it.

**Comment by wf9a5m75** [comment] 2017-12-12 23:51
No contribution, no help. You should know how difficult and how much spend time without reproduce the issue.

For example, you only share part of your code, but for me,
you ask me to write an application like your code.

Key point is `time is money`. You will pay money for my private time?

If no, please share your project files on github. Otherwise, no help.

**Comment by MDavidMR** [comment] 2017-12-12 23:53
Thank you, I really appreciate your help, now I can't upload the project because I am not in my office, but I will. This is important to me and I thank you your time.

**Comment by wf9a5m75** [comment] 2017-12-13 00:04
OK, thank you for the update. I only ask "share your project files", so the repository is not necessary to be public if you mind to leak your source code.

I don't leak your code because I'm not interested in your business. I'm only interested in to fix the issue. So don't worry.

**Comment by candraekas** [comment] 2017-12-13 01:04
My application has been solved, I used the suggestion of issue  #1435, but in command 
`$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_IOS = "(API key)"` 
I delete #multiple_maps, so I pull from the branch master and the plugin I'm using now is version 2.1.1. Sorry, my English is bad.

**Comment by wf9a5m75** [comment] 2017-12-13 01:26
The master branch version is the same as npm version.

**Comment by wf9a5m75** [comment] 2017-12-13 17:13
ping

**Comment by wf9a5m75** [comment] 2017-12-14 17:08
ping

**Comment by wf9a5m75** [comment] 2017-12-18 02:08
Since there is no update for a while, I close this thread. But you can still reply with update.

**Closed by wf9a5m75** 2017-12-18 02:08 UTC
Labels: need more information, pending / waiting
