### ISSUE TITLE
HtmlInfoWindow issues with closing and dragging

### ISSUE THREAD

**Issue by xloading** [mapsplugin/cordova-plugin-googlemaps#1474] opened 2017-05-31 11:16 UTC
Hi Masashi!

I haven't updated v2 plugin in my app for quite a while and yesterday finally decided that the time has come (especially because I was also facing #1376).

I have re-installed latest version of plugin and updated my code to utilize HtmlInfoWindow class instead of InfoWindow.

However I faced two issues with infowindows for now:
1. After opening infowindow it can't be closed by tapping the map (checked only on iOS simulator for now).
I have double checked that the following commit d9e40dda01ed6bfed54edb81a6d01422b3211de4 is present in downloaded plugin code, however the problem still persists

2. There is also some random issue with dragging - in some cases HtmlInfoWindow did not move together with marker when dragging the map.
But I haven't yet figured out exact sequence of steps to reproduce this one, will try to provide more info soon.

Hope you will have time to look into this.

Thanks!

**Comment by wf9a5m75** [comment] 2017-05-31 19:58
Confirmed. I will fix this soon.

**Comment by wf9a5m75** [comment] 2017-05-31 20:21
Fixed. Sorry for the trouble.
Please reinstall the plugin.

```js
$> cordova plugin rm cordova-plugin-googlemaps

$> npm cache clean

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps \
     --variable API_KEY_FOR_ANDROID="<YOUR KEY>" \
     --variable API_KEY_FOR_IOS="<YOUR KEY>" \
     --nofetch
```

**Comment by xloading** [comment] 2017-06-02 08:19
Hi Masashi!

I've re-installed the latest version and haven't changed anything else in the code but... now the map is not draggable/clickable at all. It is drawn fine, all markers are present but clicks/dragging doesn't have any effect.

Just to prevent the extra question, I have cordova.fireDocumentEvent('plugin_touch', {}); present in my code. Also no errors are present in console and system log.

Thanks a lot in advance for helping with this!

**Comment by wf9a5m75** [comment] 2017-06-02 13:47
cordova plugin list

**Comment by wf9a5m75** [comment] 2017-06-02 13:48
If safari web inspector, you need to reload after open it.

**Comment by xloading** [comment] 2017-06-02 13:57
com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"
cordova-custom-config 3.1.4 "cordova-custom-config"
cordova-fabric-plugin 1.1.7 "cordova-fabric-plugin"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-googlemaps 2.0.0-beta2-20170531-1320 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova.plugins.diagnostic 3.5.0 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by xloading** [comment] 2017-06-02 13:58
I have reloaded several times, no effect :(
And there was no such effect before, even after updating to previous version.

**Comment by wf9a5m75** [comment] 2017-06-02 14:01
In that case, please share your project code on github or bitbucket.

**Comment by xloading** [comment] 2017-06-02 14:17
https://bitbucket.org/xloading/guidelanceapp/src

I have added your user to the team ;)

**Comment by wf9a5m75** [comment] 2017-06-02 14:21
Thanks. I will check it later (I just waked up)

**Comment by xloading** [comment] 2017-06-02 14:23
Sure) Let me know if there are any probs and thanks to you!

**Comment by DarthBlaze** [comment] 2017-06-02 16:01
Hey, I also have this bug. I have just updated the plugin.

**Comment by wf9a5m75** [comment] 2017-06-02 16:33
@xloading I just read your code, and this code is wrong at least.

www/js/services.js: 732

https://bitbucket.org/guidelance/guidelanceapp/src/386284fe2f639face46e3d4b873c66142b6f6882/www/js/services.js?at=master&fileviewer=file-view-default#services.js-710:732

```js
infoWindow.setContent([
  '<div class="bubble">',
....
  '</div>'
].join("")       <---
);                   <---
```

**Comment by wf9a5m75** [comment] 2017-06-02 18:05
I inspected your project, and even I removed the maps plugin, 
I can not see this output.
Is there any wrong? (As you may know, I'm not familiar with ionic)

![screen shot 2017-06-02 at 11 03 33 am](https://cloud.githubusercontent.com/assets/167831/26738496/302d3fb4-4783-11e7-8df5-6d0832942beb.png)

**Comment by xloading** [comment] 2017-06-04 14:35
Hi Masashi!

Sorry for inconvenience, I have not shared the project code with anyone before therefore there were discrepancies in the plugins and missed js dependencies.
I have fixed all the issues and committed the changes.

Now all that needs to be done after checking out the repo is:
```
bower install
npm install
cordova platform add ios
cordova emulate ios
```
and you will get through the $ionicPlatform.ready.

**Comment by wf9a5m75** [comment] 2017-06-05 14:08
Thank you for the update. 
Since I've been traveling until June/20, I will check your project when I have a time.
Please wait for a while.

**Comment by s-georgiev** [comment] 2017-06-15 15:03
Hey guys, 
The problem with NOT closing infoWindows on iOS still exists.
When I open one infowindow and then click outside - everything is OK. But if I open one infowindow and then click on another marker to open the second infowindow, the first one does not close.

Here is my "cordova plugin list":
```
com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.0.0-beta2-20170615-1407 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
```
and here is my JS that executes when map is ready:
```
function onMapReady() {

        var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();
        htmlInfoWindow.setContent("<button>tets</button>");
        map.addMarker({
            position: {lat: 42.658881, lng: 23.316087}
        }, function(marker) {
            marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
                htmlInfoWindow.open(marker);
            });
        });

        var htmlInfoWindow2 = new plugin.google.maps.HtmlInfoWindow();
        htmlInfoWindow2.setContent("<button>tets 22</button>");
        map.addMarker({
            position: {lat: 42.658881, lng: 23.317087}
        }, function(marker) {
            marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
                htmlInfoWindow2.open(marker);
            });
        });
}
```

**Comment by xloading** [comment] 2017-06-20 07:18
Hi Masashi,

I'd like to let you know that the original issue with closing/dragging was resolved for me after updating plugin to latest version.

However I face the other difficulty now related to using HtmlInfoWindows with multiple markers. After the approach has changed I always have infowindows duplicated for the whole set of my marker objects. I understand that this is related to asynchronous callback but I'm not clear how this should be fixed in the code.

Here is the example code:
```js
//Loading sights information and placing markers on map
Sight.bylocation({location_id: locationId, lat: position.coords.latitude, lng: position.coords.longitude}, function (data) {
  $rootScope.sights = data;

  for (var i = 0; i < $rootScope.sights.length; i++) {
    if ($rootScope.sights[i].lat) {
      var sightPos = new plugin.google.maps.LatLng($rootScope.sights[i].lat, $rootScope.sights[i].lng);
      $rootScope.latLng.push(sightPos);

      markerId = $rootScope.sights[i].id;
      markerTitle = $rootScope.sights[i].name;
      markerThumbnail = 'http://www.guidelance.com/images/sights/square_small/' + $rootScope.sights[i].main_img;
      markerDetails = 'Tours: ' + $rootScope.sights[i].toursCount + ', Guides: ' + $rootScope.sights[i].guidesCount;

      console.log('Before map addMarker 2');
      var infoWindow = new plugin.google.maps.HtmlInfoWindow();

      map.addMarker({
        'position': sightPos,
        'icon': {
          'url': imgPath('img/sight_marker.png')
        }/*,
        'm_title': markerTitle,
        'm_thumbnail': markerThumbnail,
        'm_id': markerId,
        'm_type': 'sight',
        'm_details': markerDetails*/
      }, function(marker) {

        marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
          infoWindow.setContent(
            [
              '<div class="bubble">',
              '<a href="#/side-menu21/sights/' + markerId + '">',
              ' <div style="overflow:hidden; height:100%">',
              '   <div width="30px" style="float:left; padding:2px; height:100%">',
              '     <div style="height: 100%; position: absolute">',
              '       <img src="' + markerThumbnail + '" height="40px" width="40px">',
              '     </div>',
              '   </div>',
              '   <div width="190px" style="float:left;">',
              '     <div style="height: 100%; position: absolute; left:50px; font-weight: bold; color:#000000;">' + markerTitle.substr(0, 25) + (markerTitle.length > 25 ? '...' : '') + '<br/>',
              '       <span style="font-weight: normal;">' + markerDetails + '</span>',
              '     </div>',
              '   </div>',
              '   <div width="20px" style="float:left; height:100%">',
              '     <div style="height: 100%; position: absolute; left:250px">',
              '       <i class="icon ion-ios-arrow-forward" style="font-size:30px; color:#0000FF; display: inline-block; vertical-align: middle"></i>',
              '     </div>',
              '   </div>',
              '</div>',
              '</a>',
              '</div>'
            ].join("")
          );
          infoWindow.open(marker);
        });

      });
    }

  }
  var latLngBounds = new plugin.google.maps.LatLngBounds($rootScope.latLng);
  
    if($rootScope.latLng.length > 0) {
      console.log('Before camera moved 1');
      console.log(latLngBounds);
      map.moveCamera({
        'target': latLngBounds
      }, function () {
        var cameraPosition = map.getCameraPosition();
        console.log(cameraPosition);
        map.setCameraZoom(Math.floor(cameraPosition.zoom - 1));
        console.log('Camera moved 1');
      });
    }

});
```

After execution of this code I get the same infoWindow for all of my markers.

Could you advise me on the proper resolution?

Thank you!

**Comment by wf9a5m75** [comment] 2017-06-21 23:29
You can write like this:

```js
GuideCoord.bylocation({location_id: locationId, lat: position.coords.latitude, lng: position.coords.longitude}, function(data) {
  $rootScope.guideCoords = data;

  var onMarkerClick = function() {
    var marker = this;
    var guideProfile = marker.get("guideProfile");
    var markerTitle = guideProfile.first_name + ' ' + guideProfile.last_name[0];
    var markerThumbnail = 'http://www.guidelance.com/images/guides/avatar/' + guideProfile.avatar_img;

    infoWindow.setContent([
      '<div class="bubble">',
      '<a href="#/side-menu21/guides/' + markerId + '">',
      ' <div style="overflow:hidden; height:100%">',
      '   <div width="30px" style="float:left; padding:2px; height:100%">',
      '     <div style="height: 100%; position: absolute">',
      '       <img src="' + markerThumbnail + '" height="40px" width="40px">',
      '     </div>',
      '   </div>',
      '   <div width="190px" style="float:left;">',
      '     <div style="height: 100%; position: absolute; left:50px; font-weight: bold; color:#000000;">' + markerTitle.substr(0, 25) + (markerTitle.length > 25 ? '...' : ''),
      '     </div>',
      '   </div>',
      '   <div width="20px" style="float:left; height:100%">',
      '     <div style="height: 100%; position: absolute; left:250px">',
      '       <i class="icon ion-ios-arrow-forward" style="font-size:30px; color:#0000FF; display: inline-block; vertical-align: middle"></i>',
      '     </div>',
      '   </div>',
      '</div>',
      '</a>',
      '</div>'
    ].join("")
    );
  };

  var infoWindow = new plugin.google.maps.HtmlInfoWindow();

  var baseArray = plugin.google.maps.BaseArrayClass($rootScope.guideCoords);
  baseArray.map(function(data, cb) {
    var guidePos = {lat: data.lat, lng: data.lng};
    $rootScope.latLng.push(guidePos);

    var markerId = data.guide_id;

    var guideProfile;
    if ("profile" in data) {
      guideProfile = {
        first_name: data.profile.first_name,
        last_name: data.profile.last_name,
        avatar_img: data.profile.avatar_img
      };
    } else {
      guideProfile = {
        first_name: data.first_name,
        last_name: data.last_name,
        avatar_img: data.avatar_img
      };
    }


    console.log('Before map addMarker 1');

    map.addMarker({
      'position': guidePos,
      'icon': {
        'url': imgPath('img/guide_marker.png')
      },
      'm_title': markerTitle,
      'm_thumbnail': markerThumbnail,
      'm_id': markerId,
      'm_type': 'guide',
      'guideProfile': guideProfile
    }, cb);

  }, function(markers) {

    markers.forEach(function(marker) {
      marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
    });

  });

});
```

**Comment by wf9a5m75** [comment] 2017-06-26 02:09
ping

**Comment by xloading** [comment] 2017-06-27 06:55
Hi Masashi!

I have fully refactored the code as per your suggestion and now the behavior is much better indeed, thank you a lot!

However I still was able to reproduce another issue with infowindows, here's the screencast:
https://youtu.be/Ad9YnDEh3H0

Latest code was committed to guidelanceapp repo on Bitbucket.

**Comment by wf9a5m75** [comment] 2017-06-27 14:11
What version?

**Comment by xloading** [comment] 2017-06-27 14:54
cordova-plugin-googlemaps 2.0.0-beta2-20170615-1407

**Comment by wf9a5m75** [comment] 2017-06-27 16:07
Why do you use old version? The latest version is `2.0.0-beta2-20170625-1805`
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/plugin.xml#L2

The multiple_maps branch has been updated frequently.

**Comment by xloading** [comment] 2017-06-28 08:02
Hi Masashi,

I have updated to the latest version and face much more issues now:
1. Infowindows are not closed by clicking on the map.
2. Infowindows are not tied to marker when dragging the map.
3. For some reason after switching between two types of markers infowindow of the first marker becomes replaced by the second's.

Here's the screencast:
https://youtu.be/Huikho9x5Kw

Hope it helps and thank you for all the efforts!

**Comment by wf9a5m75** [comment] 2017-06-28 11:16
I rebuild your project, but for some reason it does not work.
![screen shot 2017-06-28 at 4 13 17 am](https://user-images.githubusercontent.com/167831/27634553-8148b11e-5bb8-11e7-8584-7c0d8a2aa968.png)

**Comment by xloading** [comment] 2017-06-28 11:19
Did you run
```
bower install
npm install
```
?
I intentionally don't include external sources in the repo.

**Comment by wf9a5m75** [comment] 2017-06-28 11:28
Oh, I forgot `bower install`

**Comment by wf9a5m75** [comment] 2017-06-28 17:08
Sorry, I fixed it. Please try again.

**Comment by wf9a5m75** [comment] 2017-06-30 19:12
ping

**Comment by xloading** [comment] 2017-07-02 07:51
Hi Masashi,

I've updated the plugin and tested your fix.
On the whole everything seems to be working fine - infoWindows are closed properly and no mixing happens.
However every time I closed infoWindows the following errors appeared in the console:
![2017-07-02 10 46 59](https://user-images.githubusercontent.com/1406364/27768111-45d1c814-5f14-11e7-80b0-a8c36579ab15.png)

Thank you indeed!

**Comment by wf9a5m75** [comment] 2017-07-02 14:04
This error only occurs on your project. Please double check your code.

**Comment by wf9a5m75** [comment] 2017-07-06 18:25
ping

**Comment by wf9a5m75** [comment] 2017-07-07 22:52
Since there is no update for a while, I close this issue at this time. But you can still reply for this issue if you have any updates.

**Closed by wf9a5m75** 2017-07-07 22:52 UTC
