### ISSUE TITLE
Application has stopped (Android)

### ISSUE THREAD

**Issue by lsilva23** [mapsplugin/cordova-plugin-googlemaps#2167] opened 2018-03-21 19:15 UTC
I have this bug.
Yesterday I was building normally.
Today phonegap is compiling but when I install on Android I get this error:

```
03-21 15:06:10.381 10948-10948/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: myapp.com, PID: 10948
                                                   java.lang.NoSuchMethodError: No static method checkNotNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbq; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbq' appears in /data/app/myapp.com-2/base.apk)
                                                       at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                                                       at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:209)
                                                       at android.app.Activity.runOnUiThread(Activity.java:5874)
                                                       at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:72)
                                                       at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                                                       at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
                                                       at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
                                                       at org.apache.cordova.PluginManager.init(PluginManager.java:86)
                                                       at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
                                                       at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
                                                       at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
                                                       at myapp.com.MyApp.onCreate(MyApp.java:39)
                                                       at android.app.Activity.performCreate(Activity.java:6687)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by wf9a5m75** [comment] 2018-03-21 19:24
Please share your project files on Github.

**Comment by Michazzz** [comment] 2018-03-22 11:46
Same here, will do update on my github repo

**Comment by DifferentialityDevelopment** [comment] 2018-03-22 12:00
Having the exact same issue.

Below is my package.json, removed api keys for obvious reasons
{
    "name": "-",
    "version": "1.0.0",
    "author": "-",
    "homepage": "-",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/animations": "5.2.1",
        "@angular/common": "5.2.1",
        "@angular/compiler": "5.2.1",
        "@angular/compiler-cli": "5.2.1",
        "@angular/core": "5.2.1",
        "@angular/forms": "5.2.1",
        "@angular/http": "5.2.1",
        "@angular/platform-browser": "5.2.1",
        "@angular/platform-browser-dynamic": "5.2.1",
        "@ionic-native/android-full-screen": "4.5.2",
        "@ionic-native/background-geolocation": "^4.5.3",
        "@ionic-native/background-mode": "^4.5.2",
        "@ionic-native/base64": "4.5.2",
        "@ionic-native/core": "4.5.2",
        "@ionic-native/device": "^4.5.3",
        "@ionic-native/diagnostic": "^4.5.3",
        "@ionic-native/file": "4.5.2",
        "@ionic-native/file-chooser": "4.5.2",
        "@ionic-native/geolocation": "4.5.2",
        "@ionic-native/google-maps": "^4.5.2",
        "@ionic-native/launch-navigator": "^4.5.3",
        "@ionic-native/local-notifications": "^4.5.3",
        "@ionic-native/native-page-transitions": "4.5.2",
        "@ionic-native/native-storage": "4.5.2",
        "@ionic-native/push": "4.5.2",
        "@ionic-native/secure-storage": "4.5.2",
        "@ionic-native/spinner-dialog": "^4.5.2",
        "@ionic-native/splash-screen": "4.5.2",
        "@ionic-native/status-bar": "4.5.2",
        "@ionic/storage": "2.1.3",
        "@types/google-maps": "^3.2.0",
        "ajv": "^6.0.1",
        "com-badrit-base64": "^0.2.0",
        "cordova-android": "7.0.0",
        "cordova-android-support-gradle-release": "^1.2.0",
        "cordova-browser": "5.0.3",
        "cordova-ios": "^4.5.4",
        "cordova-plugin-actionsheet": "^2.3.3",
        "cordova-plugin-app-event": "^1.2.1",
        "cordova-plugin-background-mode": "^0.7.2",
        "cordova-plugin-compat": "^1.2.0",
        "cordova-plugin-device": "^2.0.1",
        "cordova-plugin-dialogs": "^2.0.1",
        "cordova-plugin-file": "^6.0.1",
        "cordova-plugin-filechooser": "^1.0.1",
        "cordova-plugin-fullscreen": "^1.2.0",
        "cordova-plugin-geolocation": "^4.0.1",
        "cordova-plugin-googlemaps": "^2.2.5",
        "cordova-plugin-mauron85-background-geolocation": "^2.3.3",
        "cordova-plugin-native-spinner": "^1.1.3",
        "cordova-plugin-nativestorage": "^2.3.1",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-statusbar": "^2.4.1",
        "cordova-plugin-whitelist": "^1.3.3",
        "cordova.plugins.diagnostic": "^3.9.2",
        "de.appplant.cordova.plugin.local-notification": "^0.8.5",
        "ionic-angular": "^3.9.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.5.6",
        "socket.io-client": "^2.0.4",
        "sw-toolbox": "3.6.0",
        "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.1.3",
        "zone.js": "0.8.20"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.8",
        "ionic": "3.20.0",
        "typescript": "2.6.2"
    },
    "description": "-",
    "cordova": {
        "plugins": {
            "cordova-plugin-device": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-compat": {},
            "cordova-plugin-file": {},
            "cordova-plugin-filechooser": {},
            "cordova-plugin-fullscreen": {},
            "cordova-plugin-geolocation": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-nativestorage": {},
            "cordova-plugin-native-spinner": {},
            "com-badrit-base64": {},
            "cordova.plugins.diagnostic": {},
            "uk.co.workingedge.phonegap.plugin.launchnavigator": {},
            "cordova-plugin-background-mode": {},
            "cordova-plugin-app-event": {},
            "de.appplant.cordova.plugin.local-notification": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "-",
                "API_KEY_FOR_IOS": "-",
                "PLAY_SERVICES_VERSION": "11.8.0",
                "ANDROID_SUPPORT_V4_VERSION": "24.1.0"
            },
            "cordova-plugin-mauron85-background-geolocation": {},
            "cordova-android-support-gradle-release": {
                "ANDROID_SUPPORT_VERSION": "27.+"
            }
        },
        "platforms": [
            "browser",
            "android"
        ]
    }
}

**Comment by wf9a5m75** [comment] 2018-03-22 12:14
Without project files, how can I reproduce your issue?

**Comment by DifferentialityDevelopment** [comment] 2018-03-22 12:34
I managed to resolve my issue, was able to build successfully with play services v4.26
and I added two lines that forced the dependencies for com.google.android.gms:play-services-maps & com.google.android.gms:play-services-location to latest in my build.gradle.

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    compile "com.google.android.gms:play-services-maps:11.8.0"
    compile "com.google.android.gms:play-services-location:11.8.0"
    compile "com.android.support:support-core-utils:24.1.0"
    compile "com.google.android.gms:play-services-location:+"
    compile "com.android.support:support-v4:27.1.0"
    compile "com.android.support:appcompat-v7:26.+"
    compile "com.squareup.okhttp3:okhttp:3+"
    // SUB-PROJECT DEPENDENCIES END
    compile "com.google.android.gms:play-services-location:+"
    compile "com.google.android.gms:play-services-maps:+"
}

After that it built successfully and the app did not crash on load anymore.

**Comment by StobyWan** [comment] 2018-03-22 13:11
I am having the same problem on ionic. Using version 2.2.8 of the plugin.
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
 cordova (Cordova CLI) : 8.0.0 
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 
Environment Variables:
    ANDROID_HOME : /Users/*/Library/Android/sdk
Misc: backend : pro

**Comment by lsilva23** [comment] 2018-03-22 13:15
@DifferentialityDevelopment 
How do you change your build.gradle files using cordova? 
Is there a way of doing this with config.xml?

**Comment by wf9a5m75** [comment] 2018-03-22 14:09
@StobyWan
I guess there are two definitions of `com.android.support:support-core-utils`

This is not bug, it's just conflict with other plugin, such as the google-plus plugin.
Choosing what plugin is your responsibility. If conflict, you need to adjust them.

**Comment by lsilva23** [comment] 2018-03-22 14:26
@wf9a5m75 This is my Project: http://sistema.99car.club/pdrcar.apk

**Comment by wf9a5m75** [comment] 2018-03-22 14:30
Please share your project files on Github.

**Comment by lsilva23** [comment] 2018-03-22 14:30
And on my build log in Phonegap I am getting this:
:app:lintVitalRelease/app/src/main/res/values/strings.xml:3: Error: "app_name" is not translated in "ar" (Arabic), "de" (German), "fr" (French), "hi" (Hindi), "ja" (Japanese), "nl" (Dutch), "pl" (Polish), "pt-PT" (Portuguese: Portugal), "ru" (Russian), "uk" (Ukrainian) [MissingTranslation]
    <string name="app_name">Pdr Car Cliente</string>
            ~~~~~~~~~~~~~~~
/app/src/main/res/values/strings.xml:4: Error: "launcher_name" is not translated in "ar" (Arabic), "de" (German), "fr" (French), "hi" (Hindi), "ja" (Japanese), "nl" (Dutch), "pl" (Polish), "pt-PT" (Portuguese: Portugal), "ru" (Russian), "uk" (Ukrainian) [MissingTranslation]
    <string name="launcher_name">@string/app_name</string>
            ~~~~~~~~~~~~~~~~~~~~
/app/src/main/res/values/strings.xml:5: Error: "activity_name" is not translated in "ar" (Arabic), "de" (German), "fr" (French), "hi" (Hindi), "ja" (Japanese), "nl" (Dutch), "pl" (Polish), "pt-PT" (Portuguese: Portugal), "ru" (Russian), "uk" (Ukrainian) [MissingTranslation]
    <string name="activity_name">@string/launcher_name</string>
            ~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingTranslation":
   If an application has more than one locale, then all the strings declared
   in one language should also be translated in all other languages.

   If the string should not be translated, you can add the attribute
   translatable="false" on the <string> element, or you can define all your
   non-translatable strings in a resource file called donottranslate.xml. Or,
   you can ignore the issue with a tools:ignore="MissingTranslation"
   attribute.

   By default this detector allows regions of a language to just provide a
   subset of the strings and fall back to the standard language strings. You
   can require all regions to provide a full translation by setting the
   environment variable ANDROID_LINT_COMPLETE_REGIONS.

   You can tell lint (and other tools) which language is the default language
   in your res/values/ folder by specifying tools:locale="languageCode" for
   the root <resources> element in your resource file. (The tools prefix
   refers to the namespace declaration http://schemas.android.com/tools.)

3 errors, 0 warnings

**Comment by DifferentialityDevelopment** [comment] 2018-03-22 14:32
@wf9a5m75 I can't seem to agree on this, the app works fine but only causes this issue for me on the lowest supported android version of API 19, ie 4.4.4.
I don't necessarily think it's a bug with the plugin though, nevertheless making sure the app is built with the latest dependencies as I mentioned above seems to fix the issue.

@lsilva23 What play services version are you building with?

**Comment by lsilva23** [comment] 2018-03-22 14:34
@DifferentialityDevelopment 
Are you talking about <preference name="android-minSdkVersion" value="16"/> this?

**Comment by DifferentialityDevelopment** [comment] 2018-03-22 14:37
@lsilva23 Does your app crash on startup or on install?
The error I had on startup was
java.lang.NoSuchMethodError: com.google.android.gms.common.internal.zzbq.checkNotNull
at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)

**Comment by lsilva23** [comment] 2018-03-22 14:38
@DifferentialityDevelopment  On startup! It build successful on Phonegap and Install successful on Android 5.1/7.0

**Comment by DifferentialityDevelopment** [comment] 2018-03-22 14:39
@lsilva23 Did you try the fix I stated earlier of modifying the build.gradle file?

**Comment by lsilva23** [comment] 2018-03-22 14:42
@DifferentialityDevelopment I can't find my build.gradle file, I will post my project files so you can see how I am doing this

**Comment by lsilva23** [comment] 2018-03-22 14:47
I fixed!
Just had to put this variables:
<plugin name="cordova-plugin-googlemaps" spec="^2.2.8">
		<variable name="PLAY_SERVICES_VERSION" value="+" />
		<variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.0" />
		<variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="Aplicativo precisa de sua localização!" />
		<variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Aplicativo precisa de sua localização!" />
	</plugin>
Thank you guys for your time!

**Comment by DifferentialityDevelopment** [comment] 2018-03-22 14:48
Lol, glad you got it fixed.

**Comment by wf9a5m75** [comment] 2018-03-22 21:05
@DifferentialityDevelopment

If you were a plugin developer, and someone reports only logs, what whould you do?
It's not only one, tons of people.
So you would spend your private time for debugging other people problems.
Would you like it?

I don't like it. That's why I ask for everyone to share the project files. Because this is shortest way to solve the problem.
I asked "please share your project files on GitHub", but I don't specify as public repository.
If you don't want to discover your code in public, you just buy a private repo.

You don't agree it? Please just debug the issue by yourself.

**Comment by Michazzz** [comment] 2018-03-22 21:20
@wf9a5m75 I will try to upload my project file (plugin) tomorrow (23 March) from airport, because then I get some time do rebuild my project. I will let you know about it if you want, ok?

**Comment by wf9a5m75** [comment] 2018-03-22 21:41
Yeah, let me know when you are ready please.

**Comment by hackeo1** [comment] 2018-03-23 21:25
Adding <variable name="PLAY_SERVICES_VERSION" value="+" /> did the trick, it may be that 11.8.0 should change to 12.0.0 in the future.

**Comment by DifferentialityDevelopment** [comment] 2018-03-23 21:47
@hackeo Ah! Thanks for that!

**Comment by wf9a5m75** [comment] 2018-03-23 22:09
Plugin configuration is responsibility of app developer, not me, because it's depends on `when`, and `what other plugins you install`. In the past, so many people claimed `<variable name="PLAY_SERVICES_VERSION" value="+" />` because conflict with other plugins.
You can select `+`, but take the risk with your responsibility please.

**Comment by wf9a5m75** [comment] 2018-03-24 21:44
Since it seems the reason is the build configuration, and everyone are solved thier problems, I close this thread.

**Closed by wf9a5m75** 2018-03-24 21:44 UTC
Labels: need more information
