### ISSUE TITLE
Crash on Samsung Galaxy S5 Mini

### ISSUE THREAD

**Issue by jonas-l-b** [mapsplugin/cordova-plugin-googlemaps#2186] opened 2018-03-29 15:39 UTC
**I'm submitting a ...**  (check one with "x")

- [x ] any problem or bug report

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-android-play-services-gradle-release 1.1.4 "cordova-android-play-services-gradle-release"
cordova-plugin-android-fingerprint-auth 1.4.3 "FingerprintAuth"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appminimize 1.0 "AppMinimize"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-device-motion 2.0.0 "Device Motion"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-indexappcontent 0.1.0 "Index App Content"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-shake 0.6.0 "Shake Gesture Detection"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
phonegap-plugin-push 2.1.0 "PushPlugin"

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
The app crashes on an old Samsung Galaxy S5 Mini. When I open the Map, it's fine until I try to interact with it, then the app always crashes. There is no output in the Chrome Webview Debug (probably because it is native)

**Expected behavior:**
I expect it to run as it runs perfect on a OnePlus 5T. I'm just wondering if this is because the S5 Mini is super old (which would be fine because I do not need to support devices that old) or if it has another issue. I hope it is not connected to it being a Samsung phone.

**Comment by wf9a5m75** [comment] 2018-03-29 16:05
`cordova-plugin-googlemaps 2.1.1` is too old. Please reinstall the latest plugin at least.

**Comment by wf9a5m75** [comment] 2018-03-29 16:06
`Android v4.4.2`. wow, it's very old...

**Comment by jonas-l-b** [comment] 2018-03-29 16:27
Actually it got upgraded to Android v5. 


Von: Masashi Katsumata
Gesendet: Donnerstag, 29. März 2018 18:06
An: mapsplugin/cordova-plugin-googlemaps
Cc: jonaslb; Author
Betreff: Re: [mapsplugin/cordova-plugin-googlemaps] Crash on Samsung Galaxy S5Mini (#2186)

Android v4.4.2. wow, it's very old...

**Comment by wf9a5m75** [comment] 2018-03-30 15:44
ping

**Comment by wf9a5m75** [comment] 2018-04-01 06:15
Since there is no additional information, I close this thread.

**Closed by wf9a5m75** 2018-04-01 06:15 UTC
Labels: need more information, pending / waiting

**Comment by thiphariel** [comment] 2018-04-04 16:54
Hello.

I have the same problem with a Samsung Galaxy A5.

Seems to be related with Bitmap.

Here is a crash log from the Play Store : 

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a5y17ltexx/a5y17lte:7.0/NRD90M/A520FXXU4BRB1:user/release-keys'
Revision: '8'
ABI: 'arm64'
pid: 30706, tid: 31331, name: androidmapsapi-  >>> com.levieuxcrayon.mmdd <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x732ea00000
    x0   000000732e9fe003  x1   000000733a67fc00  x2   0000000000000400  x3   0000000000000002
    x4   000000733a67f800  x5   0000000000000fc0  x6   00000000000003f0  x7   0000000000000400
    x8   0000000000000001  x9   0000000000000001  x10  0000000000001000  x11  0000000000000400
    x12  00000000000003ff  x13  0000000000000400  x14  0000000000000400  x15  0000000000000ffc
    x16  0000000000000400  x17  000000732e9fffc3  x18  000000732e9ff003  x19  000000732e9fffff
    x20  000000732f676428  x21  000000733a67f800  x22  0000000000000001  x23  0000040000000400
    x24  0000000000000004  x25  0000000000001000  x26  0000000000000000  x27  000000732e600001
    x28  00000000003fe000  x29  000000732f676400  x30  000000738907a6b4
    sp   000000732f6760e0  pc   0000007389063df4  pstate 0000000020000000

backtrace:
    #00 pc 00000000004c9df4  /system/lib64/libskia.so
    #01 pc 00000000004e06b0  /system/lib64/libskia.so
    #02 pc 00000000003ed688  /system/lib64/libskia.so (_ZN18SkWEBPImageEncoder8onEncodeEP9SkWStreamRK8SkBitmapi+504)
    #03 pc 0000000000110164  /system/lib64/libandroid_runtime.so
    #04 pc 00000000024bbd4c  /system/framework/arm64/boot-framework.oat (offset 0x2014000) (android.graphics.Bitmap.nativeCompress+200)
    #05 pc 00000000024bdd48  /system/framework/arm64/boot-framework.oat (offset 0x2014000) (android.graphics.Bitmap.compress+276)
    #06 pc 00000000000d1f34  /system/lib64/libart.so (art_quick_invoke_stub+580)
    #07 pc 00000000000dec08  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+208)
    #08 pc 000000000028dd48  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+312)
    #09 pc 0000000000286d24  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
    #10 pc 0000000000556ac4  /system/lib64/libart.so (MterpInvokeVirtualQuick+452)
    #11 pc 00000000000c8694  /system/lib64/libart.so (ExecuteMterpImpl+29972)
```

**Comment by wf9a5m75** [comment] 2018-04-04 16:55
Could you share the repository that reproduce this issue 100%?

**Comment by thiphariel** [comment] 2018-04-04 16:58
At this point, no, sorry, I could try to build a test app that reproduce this issue in few days or so. 

But the app should run on a similar Samsung device, otherwise the app won't crash. My app run smoothly on a Nexus 5X for instance, same code.

I'll ping you when I'm ready... Sorry

**Comment by wf9a5m75** [comment] 2018-04-04 17:06
Okay. Please prepare the code that reproduce this issue 100%.
If you think this issue is particularly on Samsung devices, please consider to donate $150 USD (almost half of the average price of Samsung Galaxy A5), I will buy it.
I mean I will pay the other half of the price.

![Uploading Screen Shot 2018-04-04 at 10.03.44 AM.png…]()
