### ISSUE TITLE
Now with your recent changes, addMarkers has stopped working

### ISSUE THREAD

**Issue by jschaves** [mapsplugin/cordova-plugin-googlemaps#1623] opened 2017-08-07 14:04 UTC
Hello, I am devoloping an app and I am using this beta branch.
Now with your recent changes, "Update LatLngBounds.js" addMarkers has stopped working.
The map is created but it does not show any markers.

Here is where it stops working now.
This code was working fine till now.
Thank you in advance for your comments!

```js
  var div = document.getElementById('map');
  map = plugin.google.maps.Map.getMap(div);
  var htmlInfoWindow = [];
  map.one(plugin.google.maps.event.MAP_READY, function() {
    var data = [];
    var objetoarray = {};
    $.each(datosLocales, function(index, value) {
      var resultado = ricolisimo.estadoHorario(datosLocales[index].id);
      if(resultado.queda !== 'Cerrado ahora') {
          html = [
              '<span class="winfomap2">',
              datosLocales[index].name,
              '<br>',
              datosLocales[index].direccion,
              '<br>',
              datosLocales[index].cocina,
              '<br>',
              '<span style="color:green">Abierto ahora</span>',
              '<br>',
              '<a id="' + datosLocales[index].id + '" href="javascript:ricolisimo.mas(' + datosLocales[index].id + ', \'mapa\')"> <button class="mapamas"> Ver más </button> <span id="premas" style="display:none;padding-left:5px;"> <img width="22" src="images/framework/AjaxLoader.gif" /></span></a>',
              '</span>'
          ].join("");
      } else {
          html = [
              '<span class="winfomap3">',
              datosLocales[index].name,
              '<br>',
              datosLocales[index].direccion,
              '<br>',
              datosLocales[index].cocina,
              '<br>',
              '<span style="color:red">Cerrado ahora</span>',
              '<br>',
              '<a id="' + datosLocales[index].id + '" href="javascript:ricolisimo.mas(' + datosLocales[index].id + ', \'mapa\')"> <button class="mapamas"> Ver más </button> <span id="premas" style="display:none;padding-left:5px;"> <img width="22" src="images/framework/AjaxLoader.gif" /></span></a>',
              '</span>'
          ].join("");
      }
      htmlInfoWindow[index] = new plugin.google.maps.HtmlInfoWindow();
      htmlInfoWindow[index].setContent(html);
      objetoarray = {
          position: {
              lat: datosLocales[index].lat,
              lng: datosLocales[index].lng
          },
          icon: {
              'url': icon
          },
          infoWindow: htmlInfoWindow[index]
      };
      data.push(objetoarray);
    });
    // Add markers
    addMarkers(map, data, function(markers) {
      // Set camera position that include all markers.
      var bounds = [];
      data.forEach(function(POI) {
        bounds.push(POI.position);
      });
      map.animateCamera({
        target: bounds,
        duration: 3000,
        padding: 25 
      }, function() {
        
      });
    });
  });
  function addMarkers(map, data, callback) {
    var markers = [];
    function onMarkerAdded(marker) {
      markers.push(marker);
      marker.set("label", "marker" + markers.length);
      marker.on(plugin.google.maps.event.INFO_OPEN, onInfoWindowEvents);
      marker.on(plugin.google.maps.event.INFO_CLOSE, onInfoWindowEvents);
      if (markers.length === data.length) {
        callback(markers);
      }
    }
    data.forEach(function(markerOptions, idx) {
      map.addMarker(markerOptions, onMarkerAdded);
    });
  }
  function onInfoWindowEvents(position) {
    var marker = this;
    var labelStr = marker.get("label");
    var label = document.getElementById(labelStr);
    label.innerText = marker.isInfoWindowShown() ? "open" : "close";
  }
```

**Comment by wf9a5m75** [comment] 2017-08-07 14:06
Could you tell me what version do you use?

Not just v2, but also include the datetime.

**Comment by jschaves** [comment] 2017-08-07 14:13
18 hours ago

https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/86648540ba7628e58e82138aa80c659b13063796

**Comment by wf9a5m75** [comment] 2017-08-07 14:18
ok.

And in the addMarkers(), where is the last executed?

**Comment by jschaves** [comment] 2017-08-07 14:25
data.forEach(function(markerOptions, idx) {
          map.addMarker(markerOptions, onMarkerAdded);
        });

**Comment by wf9a5m75** [comment] 2017-08-07 14:36
Ok. In this case, the markerOptions is the problem.
I guess there are some error log in the native log.
Could check in the native log?

If you're not familiar with, please provide the data.

**Comment by jschaves** [comment] 2017-08-07 15:54
I am not familiar with it, I'm afraid. What data should I send you? Do you mean the output of markerOptions?

**Comment by wf9a5m75** [comment] 2017-08-07 16:07
I guess map.addMarker() faces error. But the error is really depends on the markerOptions.
So please provide the markerOptions.

In your code, `data` variable.

By the way, the `infoWindow` option is already deprecated. 
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/newHtmlInfoWindow/README.md

**Comment by wf9a5m75** [comment] 2017-08-07 16:14
And which OS is the problem, Android or iOS?

**Comment by jschaves** [comment] 2017-08-07 16:41
I only tried it on Android, before it worked on the two

**Comment by wf9a5m75** [comment] 2017-08-07 16:47
Thank you. I understand your situation. Please prepare the data that reproduce your issue.

**Comment by jschaves** [comment] 2017-08-07 17:02
data markerOptions:

Object
lat: "40.4106712"
lng: "-3.7074968"
__proto__: —
Object
url: "images/logo-ricolisimo.png"
__proto__: —
Object
__subs1502124689588: Object
__vars1502124689588: Object
errorHandler: function () { [native code] }
arguments: —
caller: —
length: 1
name: ""
__proto__: —
hashCode: 263160215109
__proto__: —

**Comment by wf9a5m75** [comment] 2017-08-07 17:04
```js
{
  lat: "40.4106712",
  lng: "-3.7074968",
  url: "images/logo-ricolisimo.png"
}
```

Only one?

**Comment by jschaves** [comment] 2017-08-07 17:11
Sorry, I did not copy everything. Here it is:

Object
lat: "40.4106712"
lng: "-3.7074968"
__proto__: —
Object
url: "images/logo-ricolisimo.png"
__proto__: —
Object
__subs1502124689588: Object
icon_changed: Array[1]
infoPosition_changed: Array[1]
infoWindowAnchor_changed: Array[1]
info_close: Array[1]
__proto__: —
__vars1502124689588: Object
content: "<span class="winfomap2">La Barca del patio<br>Plaza de Cascorro, 19<br>Andaluz<br><span style="color…"
frame: HTMLDivElement
accessKey: ""
align: ""
attributes: NamedNodeMap
baseURI: ""
childElementCount: 2
childNodes: NodeList[2]
children: HTMLCollection[2]
classList: DOMTokenList
className: ""
clientHeight: 0
clientLeft: 0
clientTop: 0
clientWidth: 0
contentEditable: "inherit"
dataset: DOMStringMap
dir: ""
draggable: false
firstChild: HTMLDivElement
firstElementChild: HTMLDivElement
hidden: false
id: ""
innerHTML: "<div style="display: block; position: relative; background-color: white; border: 1px solid rgb(204, …"
innerText: ""
isContentEditable: false
lang: ""
lastChild: HTMLDivElement
accessKey: ""
align: ""
attributes: NamedNodeMap
0: Attr
baseURI: null
childNodes: NodeList[1]
0: Text
baseURI: null
childNodes: NodeList[0]
data: "position: relative; margin-top: -1px;"
firstChild: null
lastChild: null
length: 37
localName: null
namespaceURI: null
nextElementSibling: null
nextSibling: null
nodeName: "#text"
nodeType: 3
nodeValue: "position: relative; margin-top: -1px;"
ownerDocument: HTMLDocument
parentElement: null
parentNode: Attr
prefix: null
previousElementSibling: null
previousSibling: null
textContent: "position: relative; margin-top: -1px;"
wholeText: "position: relative; margin-top: -1px;"
__proto__: —
length: 1
__proto__: —
firstChild: Text
isId: false
lastChild: Text
localName: "style"
name: "style"
namespaceURI: null
nextSibling: null
nodeName: "style"
nodeType: 2
nodeValue: "position: relative; margin-top: -1px;"
ownerDocument: HTMLDocument
ownerElement: HTMLDivElement
parentElement: null
parentNode: null
prefix: null
previousSibling: null
specified: true
textContent: "position: relative; margin-top: -1px;"
value: "position: relative; margin-top: -1px;"
__proto__: —
length: 1
__proto__: —
baseURI: ""
childElementCount: 2
childNodes: NodeList[2]
children: HTMLCollection[2]
classList: DOMTokenList
className: ""
clientHeight: 0
clientLeft: 0
clientTop: 0
clientWidth: 0
contentEditable: "inherit"
dataset: DOMStringMap
dir: ""
draggable: false
firstChild: HTMLDivElement
firstElementChild: HTMLDivElement
hidden: false
id: ""
innerHTML: "<div style="position: absolute; left: 50%; height: 0px; width: 0px; margin-left: -15px; border-width…"
innerText: ""
isContentEditable: false
lang: ""
lastChild: HTMLDivElement
lastElementChild: HTMLDivElement
localName: "div"
namespaceURI: "http://www.w3.org/1999/xhtml"
nextElementSibling: null
nextSibling: null
nodeName: "DIV"
nodeType: 1
nodeValue: null
offsetHeight: 0
offsetLeft: 0
offsetParent: null
offsetTop: 0
offsetWidth: 0
onabort: null
onbeforecopy: null
onbeforecut: null
onbeforepaste: null
onblur: null
onchange: null
onclick: null
oncontextmenu: null
oncopy: null
oncut: null
ondblclick: null
ondrag: null
ondragend: null
ondragenter: null
ondragleave: null
ondragover: null
ondragstart: null
ondrop: null
onerror: null
onfocus: null
oninput: null
oninvalid: null
onkeydown: null
onkeypress: null
onkeyup: null
onload: null
onmousedown: null
onmouseenter: null
onmouseleave: null
onmousemove: null
onmouseout: null
onmouseover: null
onmouseup: null
onmousewheel: null
onpaste: null
onreset: null
onscroll: null
onsearch: null
onselect: null
onselectstart: null
onsubmit: null
ontouchcancel: null
ontouchend: null
ontouchmove: null
ontouchstart: null
onwebkitfullscreenchange: null
onwebkitfullscreenerror: null
outerHTML: "<div style="position: relative; margin-top: -1px;"><div style="position: absolute; left: 50%; height…"
outerText: ""
ownerDocument: HTMLDocument
parentElement: HTMLDivElement
parentNode: HTMLDivElement
prefix: null
previousElementSibling: HTMLDivElement
previousSibling: HTMLDivElement
scrollHeight: 0
scrollLeft: 0
scrollTop: 0
scrollWidth: 0
spellcheck: true
style: CSSStyleDeclaration
tabIndex: -1
tagName: "DIV"
textContent: ""
title: ""
translate: true
webkitPseudo: ""
webkitShadowRoot: null
webkitdropzone: ""
__proto__: —
lastElementChild: HTMLDivElement
localName: "div"
namespaceURI: "http://www.w3.org/1999/xhtml"
nextElementSibling: null
nextSibling: null
nodeName: "DIV"
nodeType: 1
nodeValue: null
offsetHeight: 0
offsetLeft: 0
offsetParent: null
offsetTop: 0
offsetWidth: 0
onabort: null
onbeforecopy: null
onbeforecut: null
onbeforepaste: null
onblur: null
onchange: null
onclick: null
oncontextmenu: null
oncopy: null
oncut: null
ondblclick: null
ondrag: null
ondragend: null
ondragenter: null
ondragleave: null
ondragover: null
ondragstart: null
ondrop: null
onerror: null
onfocus: null
oninput: null
oninvalid: null
onkeydown: null
onkeypress: null
onkeyup: null
onload: null
onmousedown: null
onmouseenter: null
onmouseleave: null
onmousemove: null
onmouseout: null
onmouseover: null
onmouseup: null
onmousewheel: null
onpaste: null
onreset: null
onscroll: null
onsearch: null
onselect: null
onselectstart: null
onsubmit: null
ontouchcancel: null
ontouchend: null
ontouchmove: null
ontouchstart: null
onwebkitfullscreenchange: null
onwebkitfullscreenerror: null
outerHTML: "<div style="overflow: visible; position: absolute; display: inline-block;"><div style="display: bloc…"
outerText: ""
ownerDocument: HTMLDocument
parentElement: null
parentNode: null
prefix: null
previousElementSibling: null
previousSibling: null
scrollHeight: 0
scrollLeft: 0
scrollTop: 0
scrollWidth: 0
spellcheck: true
style: CSSStyleDeclaration
tabIndex: -1
tagName: "DIV"
textContent: ""
title: ""
translate: true
webkitPseudo: ""
webkitShadowRoot: null
webkitdropzone: ""
__proto__: —
__proto__: —
errorHandler: function () { [native code] }
hashCode: 263160215109
__proto__: —

**Comment by wf9a5m75** [comment] 2017-08-07 17:18
Well, if you give me the date as JSON style, I appreciate.

**Comment by shrijan** [comment] 2017-08-08 00:33
I have similar issue i was updating from previous version. 

Native log shows
 /var/containers/Bundle/Application/43824954-74F2-40E5-81B5-219A535851AE/MyMosman.app/www/index.html#/www/img/markers/walk.png'
`'icon': {
                    'url' : "www/img/markers/walk.png"
                  }`
it was working ok in v1.

If i use default marker than it works.

I am working in ionic v1.

Thanks
shrijan

**Comment by wf9a5m75** [comment] 2017-08-08 00:40
@shrijan The v1 and v2 are completely different code.
Please double check your code really carefully.

**Comment by shrijan** [comment] 2017-08-08 00:56
@wf9a5m75 It was working fine with android but didn't work with ios.
`I fix that issue using absolute path the image.
'icon': {
                    'url' : cordova.file.applicationDirectory+"www/img/markers/walk.png"
                  }`
I don't think it was issue with the plugin.

**Comment by wf9a5m75** [comment] 2017-08-08 00:58
You can do more simply

```
{
   icon: "img/markers/walk.png"
}
```

**Comment by shrijan** [comment] 2017-08-08 01:11
Thanks

**Comment by wf9a5m75** [comment] 2017-08-10 14:04
@jschaves ping

**Comment by wf9a5m75** [comment] 2017-08-13 17:04
Since there is no update, I close this issue thread.

**Closed by wf9a5m75** 2017-08-13 17:04 UTC
Labels: need more information

**Comment by jschaves** [comment] 2017-08-14 07:45
Changing:
var label = document.getElementById(labelStr);
for
var label = $('#' + labelStr);
works infowindows
