### ISSUE TITLE
Android: White screen issue outside of map when keyboard is visible

### ISSUE THREAD

**Issue by Alex-Sessler** [mapsplugin/cordova-plugin-googlemaps#882] opened 2016-03-08 16:40 UTC
I'm using the map in a subpage of my app, so the map is only initialized when i open this subpage. What i recently discovered is, that when (map was not initialzed yet) the keyboard opens, the content area is covered by a white area (probably from root.setBackgroundColor(Color.WHITE) in GoogleMaps.java). Now when i open the subpage (and the map gets initialized), i can go back to the other pages and trigger the keyboard, just to see everything normal without any white area.
Do you have any idea what i could do about that?
I've seen this issue on Android 5 and 6 so far but haven't tested on any other devices. I'm using Crosswalk 15 and the cordova crosswalk webview plugin 1.4.0.

**Comment by maximeba** [comment] 2016-03-09 17:40
Do you have ` <preference name="xwalkZOrderOnTop" value="true" />` to your config.xml ? If not try adding it and see if that fixes the problem.

**Comment by Alex-Sessler** [comment] 2016-03-09 18:19
It does not fix my problem. 
I've also had an issue with some devices (nexus 5 and sony xperia) where the app would be just blank without the map ever being initialized.
I got it fixed by removing the line:
`view.setLayerType(View.LAYER_TYPE_HARDWARE, null);`
In GoogleMaps.java line 196. 
Apparently LAYER_TYPE_HARDWARE messes the z-index up for some devices more than others. How relevant is this line anyways? I've been googling like mad but couldn't figure anything related to crosswalk.

**Comment by wf9a5m75** [comment] 2016-03-19 14:32
@Alex-Sessler Could you provide some screen captures before and afters, and give some code (or html, css) that reproduce your issue.
Fortunately, I have also Nexus 5. So it should reproduce your issue.

**Comment by wf9a5m75** [comment] 2016-03-24 05:56
Any update for this? If no update in couple of days, I will close this file.

**Comment by wf9a5m75** [comment] 2016-03-25 16:01
@Alex-Sessler There is no problem on my Nexus 5 at all.
I could not reproduce your issue (due to less information).
I close this issue at once. If you have any update, please reopen this issue.

**Closed by wf9a5m75** 2016-03-25 16:01 UTC
