### ISSUE TITLE
cannot use large polyline (like directions)

### ISSUE THREAD

**Issue by caleb87** [mapsplugin/cordova-plugin-googlemaps#1150] opened 2016-10-24 18:44 UTC
When I add a polyline with 10k points (like a directions route), the app freezes and never loads. The most I can load is around 2k points and it takes about 5 seconds.

If I break the route into 500 point segments, and add a polyline for each segment then it loads the entire 10k points in about 2 seconds, but it's in 20 segments.  

Any idea how to use a single polyline?

**Comment by wf9a5m75** [comment] 2016-10-24 19:57
First of all, you need to understand why the Google Maps can not draw the polyline.
Because it's too large data.
You need to simplify your polyline points.


Google published the algorithm how to simplify the polyline (drop the middle points for the specific zoom level).
The document of the algorithm is here.
https://developers.google.com/maps/documentation/utilities/polylinealgorithm

The interactive UI is here.
https://developers.google.com/maps/documentation/utilities/polylineutility

You need to create the simplified polyline path for each zoom levels using interactive UI (or calculate by yourself).

You will get the encoded path strings as the result.

Then you can draw the path using the decode method.
The plugin provides encode/decode methods as the same as Google Maps JavaScript API v3.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Geometry-Library

-------

**Comment by caleb87** [comment] 2016-10-25 16:40
Thanks Masashi.

Google Maps can add 10k points, but I just have to break it into 20 polylines. It loads relatively quick. I guess I will stick to this method for now. 

I was aware of the encoding, but not that it could simplify polylines. This is certainly useful for low zoom levels.

**Comment by caleb87** [comment] 2016-12-22 03:04
I discovered that I can create the polyline with a couple points and then change it with setPoints, and it will load any amount of points quickly. I loaded a route that had 27k points and it was instant.

It seemed odd that it couldn't load 27k points, considering that the JS version could do it easily in my phonegap app. 

This could still be a Google Maps SDK issue, though it may be a plugin problem as well. I don't know.

**Comment by masashiGMS** [comment] 2016-12-22 04:31
Not plugin's problem.

**Comment by caleb87** [comment] 2016-12-22 05:26
So if I add a polyline in a java app with 27k points, the program will crash like it does with this one? But if I setPoints() a polyline with 27k points in a java app, it will load it? Just the same as the plugin?

**Comment by wf9a5m75** [comment] 2016-12-22 06:18
@caleb87 
If you can make your app with Java, I recommend you create without this plugin.
Because in order to help JavaScript, the plugin works lots of things in native side.
It means there is overhead.

I'm not welcome, just complain.
Sending a pull request that resolve the issue is very welcome :)

By the way, the maps plugin v2 is better than v1. Have you tried it?

**Comment by caleb87** [comment] 2016-12-22 17:00
This plugin is amazing, and the documentation is too. It's one of the best cordova plugins I have seen. I have already found a solution to my problem, but I think it would be good to fix the issue for the future.

Maybe the v2 version fixes all this, and if so then problem solved. I will try the v2, and post my findings. 

The overhead is fully acceptable, but the overhead is not the issue. If setPoints() is capable of loading 27,000 points instantly, but addPolyline() is not then that's certainly not an overhead issue. Something is wrong.

I can make a prototype java app to test whether or not the issue is in the Google SDK. I hope to do it Saturday/Sunday. When I finish, I'll post my findings, code and apk. 



My hack-solution for my production app is this:
```
// adding 2 points 
var poly;
map.addPolyline(config, function(r) {
	poly = r;
}
var points = [...]; // 27,000 points
poly.setPoints(points); **// load instantly**
```

The issue:
```
// adding 27k points.... crashes the app, and will even crash it when there's only a few thousand points
var poly; 
map.addPolyline(config, function(r) {
	poly = r;
}
```

**Comment by caleb87** [comment] 2017-01-23 23:53
I migrated the methods to v2. The app worked as expected until I tried to use setPoints() on a large polyline which caused it to crash. In v1, while creating a polyline with thousands of points the app crashed, but  setPoints() will add 20k points almost instantly (my solution posted above). It seems that now in v2 this no longer works.

**Comment by wf9a5m75** [comment] 2017-02-22 15:18
Please provide example data.

**Comment by KimberleeDArmstrong** [comment] 2017-02-22 15:27
You were right I had all power lines Phases A, B, and C dowline from a Substation as a multi-line. That is a BIG multiline. I removed it and it works much better. You can close it. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment] 2017-02-22 17:09
👍

**Closed by wf9a5m75** 2017-02-22 17:09 UTC
