### ISSUE TITLE
App crashes on map in ios

### ISSUE THREAD

**Issue by yasiramidtech** [mapsplugin/cordova-plugin-googlemaps#1431] opened 2017-05-04 09:50 UTC
My app is crashing mostly on map view. I'm using map version 2.0 beta. Getting this error.

```
Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0xf318600> was mutated while being enumerated.'
*** First throw call stack:
(0x1cf60df7 0x1c1c3077 0x1cf60891 0xc69eb 0x222f5a1f 0x220465ed 0x1ce7b4b3 0x1ce7b3e7 0x2204606d 0x222f5a1f 0x220465ed 0x1ce7b4b3 0x1ce7b3e7 0x2204606d 0x222f5a1f 0x222dfa37 0x22010eab 0x222df943 0x222dfbcd 0x227a4fe5 0x227a813d 0x227a25d3 0x1cf1c71b 0x1cf1c1bb 0x1cf1a4fb 0x1ce69533 0x1ce69341 0x1e640bfd 0x22077e67 0x22072591 0x61433 0x1c63350b)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by wf9a5m75** [comment] 2017-05-04 13:48
Did you install the latest code?
And please share your project

**Comment by yasiramidtech** [comment] 2017-05-05 07:34
I have reinstalled the plugin but now plugin.google.maps.event.CAMERA_MOVE_END event is not working

**Comment by wf9a5m75** [comment] 2017-05-05 07:44
I just confirmed the CAMERA_MOVE_END works perfectly.

```js
document.addEventListener("deviceready", function() {
  var mapDiv = document.getElementById("map_canvas");
  var options = {
    'camera': {
      'zoom': 13,
      'center': {"lat": 37.4419, "lng": -122.1419}
    }
  };
  var map = plugin.google.maps.Map.getMap(mapDiv, options);
  map.on(plugin.google.maps.event.MAP_READY, onMapReady);
});

function onMapReady() {
  var map = this;

  map.on(plugin.google.maps.event.CAMERA_MOVE_END, function() {
    alert("--->CAMERA_MOVE_END");
  });

}
```

**Comment by wf9a5m75** [comment] 2017-05-05 07:51
By the way, I committed some code to prevent crash for iOS.
Please reinstall the plugin.

**Comment by yasiramidtech** [comment] 2017-05-05 07:53
This code was working before reinstalled the plugin.

  $ionicPlatform.ready(function ()
    {
        var div = document.getElementById("map_canvas");
        map = plugin.google.maps.Map.getMap(div);
        var lat, long;
        var onSuccess = function (location)
        {
            
            map.setMyLocationEnabled(true);
            var msg = ["Current your location:\n",
            "latitude:" + location.latLng.lat,
            "longitude:" + location.latLng.lng,
            "speed:" + location.speed,
            "time:" + location.time,
            "bearing:" + location.bearing].join("\n");

            map.animateCamera({
                'target': location.latLng,// { lat: 30.195825588923114, lng: 71.42629131674767 },//location.latLng,
                'tilt': 20,
                'zoom': 16,
                'bearing': 25,
                'duration': 300 // 1/2 seconds
            },

            function ()
            {
               
                map.on(plugin.google.maps.event.CAMERA_MOVE_END, function (location)
                {

                    counter = counter + 1;
                    console.log(counter);
                    //$('#SlideDiv').animate({ 'height': '110px', }, 250);
                    console.log(location.target.lat);
                    console.log(location.target.lng);
                      
                    
                })

                });
            };

        var onError = function (msg)
        {
           // alert("error: " + msg);
        };
        map.getMyLocation(onSuccess, onError);
        
    });

**Comment by yasiramidtech** [comment] 2017-05-05 07:54
Ok i try again

**Comment by yasiramidtech** [comment] 2017-05-05 09:41
I used above your mentioned code and again reinstalled the plugin but CAMERA_MOVE_END event not working

**Comment by wf9a5m75** [comment] 2017-05-05 22:00
What version of iOS do you use?

**Comment by yasiramidtech** [comment] 2017-05-08 04:37
Xcode 8.2.1
Build version 8C1002

**Comment by wf9a5m75** [comment] 2017-05-08 04:49
No, I asked iOS version. Not Xcode.

**Comment by wf9a5m75** [comment] 2017-05-08 04:50
And I test on my iPhone SE 10.3.1, but the CAMERA_MOVE_END event works perfectly.

**Comment by yasiramidtech** [comment] 2017-05-08 05:05
iPhone 5S 10.3.1

**Comment by wf9a5m75** [comment] 2017-05-08 05:08
In that case, the plugin should work.

Please try again with only pure cordova framework (no ionic, etc).

**Comment by yasiramidtech** [comment] 2017-05-08 05:14
Ok i try again then let you know.
Thank You.

**Comment by yasiramidtech** [comment] 2017-05-08 05:34
It is not working yet. Before reinstall the plugin CAMERA_MOVE_END event was working fine. Can i install again that version??

**Comment by wf9a5m75** [comment] 2017-05-08 05:43
You can specify the commit id.
https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#syntax

```
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#(commit id)
```

**Comment by yasiramidtech** [comment] 2017-05-08 07:58
I have reinstalled the older version now all events are working. But map markers are not showing on the map and facing again crashes issues

**Comment by wf9a5m75** [comment] 2017-05-08 14:03
So, what's error?
Please attach more information.

**Comment by wf9a5m75** [comment] 2017-05-26 16:09
Since there is no update in last 18 days, I close this issue at once.
If you have any updates, you can reopen this issue or just simply reply your message.

**Closed by wf9a5m75** 2017-05-26 16:09 UTC
