### ISSUE TITLE
Error when removing map

### ISSUE THREAD

**Issue by yoleth** [mapsplugin/cordova-plugin-googlemaps#1823] opened 2017-10-18 16:05 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[x] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
code-push 2.0.1-beta "CodePushAcquisition"
com.adjust.sdk 4.11.3 "Adjust"
com.bma4s.sdk.plugins.cordova 1.3.5 "BMA4S"
com.cordova.plugins.cookiemaster 1.0.1 "CookieMaster"
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-android-play-services-gradle-release 0.0.2 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 1.1.2 "cordova-android-support-gradle-release"
cordova-fabric-plugin 1.1.9 "cordova-fabric-plugin"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-code-push 1.9.6-beta "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.4-dev "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.0.0 "PushPlugin"
```
package.json

```
"dependencies": {
    "@angular/animations": "^4.3.4",
    "@angular/common": "4.3.4",
    "@angular/compiler": "4.3.4",
    "@angular/compiler-cli": "4.3.4",
    "@angular/core": "4.3.4",
    "@angular/forms": "4.3.4",
    "@angular/http": "4.3.4",
    "@angular/platform-browser": "4.3.4",
    "@angular/platform-browser-dynamic": "4.3.4",
    "@angular/platform-server": "^4.3.4",
    "@angular/router": "^4.3.4",
    "@ionic-native/android-permissions": "^4.2.1",
    "@ionic-native/app-availability": "^4.2.1",
    "@ionic-native/core": "^4.2.1",
    "@ionic-native/deeplinks": "^4.1.0",
    "@ionic-native/device": "^4.3.1",
    "@ionic-native/facebook": "^4.1.0",
    "@ionic-native/fcm": "^4.3.1",
    "@ionic-native/file": "^3.12.1",
    "@ionic-native/file-opener": "^4.2.1",
    "@ionic-native/file-transfer": "^4.2.1",
    "@ionic-native/firebase": "^4.2.1",
    "@ionic-native/google-analytics": "^4.1.0",
    "@ionic-native/google-maps": "^4.2.1",
    "@ionic-native/in-app-browser": "^4.1.0",
    "@ionic-native/keyboard": "^4.1.0",
    "@ionic-native/local-notifications": "^4.2.1",
    "@ionic-native/network": "^4.2.1",
    "@ionic-native/push": "^3.14.0",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "^4.2.1",
    "@ionic-native/themeable-browser": "^4.2.0",
    "@ionic-native/transfer": "^3.12.1",
    "@ionic/storage": "2.0.1",
    "@ng-idle/core": "^2.0.0-beta.12",
    "@ng-idle/keepalive": "^2.0.0-beta.12",
    "@types/google-maps": "^3.2.0",
    "@types/underscore": "^1.8.1",
    "angular2-http-interceptor": "^4.0.0",
    "angular2-local-storage": "^0.2.0",
    "angular2-moment": "^1.6.0",
    "angularfire2": "^4.0.0-rc.1",
    "code-push": "^2.0.1-beta",
    "com.adjust.sdk": "^4.11.2",
    "com.bma4s.sdk.plugins.cordova": "^1.3.4",
    "com.cordova.plugins.cookiemaster": "^1.0.1",
    "com.googlemaps.ios": "https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk",
    "cordova-android": "^6.2.3",
    "cordova-android-play-services-gradle-release": "0.0.2",
    "cordova-android-support-gradle-release": "^1.0.0",
    "cordova-fabric-plugin": "^1.1.9",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-android-native-pdfviewer": "^1.2.0",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-app-event": "^1.2.1",
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-code-push": "^1.9.6-beta",
    "cordova-plugin-compat": "^1.1.0",
    "cordova-plugin-console": "^1.0.7",
    "cordova-plugin-device": "^1.1.6",
    "cordova-plugin-dialogs": "^1.3.3",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-file-opener2": "^2.0.19",
    "cordova-plugin-file-transfer": "^1.6.3",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-google-analytics": "^1.8.3",
    "cordova-plugin-googlemaps": "^2.0.0",
    "cordova-plugin-googlemaps-sdk": "https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
    "cordova-plugin-inappbrowser": "^1.7.1",
    "cordova-plugin-network-information": "^1.3.3",
    "cordova-plugin-splashscreen": "https://github.com/apache/cordova-plugin-splashscreen.git",
    "cordova-plugin-statusbar": "^2.2.3",
    "cordova-plugin-themeablebrowser": "https://github.com/yoleth/cordova-plugin-themeablebrowser.git",
    "cordova-plugin-whitelist": "^1.3.2",
    "cordova-plugin-zip": "^3.1.0",
    "de.appplant.cordova.plugin.local-notification": "^0.8.5",
    "firebase": "^4.3.0",
    "ionic-angular": "3.6.0",
    "ionic-native": "^2.9.0",
    "ionic-plugin-deeplinks": "https://github.com/Guidobraak9/ionic-plugin-deeplinks.git",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "ngx-clipboard": "^8.0.3",
    "node-js-marker-clusterer": "^1.0.0",
    "phonegap-plugin-push": "^2.0.0",
    "promise-polyfill": "6.0.2",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "underscore": "^1.8.3",
    "xcode": "^0.9.3",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.2",
    "@ionic/app-scripts": "^2.1.3",
    "gulp": "^3.9.1",
    "gulp-replace": "^0.6.1",
    "gulp-sass": "^3.1.0",
    "ionic": "3.13.1",
    "ios-sim": "^6.1.1",
    "node-sass": "^3.3.3",
    "npm": "^5.2.0",
    "typescript": "^2.4.2",
    "xcode": "^0.9.3"
  }
```

**Current behavior:**
When trying to remove map, error occured  and map is not removed.

```
vendor.js:1378 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at MarkerCluster.<anonymous> (vendor.js:76393)
    at MarkerCluster.callback (BaseClass.js:101)
    at MarkerCluster.trigger (BaseClass.js:62)
    at MarkerCluster.remove (MarkerCluster.js:286)
    at clearObj (Map.js:554)
    at Map.remove (Map.js:563)
    at callInstance (vendor.js:120390)
    at vendor.js:120555
    at vendor.js:74733
    at new t (polyfills.js:3)
    at MarkerCluster.<anonymous> (vendor.js:76393)
    at MarkerCluster.callback (BaseClass.js:101)
    at MarkerCluster.trigger (BaseClass.js:62)
    at MarkerCluster.remove (MarkerCluster.js:286)
    at clearObj (Map.js:554)
    at Map.remove (Map.js:563)
    at callInstance (vendor.js:120390)
    at vendor.js:120555
    at vendor.js:74733
    at new t (polyfills.js:3)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4239)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>
```

**Expected behavior:**
Remove map correctly

**Steps to reproduce:**
Creat a map, add clusters and then call remove on it.

**Comment by wf9a5m75** [comment] 2017-10-18 16:08
Please share your project files on github.

**Comment by stormwin** [comment] 2017-10-18 17:52
i see similar/same error in console on my app. The app work normally after the error. No crash or white screens. i will try to create test repo later today. i have a map, few markers and htmlinfowindow

**Comment by wf9a5m75** [comment] 2017-10-19 16:42
ping

**Comment by msepp** [comment] 2017-10-24 12:27
I had a similar error. I have a map where I add a single marker after the `MAP_READY` event. If I try to call `.remove()` on the map instance, I get the reported error.  

Calling map `.clear()` before `.remove()` fixed it for me.

**Comment by wf9a5m75** [comment] 2017-10-24 20:46
@msepp Actually you just need to execute `map.remove()` only for your case.
Because the `map.remove()` executes the same code as `map.clear()` internally.

**Comment by stormwin** [comment] 2017-10-24 23:35
The error only appear in ionic. I think that the problem is in ionic wrapper.
this is very simple ionic app that add multiple markers, wait for 10 seconds and then map.remove();
The error will appear in console.
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at Marker.<anonymous> (vendor.js:77724)
    at Marker.callback (BaseClass.js:101)
    at Marker.trigger (BaseClass.js:62)
    at Marker.remove (Marker.js:112)
    at clearObj (Map.js:554)
    at Map.remove (Map.js:563)
    at callInstance (vendor.js:75729)
    at vendor.js:75894
    at vendor.js:57839
    at new t (polyfills.js:3)
    at Marker.<anonymous> (vendor.js:77724)
    at Marker.callback (BaseClass.js:101)
    at Marker.trigger (BaseClass.js:62)
    at Marker.remove (Marker.js:112)
    at clearObj (Map.js:554)
    at Map.remove (Map.js:563)
    at callInstance (vendor.js:75729)
    at vendor.js:75894
    at vendor.js:57839
    at new t (polyfills.js:3)
    at c (polyfills.js:3)
    at new t (polyfills.js:3)
    at tryNativePromise (vendor.js:57838)
    at getPromise (vendor.js:57846)
    at GoogleMap.<anonymous> (vendor.js:75877)
    at GoogleMap.value [as remove] (vendor.js:118185)
    at main.js:105
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4238)
    at t.invokeTask (polyfills.js:3)
```
https://github.com/stormwin/testmap2

**Comment by wf9a5m75** [comment] 2017-10-25 07:05
It seems the wrapper plugin executes `map.remove` twice for some reason.
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at Marker.<anonymous> (vendor.js:77724)
    at Marker.callback (BaseClass.js:101)
    at Marker.trigger (BaseClass.js:62)
    at Marker.remove (Marker.js:112)
    at clearObj (Map.js:554)
    at Map.remove (Map.js:563)  <---
    at callInstance (vendor.js:75729)
    at vendor.js:75894
    at vendor.js:57839
    at new t (polyfills.js:3)
    at Marker.<anonymous> (vendor.js:77724)
    at Marker.callback (BaseClass.js:101)
    at Marker.trigger (BaseClass.js:62)
    at Marker.remove (Marker.js:112)
    at clearObj (Map.js:554)
    at Map.remove (Map.js:563)   <---
    at callInstance (vendor.js:75729)
    at vendor.js:75894
    at vendor.js:57839
    at new t (polyfills.js:3)
    at c (polyfills.js:3)
    at new t (polyfills.js:3)
    at tryNativePromise (vendor.js:57838)
    at getPromise (vendor.js:57846)
    at GoogleMap.<anonymous> (vendor.js:75877)
    at GoogleMap.value [as remove] (vendor.js:118185)
    at main.js:105
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4238)
    at t.invokeTask (polyfills.js:3)
```

**Comment by wf9a5m75** [comment] 2017-10-26 02:35
Thank you for reporting this bug. I fixed the wrapper plugin code, and send it as a PR.
https://github.com/ionic-team/ionic-native/pull/2035

After the PR is merged, the ionic team will release it as a new version.

Then please reinstall the `@ionic-native/core` and the `@ionic-native/google-maps` with latest version.
The problem should be gone.

**Comment by jalescardoso** [comment] 2017-10-28 12:44
I have the same problem with ionic. thank you all.

**Comment by stormwin** [comment] 2017-10-28 12:57
I can confirm that this bug is fixed partially. 
Everything is working fine now except HtmlinfoWindow.
When HtmlInfoWindows is opened, map.remove() will cause this error

```
TypeError: Cannot read property 'removeChild' of undefined
    at HTMLInfoWindow.close (HtmlInfoWindow.js:290)
    at Marker.callback (BaseClass.js:101)
    at Marker.trigger (BaseClass.js:62)
    at Marker.remove (Marker.js:118)
    at clearObj (Map.js:564)
    at Map.remove (Map.js:573)
    at l (vendor.js:1)
    at vendor.js:1
    at vendor.js:1
    at new t (polyfills.js:3)
    at HTMLInfoWindow.close (HtmlInfoWindow.js:290)
    at Marker.callback (BaseClass.js:101)
    at Marker.trigger (BaseClass.js:62)
    at Marker.remove (Marker.js:118)
    at clearObj (Map.js:564)
    at Map.remove (Map.js:573)
    at l (vendor.js:1)
    at vendor.js:1
    at vendor.js:1
    at new t (polyfills.js:3)
    at c (polyfills.js:3)
    at new t (polyfills.js:3)
    at vendor.js:1
    at A (vendor.js:1)
    at e.<anonymous> (vendor.js:1)
    at e.value [as remove] (vendor.js:1)
    at n.ionViewWillUnload (main.js:1)
    at t._lifecycle (vendor.js:1)
    at t._willUnload (vendor.js:1)
    at e._willUnload (vendor.js:1)
```

i have installed latest google-maps plugin from multiple_maps branch, and build latest ionic version including your unmerged commits.

**Comment by wf9a5m75** [comment] 2017-10-28 15:47
Did you update the repository code?

**Comment by stormwin** [comment] 2017-10-28 16:03
i've just updated test repository.

https://github.com/stormwin/testmap2

**Comment by wf9a5m75** [comment] 2017-10-28 16:39
Fixed.

**Comment by stormwin** [comment] 2017-10-29 17:18
I can confirm that this issue is fixed now.

Thanks

**Closed** 2017-10-29 18:05 UTC
Labels: @ionic-native/googlemaps, bug, confirmed, fixed, pending / waiting

**Comment by wf9a5m75** [comment] 2017-10-30 17:45
The people who have been waiting the PR is accepted.
The PR is still waiting. If you can't wait it, you can build from my repository.

```
$> git clone https://github.com/wf9a5m75/ionic-native

$> cd ionic-native

$> node -v
7.10

$> npm run build google-maps

$> cd (your project folder)

$> npm uninstall @ionin-native/core @ionic-native/google-maps

$> npm install (path to)/ionic-native/dist/\@ionic-native/core

$> npm install (path to)/ionic-native/dist/\@ionic-native/google-maps
```

**Comment by wf9a5m75** [comment] 2017-11-01 20:20
The PR is merged. Please reinstall the `@ionic-native/google-maps@4.3.3`, `@ionic-native/core@4.3.3`, and `cordova-googlemaps-plugin@2.1.0`.
