### ISSUE TITLE
blank map on ios 9.3.5 

### ISSUE THREAD

**Issue by dsemerida** [mapsplugin/cordova-plugin-googlemaps#1125] opened 2016-09-29 21:49 UTC
Im test on ios 9.3 but not load the map full only blank map i´ve followed instructions to load map but i didnt get nothing, any some helpme?

**Comment by wf9a5m75** [comment] 2016-09-29 22:06
Use the master branch.

**Comment by dimkaone** [comment] 2016-09-30 08:20
i'm use master branch, but it didn't get nothing.

**Comment by wf9a5m75** [comment] 2016-09-30 09:21
Provided information is less. Please report more information, such native log, screen capture, etc.

**Comment by dsemerida** [comment] 2016-09-30 18:15
![66999095-73f2-47e0-85c7-9661512f8e43](https://cloud.githubusercontent.com/assets/17621449/19002053/dc7f16c8-870f-11e6-9f6b-80c5c5b40c96.jpg)

i send this image for you see the blank map

**Comment by wf9a5m75** [comment] 2016-09-30 18:25
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/TroubleShooting:-Blank-Map

**Comment by wf9a5m75** [comment] 2016-10-05 18:09
@dsemerida Did you solve your problem?

**Comment by celron** [comment] 2016-10-07 20:01
Greetings @wf9a5m75, I have begun to run into a problem on ios 9.3.5, where a black screen occurs, while on ios 10 it seems fine, so it is not a map key problem.

I am using the master branch the plugin from today.  The last version that I used with no problem was from September 21, and you've made several changes since then.

Currently I see this in xcode
```
2016-10-07 15:20:09.764 hiamaps[1519:283196] Apache Cordova native platform version 4.2.1 is starting.
2016-10-07 15:20:09.765 hiamaps[1519:283196] Multi-tasking -> Device: YES, App: YES
2016-10-07 15:20:09.841 hiamaps[1519:283196] Using UIWebView
2016-10-07 15:20:09.843 hiamaps[1519:283196] [CDVTimer][handleopenurl] 0.096023ms
2016-10-07 15:20:09.845 hiamaps[1519:283196] [CDVTimer][intentandnavigationfilter] 2.359986ms
2016-10-07 15:20:09.846 hiamaps[1519:283196] [CDVTimer][gesturehandler] 0.086010ms
2016-10-07 15:20:09.870 hiamaps[1519:283196] [CDVTimer][file] 24.003029ms
2016-10-07 15:20:09.892 hiamaps[1519:283196] [CDVTimer][socialsharing] 21.694005ms
2016-10-07 15:20:09.892 hiamaps[1519:283196] [CDVTimer][keyboard] 0.311017ms
2016-10-07 15:20:09.903 hiamaps[1519:283196] [CDVTimer][splashscreen] 10.708988ms
2016-10-07 15:20:09.905 hiamaps[1519:283196] [CDVTimer][universallinks] 1.437008ms
2016-10-07 15:20:09.907 hiamaps[1519:283196] [CDVTimer][googlemaps] 1.753032ms
2016-10-07 15:20:09.907 hiamaps[1519:283196] [CDVTimer][TotalPluginStartup] 63.921988ms
2016-10-07 15:20:10.455 hiamaps[1519:283196] Resetting plugins due to page load.
2016-10-07 15:20:11.205 hiamaps[1519:283196] Finished load of: file:///var/containers/Bundle/Application/0E35E5A2-92DD-44EF-91E9-A34196DC2DDD/hiamaps.app/www/index.html

And it ends there.

I am about to try loading a previous version of the plugin but wanted to see if you had any idea if any of the changes could cause a problem in iOS 9.3.5

**Comment by celron** [comment] 2016-10-07 20:04
![image](https://cloud.githubusercontent.com/assets/7539817/19203871/b18c669e-8ca7-11e6-9947-e4ed7dc95e00.png)

**Comment by wf9a5m75** [comment] 2016-10-07 20:25
Please upload your project file everything to github and share with me.
I think problem is in your project.

**Comment by celron** [comment] 2016-10-07 21:08
I've shared the project with you, the current branch to use is add_panel_system.  If you have questions about the project you can email me at celron@gmail.com

**Comment by celron** [comment] 2016-10-08 16:58
@wf9a5m75, while I have not found the problem it appears that there is something different between ios 9.3.5 and 10 which is causing the problem along with some embedded code changes.  You can ignore looking at the project as I dig into the problem.

**Comment by adaniello** [comment] 2016-10-18 14:33
@celron Any news about this issue?
My app has stopped working since iOS 10.0.2 update.
Thanks

**Comment by wf9a5m75** [comment] 2016-10-18 22:03
Visual Studio user have to fix the problem by your self.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1127#issuecomment-253313235

**Comment by grapemix** [comment] 2016-10-23 09:22
+1.
Not working in iOS 10.0.2
Working in android

Since android is working, we assume that our code does not cause the problem. We confirmed our api keys for iOS is fine and Google Maps SDK for iOS is enable like thousand times.

Please help!

**Comment by adaniello** [comment] 2016-10-23 09:56
I investigated on it with 32 iOS devices: there's this issue with iOS 10.0.2 only with older devices (eg. iPhone 5s) but not with newer (eg. iPhone 6s, iPhone 7).
With a device, i tried to downgrade iOS and on this device app works fine again.
Similar issue already found with 9.3.4 version.
Note: i'm telling about an app with no updates in last 5 months.

**Comment by wf9a5m75** [comment] 2016-10-23 18:52
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#version-20-beta

**Comment by grapemix** [comment] 2016-10-26 18:04
@adaniello, we tested on iPhone6 in iOS 10.1 with app built by phonegap cloud build + cordova-iOS 4.2.0 and we still have no luck 
@wf9a5m75 , I have no idea what do you refer. Would you mind elaborate?

Thanks for the reply.

**Comment by wf9a5m75** [comment] 2016-11-22 22:07
Do you guys any update on this issue?

**Comment by baconfat** [comment] 2016-11-24 02:26
I am seeing the same behaviour as reported by @adaniello https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1125#issuecomment-255577814

- Blank map with iOS 10.0.2
- Map is loaded on Android 7.0

I tried reverting to older commits [0] to see if I can get the map to appear with a previous version but those appear broken as well. I can only guess it's because the plugin.xml always pulls `master` for the SDK [1]

[0] https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/21a461fe329f37b57f0cbf2589172af537c629c0 
[1] https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/21a461fe329f37b57f0cbf2589172af537c629c0/plugin.xml#L221

**Comment by wf9a5m75** [comment] 2016-11-24 03:28
Please provide android native logs or example apk.
I don't have any problem with the latest plugin and the latest cordova.

**Comment by baconfat** [comment] 2016-11-24 12:40
@wf9a5m75 the plugin works on Android. The blank map issue is happening on iOS 10.0.2

**Comment by wf9a5m75** [comment] 2016-11-24 17:48
I don't have any problem with iOS10 also.
Please provide xcode log or your project. Otherwise I can't inspect your issue, then I close this issue.

**Comment by baconfat** [comment] 2016-11-24 21:39
@wf9a5m75, here's my xcode log: [xcode.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/612200/xcode.txt)

I double checked the API key that I am using and verified that it's correct.

Cheers

**Comment by wf9a5m75** [comment] 2016-11-24 21:50
Thank you. I will check the log later.
By the way, which plugin do you use,  v1.3.9(npm) or v1.4.0beta(master)?

**Comment by baconfat** [comment] 2016-11-24 21:56
I am using v1.4.0beta (master)

**Comment by wf9a5m75** [comment] 2016-11-24 23:44
I chevked your lig, but it seems there are lots of (network) errors before the map plugin running.

**Comment by baconfat** [comment] 2016-11-25 18:39
@wf9a5m75, it appears to be something wrong with my API key for iOS. I generated a new API key and the map is displayed for me now on iOS 10.0.2

**Comment by wf9a5m75** [comment] 2016-11-25 18:56
Good :)

**Closed by wf9a5m75** 2016-11-25 18:56 UTC
