### ISSUE TITLE
PluginStreetViewPanorama/ Error on compiling for iOS Simulator

### ISSUE THREAD

**Issue by riyuk** [mapsplugin/cordova-plugin-googlemaps#2401] opened 2018-08-22 13:34 UTC
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**node/cordova information**

```
node -v = v10.5.0
cordova -v = 8.0.0

cordova platform ls
Installed platforms:
  browser 5.0.3
  ios 4.5.5
```

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.11 "cordova-plugin-googlemaps"
cordova-plugin-googleplaces 0.0.5 "Google Places"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Related code, data or error log (please format your code or data):**

```
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/riyuk/Library/Developer/Xcode/DerivedData/<project>-afvuidbzgmstlnbalzqyjgwoqjup/Build/Intermediates.noindex/<project>.build/Debug-iphonesimulator/<project>.build/Objects-normal/x86_64/PluginStreetViewPanorama.o <project>/Plugins/cordova-plugin-googlemaps/PluginStreetViewPanorama.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
(node:65097) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/riyuk/dev/lab/<project>/<project>/platforms/ios/cordova/build-debug.xcconfig,-workspace,<project>.xcworkspace,-scheme,<project>,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/riyuk/dev/lab/<project>/<project>/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/riyuk/dev/lab/<project>/<project>/platforms/ios/build/sharedpch
(node:65097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wf9a5m75** [comment] 2018-08-22 13:46
Please share your project files on GitHub.
I have NO problem.

**Comment by riyuk** [comment] 2018-08-22 16:50
When I delete the following lines in PluginStreetViewPanorama.m (Line 82-89) it actually works. I have no plans to use StreetView - so I guess it'll be fine.

```
GMSPanoramaSource source = [@"OUTDOOR" isEqualToString:[cameraOpts objectForKey:@"source"]] ?
          kGMSPanoramaSourceOutside : kGMSPanoramaSourceDefault;
        if ([cameraOpts objectForKey:@"radius"]) {
          int radius = [[cameraOpts objectForKey:@"radius"] intValue];
          [self.panoramaCtrl.panoramaView moveNearCoordinate:location radius:radius source:source];
        } else {
          [self.panoramaCtrl.panoramaView moveNearCoordinate:location source:source];
        }
```

The errors XCode prints (when I open the XCode Project) are:
```
Interface type cannot be statically allocated 
FIX: Insert '*'

Unknown type name 'GMSPanoramaSource'; did you mean 'GMSPanoramaService'?
FIX: Replace 'GMSPanoramaSource' with 'GMSPanoramaService'

Use of undeclared identifier 'kGMSPanoramaSourceDefault'
Use of undeclared identifier 'kGMSPanoramaSourceOutside'

No visible @interface for 'GMSPanoramaView' declares the selector 'moveNearCoordinate:radius:source:'

No visible @interface for 'GMSPanoramaView' declares the selector 'moveNearCoordinate:source:'
```

**Comment by wf9a5m75** [comment] 2018-08-22 17:26
I wonder there are definitions `kGMSPanoramaSourceDefault` and `kGMSPanoramaSourceOutside`.
https://developers.google.com/maps/documentation/ios-sdk/reference/group___panorama_source

I'll check it later. Thanks.

**Comment by wf9a5m75** [comment] 2018-08-24 00:50
Umm, I can not reproduce this issue. I have no problem.
![screen shot 2018-08-23 at 5 48 13 pm](https://user-images.githubusercontent.com/167831/44559116-beed6b00-a6fc-11e8-86de-068658c5e2c6.png)


Since I can not reproduce this issue, and no additional resources at this time, I close this thread.
But I will this keep in mind. Thank you for reporting.

**Closed by wf9a5m75** 2018-08-24 00:50 UTC
Labels: pending / waiting
