### ISSUE TITLE
Android build failing for 1.4.0

### ISSUE THREAD

**Issue by anaganisk** [mapsplugin/cordova-plugin-googlemaps#1218] opened 2016-12-10 14:20 UTC
The build process of android is failing due to this plugin with the following error
```
Error:<path>/platforms/android/gradlew: Command failed with exit code 1 Error output:
<path>/platforms/android/src/plugin/google/maps/GoogleMaps.java:
479: error: cannot access AbstractSafeParcelable
 options.compassEnabled(controls.getBoolean("compass"));
class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
````

**Comment by masashiGMS** [comment] 2016-12-10 18:19
http://stackoverflow.com/a/38085259

**Comment by Pushplaybang** [comment] 2016-12-10 18:57
duplicate of #1208 

fixed this by forking and installing locally, resetting the play store lib versions to '+' as described in the comments for the above issue.  

Builds on Android, now figuring out Xcode weirdness.

**Comment by anaganisk** [comment] 2016-12-10 19:00
@masashiGMS Thank you for the reply, I've tried that already. @Pushplaybang yes I've noticed that too, but the play store lib version is automatically switching to 9.8.0 even after switching it to '+'.
v1.3.9 doesn't have this issue its happening with v1.4.0

**Comment by anaganisk** [comment] 2016-12-10 19:04
@Pushplaybang changing the line 48&49 in https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml
from
        ```
<framework src="com.google.android.gms:play-services-maps:9.8.0" />
        <framework src="com.google.android.gms:play-services-location:9.8.0" />
```
to 
        ```
<framework src="com.google.android.gms:play-services-maps:+" />
        <framework src="com.google.android.gms:play-services-location:+" />
```
did help

**Comment by Pushplaybang** [comment] 2016-12-21 11:39
@anaganisk  - it's working for me on both android and iOS now.  

Just setting up Circle CI on my project, what error did you run into with the plugin?

**Comment by braianj** [comment] 2016-12-28 20:28
Hi, i'm facing same problem, but it doesn't fix with the 
```
<framework src="com.google.android.gms:play-services-maps:+" />
 <framework src="com.google.android.gms:play-services-location:+" />
```
This is my error
```
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

/XXX/platforms/android/src/plugin/google/maps/PluginUtil.java:135: error: cannot access AbstractSafeParcelable

    Builder builder = LatLngBounds.builder();
                                  ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
1 error

:compileDebugJavaWithJavac 
FAILED



FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':compileDebugJavaWithJavac'.

> 
Compilation failed; see the compiler error output for details.



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED




Total time: 22.331 secs

Error: /XXX/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/XXX/platforms/android/src/plugin/google/maps/PluginUtil.java:135: error: cannot access AbstractSafeParcelable
    Builder builder = LatLngBounds.builder();
                                  ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by anaganisk** [comment] 2016-12-29 03:56
@braianj no it doesn't because when you compile it the values are changed, instead use the v1.3.9 for now. update your config.xml to use v1.3.9

**Comment by braianj** [comment] 2016-12-29 04:49
@anaganisk thanks. Can you tell me how to change the config.xml?

**Comment by anaganisk** [comment] 2016-12-29 04:52
@braianj add this
```
  <plugin name="cordova-plugin-googlemaps" spec="~1.3.9">
    <variable name="API_KEY_FOR_ANDROID" value="AIzXXXXXXXXXXXXXXXXXXXXXXXXXKo"/>
  </plugin>
```

**Comment by killerkarnikel** [comment] 2017-01-15 10:52
for me the reason was changing in platforms\android\project.properties 

from:
cordova.system.library.1=com.google.android.gms:play-services-location:+
to:
cordova.system.library.1=com.google.android.gms:play-services-location:9.8.0

no adding in config.xml, and in plugin.xml was already
        <framework src="com.google.android.gms:play-services-maps:9.8.0" />
        <framework src="com.google.android.gms:play-services-location:9.8.0" />

**Comment by MTRNord** [comment] 2017-03-02 20:06
Any working fix? with ionic Framework the error is still here :(

**Comment by MTRNord** [comment] 2017-03-02 20:09
nevermind a reinstall did the trick :)

**Comment by storaze** [comment] 2017-03-22 15:57
It may occur when the Android SDK Manager is started via $ android and during the upgrade or installation process, the process is stopped with "Ctrl + C" for example, in which case the packages that were being updated should be removed and reinstalled .
How @MTRNord did.

**Comment by totalpave** [comment] 2017-03-22 19:41
I work-around this with using version 9.6.1 instead of 9.8.0. Using + just uses the latest version available, which if it does work, it may break in the future.

I also had to remove the plugin directory from the /plugins directory, and remove the android platform and re-add the android platform.

**Closed** 2017-04-21 16:13 UTC

**Comment by delbekio** [comment] 2017-04-23 17:11
doing what @anaganisk  suggested resolved my issue. but still don't understand why the issue is triggered? given that i have a copy of the project using the same version that is giving compilation error and it builds fine.

the only change is that i added the push notification plugin. can that cause a conflict?
