### ISSUE TITLE
Multiple-maps no working on Android 5

### ISSUE THREAD

**Issue by paulsynth** [mapsplugin/cordova-plugin-googlemaps#2015] opened 2018-01-22 13:51 UTC
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps "https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps"
```

**Current behavior:**
The map is not shown at all.

**Expected behavior:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment] 2018-01-22 15:12
Please share your project files. I confirmed the plugin works on Android version5, or even version4(KitKat)

**Comment by wf9a5m75** [comment] 2018-01-23 02:54
ping

**Comment by wf9a5m75** [comment] 2018-01-23 18:27
ping

**Comment by wf9a5m75** [comment] 2018-01-24 17:20
Since there is no reply at all, I close this thread.

**Closed by wf9a5m75** 2018-01-24 17:20 UTC
Labels: need more information
