### ISSUE TITLE
HTMLInfowView breaks after some time

### ISSUE THREAD

**Issue by tryadelion** [mapsplugin/cordova-plugin-googlemaps#1920] opened 2017-11-27 11:56 UTC
When having a decent quantity of markers ( 50-80), after some time ( i haven't been able to properly replicate it), i get the next error:

> Uncaught TypeError: Cannot read property 'getMap' of undefined
>     at HTMLInfoWindow.calculate (plugins/cordova-plugin-googlemaps/www/HtmlInfoWindow.js:204)
>     at HTMLInfoWindow.trigger (plugins/cordova-plugin-googlemaps/www/BaseClass.js:67)
>     at HTMLInfoWindow.set (plugins/cordova-plugin-googlemaps/www/BaseClass.js:34)
>     at Marker.callback (plugins/cordova-plugin-googlemaps/www/HtmlInfoWindow.js:32)
>     at Marker.trigger (plugins/cordova-plugin-googlemaps/www/BaseClass.js:67)
>     at Marker.set (plugins/cordova-plugin-googlemaps/www/BaseClass.js:34)
>     at Marker.setIcon (plugins/cordova-plugin-googlemaps/www/Marker.js:242)
>     at s (vendor.js:1)
>     at e.<anonymous> (vendor.js:1)
>     at e.value [as setIcon] (vendor.js:1)

As said before,  i haven't been able to replicate, sometimes i go through dozens of markers, sometimes it's when i swipe across the map and pick one, it's not a consistent bug, but rather very random-ish, and i have no idea on how to adress it.
it seems to happen when the infoview loses it's marker, maybe when the map scrolls out of view and the marker is recycled? i have no idea, but the breaking line is:

>  var map = marker.getMap();

Is there any way we could track this error? if i was able to manage the error through a callback, i could re-point to the correct marker.  or pass the MAP reference on the infowindow open. no idea.

In the meanwhile, could we get a if marker == null { console.error("SOME ERROR MESSAGE ABOUT THIS"); return;  } instead right before that line?  it's never good to have the map JS break up, because after that, **_no other markers or infowindows work unless i recreate the map._**

**Comment by wf9a5m75** [comment] 2017-11-27 14:48
As I always says, please share the project files

**Comment by tryadelion** [comment] 2017-11-27 14:51
as i'm unable to enforcibly replicate it, our prior github example with just around a hundred markers will do. 

https://github.com/tryadelion/DemoMaps

The cause is the identified line of code, that tries to get the map of a undefined marker. there should be a check before that line to make sure the marker hasn't "gone south", to prevent the code from breaking.

**Comment by wf9a5m75** [comment] 2017-11-27 15:07
Thank you for sharing the repo, but you said `a decent quantity of markers ( 50-80)`, but the example repo just contains 3 markers.
I'm not interested in your real code at all, but in order to reproduce the issue, please create the same as much as possible.

The `calculate()` function is executed when you open the HtmlInfoWindow.
I guess you do `htmlInfoWindow.open(marker)`, but the `marker` is undefined, or `marker` is removed.

**Comment by tryadelion** [comment] 2017-11-27 15:09
the exact open code in the example is the one shown in the repo, just with more markers. is there any change of that happening with the code in mind?  it comes from the onMarkerClick, so there's not many changes that could happen.

**Comment by wf9a5m75** [comment] 2017-11-27 21:25
Fixed.
![1920](https://user-images.githubusercontent.com/167831/33290058-5cd38d8c-d376-11e7-90be-2b0c61bc2c81.gif)

**Comment by wf9a5m75** [comment] 2017-11-28 15:15
ping

**Comment by tryadelion** [comment] 2017-11-28 15:59
it hasn't happened since the update commit but now, also "intermitently",  so i haven't been able to replicate it, it loses the reference to the marker icons and puts all markers as teh default red marker. Before the update it didn't happen.

**Comment by wf9a5m75** [comment] 2017-11-28 16:32
Please show me the evidence.

**Comment by tryadelion** [comment] 2017-11-28 16:35
give me 24h, i just finished my work day.

**Comment by wf9a5m75** [comment] 2017-11-28 17:06
ok

**Comment by wf9a5m75** [comment] 2017-11-29 00:32
By the way, here is an example to display custom html tags in HtmlInfoWindow.
Just for your information ;)

```TypeScript
import { Component, ComponentRef, Injector, ApplicationRef, ComponentFactoryResolver, NgZone, ElementRef, ViewChild } from '@angular/core';
import { Platform } from 'ionic-angular';
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  GoogleMapOptions,
  BaseArrayClass,
  MarkerOptions,
  Marker,
  HtmlInfoWindow
} from '@ionic-native/google-maps';

@Component({
  selector: 'custom-tag',
  template: `
    <div style="white-space: nowrap;">markerTitle: {{myTitle}}</div>
    <button ion-button (click)="onButton_click($event)">hi</button>
  `,
})
export class CustomTag {
  myTitle: string;

  onButton_click(event) {
    alert(`This is '${this.myTitle}'`);
  }
}

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  map: GoogleMap;
  htmInfoWindow: HtmlInfoWindow;

  constructor(
    public platform: Platform,
    private injector: Injector,
    private resolver: ComponentFactoryResolver,
    private appRef: ApplicationRef,
    private _ngZone: NgZone
  ) { }


  ionViewDidLoad() {
    this.platform.ready().then(() => {
      this.loadMap();
    });
  }

  onMarkerClick(params: any[]) {
    // Get a marker instance from the passed parameters
    let marker: Marker = params.pop();

    // Create a component
    const compFactory = this.resolver.resolveComponentFactory(CustomTag);
    let compRef: ComponentRef<CustomTag> = compFactory.create(this.injector);
    compRef.instance.myTitle = marker.get("myTitle");
    this.appRef.attachView(compRef.hostView);

    let div = document.createElement('div');
    div.appendChild(compRef.location.nativeElement);

    // Dynamic rendering
    this._ngZone.run(() => {
      this.htmInfoWindow.setContent(div);
      this.htmInfoWindow.open(marker);
    });

    // Destroy the component when the htmlInfoWindow is closed.
    this.htmInfoWindow.one(GoogleMapsEvent.INFO_CLOSE).then(() => {
      compRef.destroy();
    });
  }

  loadMap() {
    let locations: MarkerOptions[] = [
      {"myTitle": "one", disableAutoPan: true, position: {lat: 41.624615, lng: 0.6238626}},
      {"myTitle": "two", disableAutoPan: true, position: {lat: 41.624615, lng: 0.6248626}},
      {"myTitle": "three", disableAutoPan: true, position: {lat: 41.624615, lng: 0.6258626}}
    ];

    let mapOptions: GoogleMapOptions = {
      camera: {
        target: [
          {lat: 41.624615, lng: 0.6238626},
          {lat: 41.624615, lng: 0.6248626},
          {lat: 41.624615, lng: 0.6258626}
        ],
        padding: 60
      }
    };

    this.map = GoogleMaps.create('map_canvas', mapOptions);
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        this.htmInfoWindow =  new HtmlInfoWindow();

        let mvcArray: BaseArrayClass<MarkerOptions> = new BaseArrayClass<MarkerOptions>(locations);
        mvcArray.mapAsync((markerOpts: MarkerOptions, next: (marker: Marker) => void) => {
          this.map.addMarker(markerOpts).then(next);
        }).then((markers: Marker[]) => {
          markers.forEach((marker: Marker) => {
            marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe((parmas: any[]) => {
              this.onMarkerClick(parmas);
            });
          });
        });

      });
  }
}
```

![htmlinfowindow](https://user-images.githubusercontent.com/167831/33351658-b50ffeb6-d459-11e7-9513-91024a1e4dc1.gif)

**Comment by tryadelion** [comment] 2017-11-29 07:20
using directly HTML on the setContent seems to work, is there any positive outcome of the component creation + destruction? 

I also noticed that if you leave the map open too much time idle ( 1m-2m), without doing nothing,  and then you try to perform an action  ( open marker, open side menu to chance view), the app hangs and then breaks "this application has stopped" or responds after a lot of time waiting. will open a new ticket soon.

**Comment by tryadelion** [comment] 2017-11-29 07:32
currently trying to replicate the marker icon dissapearance issue.

**Comment by tryadelion** [comment] 2017-11-29 07:47
both issues might be related to this crash just happened:
```

11-24 13:51:53.597 14317-14317/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.tryadelion.mapsapp, PID: 14317
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                       at plugin.google.maps.PluginMarker._removeMarker(PluginMarker.java:833)
                                                       at plugin.google.maps.PluginMarkerCluster$2.run(PluginMarkerCluster.java:117)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by wf9a5m75** [comment] 2017-11-29 07:54
Please create a demo project that reproduce 100% issue.
You only share a demo project with dummy code, but it is not reproduce the issue.

**Comment by tryadelion** [comment] 2017-11-29 08:00
the android profiler doesn't show any special memory related problem, the "power consumption" of the map activity seems to be stable at 119mb - 200mb.


i will ask our tech lead if we can share with you part of the main project, i'll probably get a response on the afternoon, thanks for all the support you're providing!.

![captura de pantalla 2017-11-29 a las 8 53 37](https://user-images.githubusercontent.com/3778474/33363988-d1c34930-d4e2-11e7-8f0e-ce00cfbaccc2.png)

**Comment by wf9a5m75** [comment] 2017-11-29 14:55
Google Maps API itself sepnds lots of memory, and this plugin also uses memory.
Also ionic is heavy.
So it's depends on your code.

This plugin saves the memory usage as much as possible.
Remember, you use hybrid framework. Browser view, native code,  JavaScript code... everything use memory than pure native code.
If you still feel this plugin is heavy, you need to find the code of problem by yourself, or find another plugins. Or create your app with full native code.

**Comment by tryadelion** [comment] 2017-11-29 14:57
I haven't been able to fully find a way to reproduce 100% the issue. i'll try to build a clean repo tomorrow morning with one of our demo APIs and a new ionic blank project.

**Comment by tryadelion** [comment] 2017-11-30 08:20
https://github.com/tryadelion/DEMOMANYMARKERS

 i have created this project. on first install, leave it open or in background some time, after that, try to switch to List,  it will lag the hell out of the app ( Pixel XL, BQ X, BQ U, HUAWEI P8L), hang completely ( BQ M, BQ U, SAMSUNG CG2) or even force close ( happened in two samsungs). if it doesn't happen at first, try switching between the windows and try again, i've reproduced it 3-4 times.   

the marker dissapearance bug hasn't happened yet.

**Comment by wf9a5m75** [comment] 2017-11-30 15:29
Thank you.
 I saw your code. There are couple of mistakes.
But I'm so busy today. Maybe I will test it tomorrow.

**Comment by wf9a5m75** [comment] 2017-11-30 16:18
By the way, did you test the project **without** yhe geolocation plugin?
Because you doubt the maps plugin, you should only test the maps plugin without other plugins.

**Comment by tryadelion** [comment] 2017-11-30 16:21
I need it to get accurate location of the user outside of the maps scope for many things, it shouldn't be incompatible.

**Comment by wf9a5m75** [comment] 2017-11-30 17:08
You can. You just record the locations and store it into array (Use your brain).

```
var locations = [
  {lat: ..., lng: ...},
  {lat: ..., lng: ...},
  ...

  {lat: ..., lng: ...}
];

function getCurrentPosition(callback) {
  callback(locations[i++]);
}
```

**Comment by wf9a5m75** [comment] 2017-11-30 21:17
Regarding of your code, you **always** need to recognize that **you use native features, not only HTML element**.

At the `ionViewWillLeave`, you do like this (very bad code):
```
  ionViewWillLeave() {
    if (this.MarkerCluster != null) {
      this.MarkerCluster = null;
    }
    if (this.map != undefined) {
      this.map.setVisible(false);
    }
  }
```

Because you believe `this.MarkerCluster = null` releases all memory.
But as I described, this is just loose the reference to the marker cluster.

If you want to remove the marker cluster, you **have to ** do this:
```
this.MarkerCluster.remove();
```

-----

Also, `this.map.setVisible(false);` is none-sense.
This plugin removes the map automatically if the map div is removed.

And `this.map` starts with `null` always when you enter to the page, because you defined in the HomePage class.

If you want to hold the map instance, you need to create a provider.

**Comment by tryadelion** [comment] 2017-11-30 21:23
ok, so i'll just leave the map as it is without setVisible, i thougth you were keeping the map in behind as per an old incidence i read. as for the markercluster.remove, sometimes it  threw errors about "cannot find method remove on undefined",  that's why i switched to a quite bad code.
 is the marketcluster = null the cause of the issues? it would be quite silly,  but i can manage the random "remove on undefined" errors on a try catch and go back to that method. should i force map.remove too?

**Comment by wf9a5m75** [comment] 2017-11-30 21:25
Actually you don't need to do anything when you leave the page.
The maps plugin removes the map and related overlays automatically when the map div is removed.

**Comment by tryadelion** [comment] 2017-11-30 21:28
good to know.  bad habits from worse memory - managed libraries arise easily.

**Comment by wf9a5m75** [comment] 2017-11-30 21:36
And one more thing.

You use `ionViewDidEnter` for creating a map, but this event occurs when you select the map page on the side menu even if you are in the map page.

In order to prevent, you should use `ionViewDidLoad`
```
  ionViewDidLoad() {
    this.platform.ready().then(() => {
      this.loadMap();
    });
  }
```

**Comment by tryadelion** [comment] 2017-11-30 21:38
don't worry about that, on the real app the page change only occurs when different pages are selected, same page click does nothing. sorry for failing to do it in this demo.

**Comment by tryadelion** [comment] 2017-12-04 08:50
did you manage to find the reason of the lag?

**Comment by wf9a5m75** [comment] 2017-12-04 15:13
Unfortunately, I didn't reproduce this at all

**Comment by wf9a5m75** [comment] 2017-12-07 01:25
I updated the code for another issue, but it might help your problem. Please reinstall the plugin from the multiple_maps branch.

**Comment by wf9a5m75** [comment] 2017-12-07 17:26
ping

**Comment by wf9a5m75** [comment] 2017-12-08 08:17
This is the screen record on Nexus 5x (2012, Android 5.1.1)
![1920_compress](https://user-images.githubusercontent.com/167831/33757014-1490481e-dbad-11e7-8085-e6d534c4073a.gif)

**Comment by tryadelion** [comment] 2018-02-22 09:47
@wf9a5m75  i have been reproducing the app crash / slowdown issue on a complete separate project, plugin branch master, version 2.2.5, should we  reopen this or should i open a new one?

**Comment by tryadelion** [comment] 2018-02-22 10:06
this is the ram spike a micro hang caused.  0% cpu usage.

it is a minor memory "hog",  and the lib runs incredibly smoothly since we last talked, but i really can't find a way to fix this issue.
the flow is:

 " long time idle on map (leaving phone open, keep coding)" -> "perform action (click marker, click buttons, click tab icon to open menu)" -> "application hangs unresponsibly for 1-6 seconds ( depends on how many time the app has been idle, by personal experience)" -> "app perform actions ordered OR app crashes without exception thrown on logcat" 

![captura de pantalla 2018-02-22 a las 10 57 24](https://user-images.githubusercontent.com/3778474/36531765-33417442-17bf-11e8-9b32-d2729b86de19.png)
![captura de pantalla 2018-02-22 a las 10 57 17](https://user-images.githubusercontent.com/3778474/36531766-335a8572-17bf-11e8-9b03-6b8c60e177b6.png)

**Comment by tryadelion** [comment] 2018-02-22 10:26
after performing a profiling, these are the thread time performance profilings of the active CPU executions during the hang, each one has been screenshotted with it's thread name:

![captura de pantalla 2018-02-22 a las 11 25 09](https://user-images.githubusercontent.com/3778474/36533211-26104010-17c3-11e8-8625-53015b67ec11.png)
![captura de pantalla 2018-02-22 a las 11 24 57](https://user-images.githubusercontent.com/3778474/36533212-275aae6a-17c3-11e8-9dff-e89443644de2.png)
![captura de pantalla 2018-02-22 a las 11 24 49](https://user-images.githubusercontent.com/3778474/36533215-286121f4-17c3-11e8-8329-683fd37aed44.png)

**Comment by tryadelion** [comment] 2018-02-22 11:05
the average reproduction time is 4 minutes to face the issue at small scale. the longest so far was:
1m 12s of app hang, after 30min of screen idleing, same methods as showcased caused the hang.

the ram usage during the hang rose only  a mere 20mb and there is no GPU  impact either.

**Comment by wf9a5m75** [comment] 2018-02-22 17:18
Do you test on the same project?
https://github.com/tryadelion/DemoMaps

**Comment by tryadelion** [comment] 2018-02-23 07:17
@wf9a5m75  no, i will push it later today, do some small testing, and ping to you when updated.

**Comment by tryadelion** [comment] 2018-02-23 08:00
still, have you been able to reproduce it with any project on the master branch? it has happened me twice already on two completely unrelated, code wise, projects so far.

**Comment by tryadelion** [comment] 2018-02-23 08:32
thank you very much. the video i attached previosuly you was made during hte first profiling, will try to record a new one in the test project.

**Comment by tryadelion** [comment] 2018-02-23 09:36
after 15,04 minutes under the multiple maps branch i was able to reproduce  the issue on the demo, i've updated the demo repo. it took so long to reproduce because the memory and cpu load on this demo is 50/75% the one in the real app ( the demo just shows markers, has no side menu, has no landing tutorial, assets are smaller, there's no other plugins that add resource spending, etc).  to reproduce just zoom out until you have some big number of markers or clusters ( same icon for both used on this demo).

**Comment by tryadelion** [comment] 2018-02-23 09:41
![captura de pantalla 2018-02-23 a las 10 38 42](https://user-images.githubusercontent.com/3778474/36587539-c4a327fc-1885-11e8-9621-b0fa1c1d71c2.png)


minute 5, 2 seconds, took 600ms to respond to a user click on the "button to click" action and caused a small cpu spike. almost unnoticeable at this rate but it gets worse as time passes and when the data load is bigger ( the data subset i added is half the real one).

https://www.youtube.com/watch?v=q2OAVaTJVMM

**Comment by wf9a5m75** [comment] 2018-02-23 17:10
I think it's just too much marker.

**Comment by wf9a5m75** [comment] 2018-02-23 18:20
I will try to reproduce your issue anyway. Hold on please.

**Comment by wf9a5m75** [comment] 2018-02-27 01:52
I tried, but I could not understand what your point is.
I don't feel any time rag when I tap on the test button after 7 minutes.

And this plugin handles all touches even on HTML, the plugin uses cpu when you touch on app.
This is not a bug.

**Comment by tryadelion** [comment] 2018-02-27 07:19
when i tap on the test button, clean install on this repo, on a physical device, after 4 minutes, there's atleast ~1s, sometimes way more,  of full idle time where nothing ( drag, click, scroll, pan, click buttons) work, the app is "hanged". maybe  something is clogging the touch events and stopping it's propagation? i have no clue on what this (or other plugins) do on their behind.

**Comment by tryadelion** [comment] 2018-02-27 07:48
okay, a user reproduced the same issue and sent an ANR report:


Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 26. Wait queue head age: 6065.3ms.)

> "main" prio=5 tid=1 Runnable
>   | group="main" sCount=0 dsCount=0 obj=0x73d3c268 self=0xaa704400
>   | sysTid=22300 nice=-4 cgrp=default sched=0/0 handle=0xad3ea534
>   | state=R schedstat=( 13010426329 1331263425 6776 ) utm=1196 stm=105 core=3 HZ=100
>   | stack=0xbe1a4000-0xbe1a6000 stackSize=8MB
>   | held mutexes= "mutator lock"(shared held)
>   at java.util.HashMap.removeEntryForKey (HashMap.java:602)
>   at java.util.HashMap.remove (HashMap.java:584)
>   at java.util.HashSet.remove (HashSet.java:233)
>   at plugin.google.maps.ObjectCache.remove (ObjectCache.java:21)
>   at plugin.google.maps.PluginMarker$15.onPostExecute (PluginMarker.java:1104)
> - locked <0x0d07162d> (a com.google.android.gms.maps.model.Marker)
>   at plugin.google.maps.AsyncLoadImage.onPostExecute (AsyncLoadImage.java:548)
>   at plugin.google.maps.AsyncLoadImage.onPostExecute (AsyncLoadImage.java:27)
>   at android.os.AsyncTask.finish (AsyncTask.java:667)
>   at android.os.AsyncTask.-wrap1 (AsyncTask.java)
>   at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:684)
>   at android.os.Handler.dispatchMessage (Handler.java:102)
>   at android.os.Looper.loop (Looper.java:154)
>   at android.app.ActivityThread.main (ActivityThread.java:6119)
>   at java.lang.reflect.Method.invoke! (Native method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)

**Comment by wf9a5m75** [comment] 2018-02-27 10:58
What version?

**Comment by tryadelion** [comment] 2018-02-27 11:07
tha latest  one as appears in the repo. 2.2.5  i presume. android 6.0.1, 4GB ram, 640 series snapdragon cpu  device.

**Comment by wf9a5m75** [comment] 2018-02-27 11:11
Please create a demo project that reproduce the issue 100%.

**Comment by wf9a5m75** [comment] 2018-03-05 00:56
ping

**Comment by wf9a5m75** [comment] 2018-03-06 01:58
I have couple of Android devices from older one to new one.
However I would like to ask you one thing.
Do you want to create an application that is depends on device power?

At least, I tested on Android 4.4.4 (MOTO G), and no problem.

**Comment by wf9a5m75** [comment] 2018-03-08 17:10
Since there is no enough data is provided, I close this thread.

**Closed by wf9a5m75** 2018-03-08 17:10 UTC
Labels: bug, fixed, pending / waiting
