### ISSUE TITLE
iPhone X: incorrect touch handling with cordova-plugin-statusbar

### ISSUE THREAD

**Issue by goodsoft** [mapsplugin/cordova-plugin-googlemaps#1874] opened 2017-11-11 19:46 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-statusbar 2.3.0 "StatusBar"
```

**Current behavior:**
When running on iPhone X simulator, map is displayed correctly, but touches are handled as if map was located 20pt higher.
That is, map plugin intercepts touches on elements just ahead of map, but doesn't react to touches on the lower 20pt strip of itself.

**Expected behavior:**
Touches should be handled correctly.

**Related code, data or error log (please format your code or data):**
Apparently, this part in `src/ios/GoogleMaps/MyPluginLayer.m` has hardcoded statusbar height:
```
    if (hasCordovaStatusBar) {
        UIApplication* app = [UIApplication sharedApplication];
        if (app.isStatusBarHidden) {
            point.y -= 20 * zoomScale;
        }
    }
```

Though, the behaviour of cordova-plugin-statusbar changed in these commits:
https://github.com/apache/cordova-plugin-statusbar/commit/fff289c0b8a7d0eb5b94f06d8ace9733054185bd
https://github.com/apache/cordova-plugin-statusbar/commit/cdc9295b30b013425f4906670e16b50461aeca8d
https://github.com/apache/cordova-plugin-statusbar/commit/c45331b95555c5c77b4ed4ca690236a9b077ec4b

**Comment by wf9a5m75** [comment] 2017-11-12 01:55
Please create a demo project, and share it.
And please take a screen shot.
I have no plan to buy iPhoneX. So without cooperation with yours, this issue is not able to resolved.

**Comment by goodsoft** [comment] 2017-11-12 02:08
I don't have physical iPhone X too, but this bug can be reproduced in simulator, which is bundled with latest Xcode.
I'll create a demo project and make relevant screenshots as soon as I deal with stuff of higher priority.

In the meanwhile it's possible that someone of higher acquaintance with the code of this plugin might figure out what needs to be changed to make it work.

**Comment by wf9a5m75** [comment] 2017-11-14 19:29
Since you don't give me any example, any screen captures, I'm not sure this commit is fixed as you want.
But the hack code should not be required anymore, because of https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1875.
Please reinstall the plugin from the `multiple_maps` branch, and let me know the result.

**Comment by wf9a5m75** [comment] 2017-11-15 23:40
ping

**Comment by goodsoft** [comment] 2017-11-15 23:43
The bug is still there.
I'm trying to create a demo app to isolate this bug, but I'm not used to plain Cordova (we use rather convoluted build system), so it will take some time.

**Comment by wf9a5m75** [comment] 2017-11-16 00:22
Well, ionic is fine. Other frameworks are fine. 
And at least you can take screen record how the plugin does not work.

**Comment by wf9a5m75** [comment] 2017-11-20 17:12
ping

**Comment by wf9a5m75** [comment] 2017-11-21 17:22
Since there is no enough information, I close this thread.

**Comment by shrijan** [comment] 2017-11-22 03:52
```
     com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
     cordova-plugin-googlemaps 2.1.2-beta-20171120-1931 "cordova-plugin-googlemaps"
     cordova-plugin-statusbar 2.3.0 "StatusBar"
```
[https://youtu.be/sakHY2Dycwg](https://youtu.be/sakHY2Dycwg)

Map loads fine but overlay button when tapped doesn't react but zooms the map. This happens only after cordova-plugin-statusbar installed.

**Comment by wf9a5m75** [comment] 2017-11-22 04:02
Could you share the project files in a git repository (bitbucket provides free private repo)

**Comment by wf9a5m75** [comment] 2017-11-22 06:41
If you share the project files on GitHub, I will check it tomorrow. Otherwise, I will do next week.
From tomorrow, I will take US holidays in this week

**Comment by shrijan** [comment] 2017-11-22 22:55
https://bitbucket.org/piyashrija/googlemapcordova Thanks

On Wed, Nov 22, 2017 at 5:41 PM, Masashi Katsumata <notifications@github.com

**Comment by wf9a5m75** [comment] 2017-11-22 23:40
Well, it's kind of too late.

**Comment by wf9a5m75** [comment] 2017-11-22 23:40
But I will try to find a free time.

**Comment by shrijan** [comment] 2017-11-22 23:43
Sorry Masashi, was busy yesterday.

Thanks for your time.

**Comment by shrijan** [comment] 2017-11-27 03:42
ping

**Comment by wf9a5m75** [comment] 2017-11-27 21:45
I can't understand what the problem is.
![screen shot 2017-11-27 at 1 45 02 pm](https://user-images.githubusercontent.com/167831/33290969-3db5e2d0-d379-11e7-837a-07434cdbce58.png)

**Comment by shrijan** [comment] 2017-11-27 22:43
Problem is when you click the button on the map it will zoom map instead of
action from button like I have alert text on button click.

I think this is due to
<preference name="StatusBarOverlaysWebView" value="false" />
if remove works but will have layout problem with iphonex

Thanks


On Tue, Nov 28, 2017 at 8:45 AM, Masashi Katsumata <notifications@github.com

**Comment by wf9a5m75** [comment] 2017-11-28 03:29
@shrijan Try the multiple_maps branch.

**Comment by wf9a5m75** [comment] 2017-11-28 06:00
![1874](https://user-images.githubusercontent.com/167831/33304541-56a1a136-d3be-11e7-928c-12e4b639b05c.gif)

**Closed by wf9a5m75** 2017-11-28 06:00 UTC
Labels: bug, fixed

**Comment by shrijan** [comment] 2017-11-28 06:07
Thank you

On Tue, Nov 28, 2017 at 5:00 PM, Masashi Katsumata <notifications@github.com
