### ISSUE TITLE
White screen in Android in presense of jquery.mobile-1.4.5.min.css

### ISSUE THREAD

**Issue by Vishaliphone** [mapsplugin/cordova-plugin-googlemaps#1843] opened 2017-10-27 13:40 UTC
Hi,
I am using this plugin till around year.
It was working fine in Android, But suddenly it shows whites screen in 
<img src="https://user-images.githubusercontent.com/6514316/32106195-96aaae82-bb48-11e7-86e4-f1cc4b1b31a2.jpg" width="250">

However i check that :

```js
map = plugin.google.maps.Map.getMap(document.getElementById("map_canvas"));
map.addEventListener(plugin.google.maps.event.MAP_READY, function() {});
```

This call Back function is called successfully.

When i remove **jquery.mobile-1.4.5.min.css** from HTML file,
Everything is working fine.

So, Presence of  "jquery.mobile-1.4.5.min.css" is making issue here.
Please Guide me if any of you are come across with same behavior.

**NOTE : Everything was working fine before.**

**Comment by wf9a5m75** [comment] 2017-10-27 14:13
Make sure the css.
This plugin puts the native map view **under the browser**.
So you must set be transparent of all html elements of over the map div.


https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work

**Comment by Vishaliphone** [comment] 2017-10-30 05:23
But why It was working previously?
If you need more information then specify what you need to knew,

**Comment by wf9a5m75** [comment] 2017-10-30 05:27
I don't know. You don't share your project files with me, I can not give any help further.
If you want me to check you project, please share your project files on github. Then I will check it.

**Comment by Vishaliphone** [comment] 2017-10-30 06:14
Actually It's client Project.
I can't put it public.
Please share your gmail ID 
so i can give you access to review code files.

**Comment by wf9a5m75** [comment] 2017-10-30 06:37
https://github.com/wf9a5m75

**Comment by Vishaliphone** [comment] 2017-10-30 06:46
You can review files now.
I did give access for your mail id.
Please review it & help me regarding this,
So we can help others who are facing same issue.

**Comment by wf9a5m75** [comment] 2017-10-30 06:49
Thank you for inviting, but could you put your code onto BitBucket instead of Google Drive?
You can create free private git repository.

**Comment by Vishaliphone** [comment] 2017-10-30 06:50
Dear,
I added only 2 files on Drive,
HTML file & JS file.

**Comment by wf9a5m75** [comment] 2017-10-30 06:51
No please include all files in order to build your project file.
Please save my time. I'm so busy person.

**Comment by wf9a5m75** [comment] 2017-10-30 13:48
ping

**Comment by wf9a5m75** [comment] 2017-10-30 18:25
Since you don't share all files with me, I needed to spend time for you.
And there are missing files, I can not build your project.
So I can not reproduce your issue.

![screen shot 2017-10-30 at 11 22 13 am](https://user-images.githubusercontent.com/167831/32188283-9b7e8596-bd64-11e7-90d7-98d411e5ac9f.png)

If you share your project files on git repository, I will help you. At least you can create a demo project.
If you don't want to share anything, please close this thread.

**Closed** 2017-10-31 10:19 UTC
Labels: need more information, not bug, pending / waiting

**Comment by Vishaliphone** [comment] 2017-10-31 10:23
It's related to my custom CSS conflicted with Jquery CSS.
Thanks for your support !
