### ISSUE TITLE
Map is not clickable after setClickable(true) and overflow div close

### ISSUE THREAD

**Issue by Symorp** [mapsplugin/cordova-plugin-googlemaps#1541] opened 2017-07-10 09:37 UTC
Hello,
I use Framework7 with google maps,
everything works until i go from list view to another page.
Page is a new div. Previous page with map is on same place, just hide.
After navigation back - map stop working no clickable even i setClickable(true).
If i open same div after click on marker everything is working, but from my custom div its the problem.
I am using remote debugging in chrome so i try: destroy, getMap, refresh layout, setClickable, everything but map is still not clickable.
I tried delete all and leave just map div and nothing.

<img src="https://user-images.githubusercontent.com/16707031/28011842-07fbf0cc-6564-11e7-8cf7-6ce65ae8808b.gif" width="250">

**Comment by Symorp** [comment] 2017-07-10 09:40
Repository name is C4WMobile

**Comment by wf9a5m75** [comment] 2017-07-10 14:20
OK, I will check it.

**Comment by wf9a5m75** [comment] 2017-07-10 17:26
Hi, I think the login user/pw are different you gave me before (promo). I can not reproduce with your same page.

**Comment by Symorp** [comment] 2017-07-11 06:07
Hi, you can use promo, just instead of click on name u can click on "Jet" and you will see markers.

**Comment by wf9a5m75** [comment] 2017-07-11 22:46
If I build your project, your app is like this.
![1541](https://user-images.githubusercontent.com/167831/28094170-fdcda9fa-664f-11e7-99c6-50bff13dd373.gif)

**Comment by wf9a5m75** [comment] 2017-07-11 22:58
Ah, I see. I might figure out the issue. Let me confirm couple of things.

When you go back to the map page from the car details page, did you tap the `back button` of the Android?

And when the map does not work, what happen if you tap on the map at once?
I think the map would work.

**Comment by Symorp** [comment] 2017-07-12 06:12
So we tried Android back button and map was still not working. And one tap at Map don work too.

But you can try something. When we add an delay before animation of car detail page (like 3000ms) and when we clicked on car in car list the map was shown and waiting 3000ms for animation and load of car detail page map wasn't clickable too. So there must be something what happend which is making this fail. And some times map is working (In lot of times map work after first going to car detail and back to map, when we tried it again the issue was happen, but some times it did first time when we click on car at car list).

**Comment by wf9a5m75** [comment] 2017-07-12 06:19
I committed some code to the multiple_maps plugin.
Please retry to install the latest version.

**Comment by Symorp** [comment] 2017-07-12 06:22
Okay we will try.

**Comment by Symorp** [comment] 2017-07-12 08:34
So we tried new version. 
**Android** 

- In whole App don't work back button
- But the map work after going back from car detail

**iOS**
- In iOS still map don't work after second or first try. So we commited new version on bitbucket
You can try it (on page with map):
- click on "Zobrazit vozy"
- click on "Zobrazit mapu"
- **map is still working**
and then:
- click on marker
- go back from car detail to map
- **map is still working**
and then:
- click on "Zobrazit vozy"
- click on "Zobrazit mapu"
- **map is not working**

For the map effect we use css height: 0; with transition duration.

**Comment by wf9a5m75** [comment] 2017-07-12 14:14
Could you update the source code? I could not reproduce your app from building your source code.

**Comment by Symorp** [comment] 2017-07-13 05:54
We pushed it to bitbucket again so you can try it.

**Comment by wf9a5m75** [comment] 2017-07-13 21:07
Ok, I checked the code of Cordova Android.
They allows register only one event listener for the backbutton event.

I commented out the line.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/06d4fc78c2117289ff7f5eda429d6cc6d41c06d2

**Comment by wf9a5m75** [comment] 2017-07-13 23:06
Ok, I fixed of Android behavior at least.

![1541_android](https://user-images.githubusercontent.com/167831/28191413-041e7118-67e5-11e7-85cf-0924f043628c.gif)


In order to work correctly, you need to reinstall the latest plugin (version `2.0.0-beta2-20170713-1545` or higher)

**Comment by wf9a5m75** [comment] 2017-07-14 02:13
iOS is still inspecting.

**Comment by wf9a5m75** [comment] 2017-07-14 07:59
I finally figured out the reason. The DOM tree depth calculation was not perfect.
I rewrote the code, and improved calculation performance also.

In order to work correctly, you need to reinstall the latest plugin (version `2.0.0-beta2-20170714-0030` or higher)
I recommend reinstall Android and iOS both.

![1541_ios](https://user-images.githubusercontent.com/167831/28203307-fcc1a270-682d-11e7-842f-e1a45e65b757.gif)

**Comment by wf9a5m75** [comment] 2017-07-15 22:40
ping

**Comment by Symorp** [comment] 2017-07-15 22:52
Oh thank you for response. We Will ty new version at Monday

**Comment by wf9a5m75** [comment] 2017-07-15 23:15
ok

**Comment by Symorp** [comment] 2017-07-17 08:54
We installed new version, tried on iOS and Android and its working correct on both. 
So very big thank you man.
We will donate you if you tell us where.

**Comment by wf9a5m75** [comment] 2017-07-17 13:52
Sounds good.

And thank you for offering donation.
You can do it from here

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Closed by wf9a5m75** 2017-07-17 13:52 UTC

**Comment by amirul1000** [comment] 2018-01-16 12:34
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/class/Map/setClickable
