### ISSUE TITLE
EXC_BAD_ACCESS on Marker.m

### ISSUE THREAD

**Issue by PapyElGringo** [mapsplugin/cordova-plugin-googlemaps#914] opened 2016-03-29 17:05 UTC
I've got an EXC_BAD_ACCESS (code=1,address=0xc) on line 627 of Marker.m

seem to be the commit #807 who break.

**Comment by wf9a5m75** [comment] 2016-03-29 17:08
This line?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/10b13c0265224c50f2694911d30c1dfdcea45a4c/src/ios/GoogleMaps/Marker.m#L627

**Comment by PapyElGringo** [comment] 2016-03-30 09:38
Yep

**Comment by wf9a5m75** [comment] 2016-03-30 13:17
Could you show.me example code and more error log?

**Comment by wf9a5m75** [comment] 2016-03-30 15:08
Without error logs and example code, we can not confirm your issue. In that case, we close this issue.

**Comment by PapyElGringo** [comment] 2016-03-31 08:43
I'll try to put something when i'll have the time

**Comment by wf9a5m75** [comment] 2016-03-31 16:03
I close this issue at once, because no enough information at this time.
If you face the same error again, please reopen this issue with error logs and example code.

**Comment by PapyElGringo** [comment] 2016-04-14 08:56
Still got this error 

log:

*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]

**Comment by wf9a5m75** [comment] 2016-04-14 23:58
Which version do you use? Did you install the plugin from NPM or the master branch?

**Comment by wf9a5m75** [comment] 2016-04-14 23:59
The error says you didn't pass the correct arguments.

**Comment by PapyElGringo** [comment] 2016-04-15 13:23
The error occur when I try to user an local url path for icon Image or if i try to use a base64 image like

map.addMarker(position:lngLatPosition, icon: "img/marker.png"}

Only on iOS ( cordova iOs 4.1.1) version 8

**Comment by PapyElGringo** [comment] 2016-04-15 13:25
I also tryed with {url : "img/marker.png"}

and convert my png or svg with a canvas and get the dataUrl

**Comment by PapyElGringo** [comment] 2016-04-15 13:25
And i tryed from the master branch and optimization branch

**Comment by wf9a5m75** [comment] 2016-04-15 14:02
Don't use the optimazation branch yet.

**Comment by PapyElGringo** [comment] 2016-04-15 16:02
I have the same problem with the actual master version!

With this simple code 

      ionic.Platform.ready(function () {
        var mapDiv = document.getElementById("map");

        // Initialize the map plugin
        var map = plugin.google.maps.Map.getMap(mapDiv);

        // You have to wait the MAP_READY event.
        map.on(plugin.google.maps.event.MAP_READY, onMapInit);
      
    });

    function onMapInit(map) {
      console.log(map)
      for (var i = 0; i < 600; i++) {
        map.addMarker({
          'position': new plugin.google.maps.LatLng(Math.random() * 40, Math.random() * 40),
          'icon': {
            url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABOtJREFUeNrkV81rXUUUPzP3vveSvEBS41P8bohSqC6iKbiooLhxpWSrO8E/oCtFLbhyIbQYUEFx4cY/oN246qJ140KFSAWtoJuAUoWatMnLzf2Y4zlnPu5M733ZduENk5k3M3fOb875nd/MVYgI9/LRcI+f3DeUUnD29c+XAHELATepaxnEO2gr8G3nMT8Wt/28njF6dundS1Sf++Hyu3t+HeUbL7zxBRu/OjfK19ceX4H5uYGDRgsZEMOGi0FojAl1w3Vj2uJ+11Eft+u6guJwSms127TaS99ffm8v8QDvnI2f3TgJw0FOHrFe8SDIFpXUYF3bxatQN9LHNZeS+6sGFLWV1lQyONzfWzdotmjRNxMOsNuffOJ+GA1zyLSCPNNSBrmGYZ5Rf0bAbOG+nPoyqjOak+VK3uGiuTjwqt0dtVE2lQ9GvNnNDgc45gvzA3lZu4V4QVnIrWQrcj8Z1RQXHjdU9nYLuHNQgvEh4BA1LkQNc8MIAA6jW2u5C4AGV5YXxIx3f1ssBxiBCkAA9qclXP/tJry48RCcOb0qbtaKwbO72RNa+j747FsYZExOAkJ9cepHHkBH1qRHgPF8Jp0QzxGRF/n1j3/g/bc2YO2xE7C4uAij0SiA7iyEPoNCVqQAEP08biiphf3QZgC70wO5vV/A+qkVMT6ZTGA4HMrOE7sC1rgUNeIBxHSjOoYpRjnKDq0YNT6l2phy/fetA3L7gzAej8V4nucCIC5ZlgVQ6D0gNmaEgA0qgwl77Tso5AppaKx3xgtDcTsb8s83127AR19eExJ7o8p5wG7QzAqB27WxTMXGsg1NLEAOhMt5TzjLbgv706+/gwfum6c5pAVVTfOoVFYfbBjSEMRpCDt/3ZZdLczllOs25zExjkGIGNQzT03EcBz7o7KC8bwWoNZjHEIG0EhtTNPvAUZWElJD5JoeanEh/3lNkPSjf00AgTbd7mI8j+1PC1HAsqrEU6apBUwIw6w0ZLScpyI2xqYT1hhemhaVFH6/OKoC2RIABOywMC5btEWtOaRHgYT9HACb64SX5iiJb5vCFsDBtILNl9dg9dElEZk+D1x4+xWrmk6Uft+5BR9/dTXEX+q+45gHWUpZAwyqoOWWMxjIeGp1As89/YgwnwunX/w8v37S5b5V059u3KTdV60QBS/0hKAmI5oV12WCkgRKj2I2GOd97y0n6t/+5U8KS+nibuxmZimhEMUJvkpUFJ0WGKvxPbGf9fz4845zu1dBMysNLbNlVMXHgxMjY+t3Ll6x4aL2J+dfhWdPP5wYpFsVXzoC0Zr6KHE/ziIhuB3GZxJiq4TGvUjyIGBY0Mqy7OyYjVdHdxLSJQQ8VoqN3ZlHKmHBNg3lRZfPTFS5HdDvNBx4l3GM2O+kuC8E6ESkleR254jdRZU763ufaL6cgNGF9tgQeNkVowaT3UNQMXusgrZa0Tn7/ZEe+I7RMWw6aZgcx1VVth6IXR8Zx6hf9QhRSLfIYELA4JHuh8kun2DGhjmQL4lh5AkvNP0RwIhHvQTc7QDgj4aymLpDIyZQSqSwM4jvDcdxoL0D2FrGL/V54Bx/NBQH/9JJVpAsV0nsQhaEuM76pox3a8Lc6Itqm22FL7L4MnHmtQ+XaOqWu7cvB8YiBOPuppqy2YPzY1E7cbv7NLt+5UL30+x/+3X8nwADAGdc48ttRnltAAAAAElFTkSuQmCC"
          }
        }, function (marker) {});
      }
    }

**Comment by cvaliere** [comment] 2016-04-15 17:09
@wf9a5m75 do you reproduce the bug with this code?
it's been two days we try to fix this bug, with no success :(

thanks !

**Comment by wf9a5m75** [comment] 2016-04-15 18:08
I have been checking one by one. Please wait.

**Comment by PapyElGringo** [comment] 2016-04-18 08:04
Can you reopen this issue? It's a major issue for us. It's delayed our release.

Tell me if I can help.

**Comment by cvaliere** [comment] 2016-04-19 14:34
hi @wf9a5m75 I confirm it's a major issue, can you at least reopen it so other users can discuss on it?

thanks!

**Comment by wf9a5m75** [comment] 2016-04-19 18:34
Ok, please retry the master branch.

**Comment by PapyElGringo** [comment] 2016-04-20 13:58
Test in progress so far it's good job!

**Comment by PapyElGringo** [comment] 2016-04-21 09:24
My issue is resolved !

**Closed** 2016-04-21 10:29 UTC
Labels: can't reproduce
