### ISSUE TITLE
Exception on circle.setCenter

### ISSUE THREAD

**Issue by sirhaplo** [mapsplugin/cordova-plugin-googlemaps#1824] opened 2017-10-19 14:05 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[X ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ X] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-camera 2.4.1-dev "Camera"
cordova-plugin-compat 1.1.1-dev "Compat"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-opener2 2.0.2 "File Opener2"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-toast 2.5.2 "Toast"
cordova-sqlite-storage 1.5.3 "Cordova sqlite storage plugin"

**Current behavior:**
Sometimes i got a NullPointerException

```
java.lang.NullPointerException: 
  at plugin.google.maps.PluginCircle$2.run (PluginCircle.java:106)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6823)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1563)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1451)
```

And the app crashes.

**Expected behavior:**
App should not crash

**Steps to reproduce:**
It's an async problem with the geolocation update. Difficult to reproduce

**Related code, data or error log (please format your code or data):**

When the map is ready i start watching the geolocation :
```
map.addEventListener(plugin.google.maps.event.MAP_READY, function () {
                    console.log("[Mappa] Ready");
                    map_ready = true;
                    map.setIndoorEnabled(false);
                    map.setMyLocationEnabled(true);
                    geolocationService.startWatch(positionUpdate);
...
});
```
On position update i set a circle around my location or i move it.
If the map is not null, if the map fired MAP_READY, if the circle is not null
```
function setCircle(coords, distance) {
            if ((map != null) && (map_ready)) {
                if (circle != null) {
                    var latLng = new plugin.google.maps.LatLng(coords.latitude, coords.longitude);
                    circle.setCenter(latLng);
                } else {
                        var mylatLng = new plugin.google.maps.LatLng(coords.latitude, coords.longitude);
                        map.addCircle({
                            'center': mylatLng,
                            'radius': distance,
                            'strokeColor': '#AA00FF',
                            'strokeWidth': 1,
                            'fillColor': '#ffcccc'
                        }, function (newCircle) { circle = newCircle; });   
                 }         
            }
        }
```
When i leave i clear all

```
$scope.$on('$ionicView.beforeLeave', function () {
            console.log("ionicview.beforeleave");
            circle = null;
            if (map != null) {
                map.remove();
                map.setDiv(null); 
            }
            map = null;
            geolocationService.stopWatch();
}

```
Sometimes i got this exception even i double checked everything.
Java dosent find the id ( probably beacause the map is not open anymore ) and it crash

The exception is generated here
```
public void setCenter(final JSONArray args, final CallbackContext callbackContext) throws JSONException {
    String id = args.getString(0);
    final LatLng center = new LatLng(args.getDouble(1), args.getDouble(2));
    final Circle circle = this.getCircle(id);
  
    cordova.getActivity().runOnUiThread(new Runnable() {
      @Override
      public void run() {
        // Recalculate the circle bounds
        String propertyId = "circle_bounds_" + circle.getId();
```

Maybe a try / catch to be sure if circle exists ?
I expect the same problem in other overlay objects.

**Comment by wf9a5m75** [comment] 2017-10-19 14:16
Please share your project files on github.

**Comment by sirhaplo** [comment] 2017-10-19 14:23
If I could, I would do it but i can't.
I extracted what I could, it's all the code that use the circle variable.

**Comment by wf9a5m75** [comment] 2017-10-19 15:22
Sorry. I think this error is related with your code. If you can't share your code, I can't help you.

Please chose one from below:
1) create a demo project that reproduce your issue 100%
2) or, close this thread

**Comment by wf9a5m75** [comment] 2017-10-19 16:06
The plugin works safely if you use correctly.
Unfortunately, I'm so busy person. I have not enough time to play with your quiz.
If you create a demo, and share it, I will help you. Otherwise, no help. Please resolve the issue by yourself.
Source code is full open. You can use this plugin as free. But my time is not free.

**Comment by sirhaplo** [comment] 2017-10-20 07:39
> Otherwise, no help. Please resolve the issue by yourself.

I dont understand you. In 2 previously issues like mine you helped, gave some advices and fixed your code to prevent this NullPointer.
Without shared projects and without explicit conditions to replicate.
Why not in this case ?

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1797

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1569

I'm not asking for help. I'm pointing a problem that could affect other people.

**Comment by wf9a5m75** [comment] 2017-10-20 13:53
As far as I test, the plugin does not crash with circle.setCenter(). At least, I can not reproduce your issue.

I think the reason is in your code. That's why I asked. But even if you don't want to create a demo, you can close this thread.
If the problem is happened in other people, I should receive the craim from another people, but it's only you so far.

**Comment by wf9a5m75** [comment] 2017-10-24 20:46
ping

**Comment by sirhaplo** [comment] 2017-10-25 13:09
The issues keeps occurring.
If you will not look for this issue, we will do a fork of your code and we will fix this for our use with a try / catch.

**Comment by wf9a5m75** [comment] 2017-10-25 13:59
As I said, I'm so busy. And I can't reproduce your issue so far, and I don't have enough time to make test case for only this case.

If you don't share the code, I can't debug it.
In that case, please fork the repository and fix it.
Then send it as a pull request.
That's the open source code style !!!

**Comment by sirhaplo** [comment] 2017-10-26 10:53
We are working on it, but we will develop only the android fix.

**Comment by wf9a5m75** [comment] 2017-11-01 18:09
Since there is no update, I close this thread. But you can still reply anytime with update.
I haven't experienced this issue, but if you find anything please let me know.
![capture](https://user-images.githubusercontent.com/167831/32289823-25308bd6-bef5-11e7-9f27-db5b95710d6c.gif)

**Closed by wf9a5m75** 2017-11-01 18:09 UTC
Labels: need more information, pending / waiting
