### ISSUE TITLE
HtmlInfoWindow issue with beta

### ISSUE THREAD

**Issue by yunho2141** [mapsplugin/cordova-plugin-googlemaps#1917] opened 2017-11-24 14:36 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[ x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x ] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.1.2-beta-20171122-2100 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/google-maps": "^4.4.2",
"@ionic-native/core": "^4.4.2",

**Current behavior:**

when I reinstalled plugin with above version.
during running app on android. it keep occured below error message.

please check it.

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
Uncaught TypeError: Object [object NodeList] has no method 'forEach' googlemaps-cdv-plugin.js:247

```

**Comment by wf9a5m75** [comment] 2017-11-24 15:25
Too less information. Please provide more information.
The error log is too less.

And in order to reproduce your issue, please share your project files on GitHub or other git repository services.

(If no, please create a demo project. Even if you decline, no help)

**Comment by wf9a5m75** [comment] 2017-11-25 23:42
ping

**Comment by wf9a5m75** [comment] 2017-11-27 21:46
ping (if no reply, I will close this thread)

**Comment by wf9a5m75** [comment] 2017-11-28 15:14
Since there is no update, I close this thred. But you can reply anytime with new information.

**Closed by wf9a5m75** 2017-11-28 15:14 UTC
Labels: need more information
