### ISSUE TITLE
In ios map is not showing after using 2.6.0

### ISSUE THREAD

**Issue by kalaiprakash93** [mapsplugin/cordova-plugin-googlemaps#2608] opened 2019-04-23 19:51 UTC
I have developed my map functionalities uisng v2. 3.0 in this version ios working fine. But when changed to v2. 6.0 the map is not displaying with no errors.
In android it is working fine.

**Comment by wf9a5m75** [comment] 2019-04-23 19:53
Please provide more information:

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report

**OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 


**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : 
@ionic-native/google-maps : 
```

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

**Comment by wf9a5m75** [comment] 2019-04-23 19:54
And please share your project files on github repository.

**Comment by wf9a5m75** [comment] 2019-04-23 20:58
ping

**Comment by eltaiguer** [comment] 2019-04-24 13:18
Hi! I had a similar problem yesterday and I had two related issues:

- https://github.com/mapsplugin/cordova-plugin-googlemaps#api-key-android-and-ios-platforms

- Try removing and adding the ios platform again and check if you have an error for a missing `cordova-common` module, if that's the case just `npm install` it and try re-adding the platform again

**Comment by kalaiprakash93** [comment] 2019-04-26 03:29
In version 2.6.0. This plugin is skipping from adding to the project. So, am using 2.5.1. Its working fine.

If i want to use, android and ios google map sdk, i need to enable billing for both SDK right?

**Comment by wf9a5m75** [comment] 2019-04-26 03:35
> If i want to use, android and ios google map sdk, i need to enable billing for both SDK right

Yes. But Android and iOS are still free.

**Comment by kalaiprakash93** [comment] 2019-04-26 04:36
I don't know about this..without enabling billing option we can trigger 'N' numberof requests while using SDK is in it?

**Comment by wf9a5m75** [comment] 2019-04-26 05:25
This is not FAQ community. Please read Google's official page.
https://cloud.google.com/maps-platform/pricing/sheet/

**Comment by battika** [comment] 2019-04-26 12:41
@kalaiprakash93 that is correct. However in the free plan they included a very generous number of requests and you can monitor your usage through the Google API Console. I have never managed to exceed the limitation.

**Comment by wf9a5m75** [comment] 2019-04-29 23:52
Ping @kalaiprakash93

**Comment by wf9a5m75** [comment] 2019-05-01 16:26
Since there is no update for a while, I close this thread.

**Closed by wf9a5m75** 2019-05-01 16:26 UTC
