### ISSUE TITLE
Grey background on android version 4.4.2

### ISSUE THREAD

**Issue by nicolabeltramigit** [mapsplugin/cordova-plugin-googlemaps#1734] opened 2017-09-13 11:16 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[X] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[X] **2.0-beta3 (github)** 
[ ] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[X] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.1
    npm               : 3.10.10 
    OS                : Linux 4.4

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please show me the package.json**

I rename with xxx my private data on package

{
    "name": "xxx",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/google-maps": "4.2.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
        "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.6.0",
        "ionic-native": "^2.9.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.1.4",
        "typescript": "2.3.4"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "xxx",
                "API_KEY_FOR_IOS": "xxx"
            }
        },
        "platforms": [
            "android"
        ]
    }
}

**Current behavior:**
On android version 4.4.2 i see the background dark (grey/black) when i add the Overlay Tile.
The overlay image is a transparent png 
I see my png on overlay and the name of city of the map
I don't have the problem with android version 7

**Expected behavior:**
I want tho see the map with the overlay but no dark map

**Steps to reproduce:**

**Screen capture or video record:**
![screen](https://user-images.githubusercontent.com/31882594/30374566-ab780444-9885-11e7-94bc-c011c28b88c2.jpg)

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here

**Comment by wf9a5m75** [comment] 2017-09-13 14:17
First of all, you probably use the `@ionic-native/core` 3.12.1, but you have to use the 4.2.1.

And without share your project files, or the png file, what can I help you?

**Comment by wf9a5m75** [comment] 2017-09-13 14:39
One of I guess is your png file is 24bits color. Try 32 bits color.

Even the problem still occurs, please share your project files, including the image files, on github or others.
I will check it.

**Comment by nicolabeltramigit** [comment] 2017-09-13 14:57
Hi, thanks a lot for the answer.
I attach part of code, you can insert it in a simple ionic sidemenu template

About the png i insered in the code an url to transparent png, the problem is the same.
Sorry but i can't commit all code on github.

Updating the version of @ionic-native/core to 4.2.1 the problem is the same.

I repeat only with 4.4.2 android version i've the problem, with the 7 all is ok.

Thanks for your help

[files.zip](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/1299831/files.zip)

**Comment by wf9a5m75** [comment] 2017-09-13 15:01
Please (x3) don't share your code by zip file. I really hate that.

I'm really busy person, so I would like to save my time for the plugin issue as much as possible.
(No one pay for me for debugging, except a few donors. If you are a donor, I really appreciate for your kindness)

In order to save my time, please create a demo project , and share it on github (again no zip file!!)

**Comment by nicolabeltramigit** [comment] 2017-09-13 15:10
Ok sorry, when i have the demo project, i contact you again

Thanks

**Comment by wf9a5m75** [comment] 2017-09-13 16:12
Thank you for your contribution.

**Comment by wf9a5m75** [comment] 2017-09-15 16:06
ping

**Comment by nicolabeltramigit** [comment] 2017-09-18 15:12
Hi Masashi, sorry for the waiting time.
On github you can download a basic application. In this case i don't see the overlay png. I see only the map.
https://bitbucket.org/nicolabeltrami/test-google-maps-overlay

Note:
On config.xml i can't insert the really API_KEY  

Thanks for your time

**Comment by wf9a5m75** [comment] 2017-09-18 16:11
Hi, @nicolabeltramigit 

Thank you for preparing the project. But unfortunately, I decided I don't support `@ionic-native/google-maps` anymore after the discussion with the ionic-team.
Please ask at the `@ionic-native` repository.
https://github.com/ionic-team/ionic-native/issues

**Comment by wf9a5m75** [comment] 2017-09-19 00:34
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1749

**Comment by wf9a5m75** [comment] 2017-09-21 16:19
Luckily, the fundraising is reached to the end quickly, I restart to support the `@ionic-native/google-maps` again.
I will check your repo later.

**Comment by wf9a5m75** [comment] 2017-09-22 19:45
Is there any problems?
![device-2017-09-22-124217](https://user-images.githubusercontent.com/167831/30761559-87a6e764-9f93-11e7-95a2-4bb4f0ead8a5.png)

One thing, you **have to wait** the MAP_READY event before using any methods.

So you can not do this:

```
    ionViewWillEnter() {
        this.loadMap();
        this.getTileUrl();
    }
```

Correct code is
```

    ionViewWillEnter() {
        this.loadMap();
    }


    loadMap() {
        this.mapElement = document.getElementById( 'map' );

        this.map.one( GoogleMapsEvent.MAP_READY ).then(() => {
          this.getTileUrl();
        });

   }
```

**Comment by wf9a5m75** [comment] 2017-09-24 20:37
ping

**Comment by wf9a5m75** [comment] 2017-09-26 16:38
Since there is no update for a while, and I could not reproduce your issue, I close this thread.

**Closed by wf9a5m75** 2017-09-26 16:38 UTC
Labels: @ionic-native/googlemaps, need more information

**Comment by mkwsra** [comment] 2017-12-04 15:09
I have the same problem on **Android only**, it's working fine on iOS

I searched the internet and I couldn't find a solution! any tip on how to solve it?

```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /Users/Mike/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by mkwsra** [comment] 2017-12-04 17:50
My problem solved after more than 48 hours of very hard searching. it was all about the NODE version NOT npm, it was causing mismatching version downloading.

The version that worked for me: `9.2.0`

 npm version (not that it matters here but anyways): `5.5.1`

Thanks!
