### ISSUE TITLE
Google map Native shows blank after navigation from Tab page

### ISSUE THREAD

**Issue by bhumin3i** [mapsplugin/cordova-plugin-googlemaps#2056] opened 2018-02-07 05:59 UTC
**Short description of the problem:**
Currently loading google map on in tab page. On clicking on marker of map navigating to the new map page but new map page shows blank screen .

   this.mapDir.one(GoogleMapsEvent.MAP_READY).then(() => {
}); 

Above code is not getting fired in the new google map page .

System Info

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.1.7
    Node              : v8.9.2
    npm               : 5.5.1
    OS                : Windows 10

**Comment by wf9a5m75** [comment] 2018-02-07 06:01
In order to reproduce your issue, please share your project files on github.

**Comment by bhumin3i** [comment] 2018-02-07 06:38
do you mind but please share your personal email id ? i'll send on it.

**Comment by wf9a5m75** [comment] 2018-02-07 06:39
https://github.com/wf9a5m75

**Comment by bhumin3i** [comment] 2018-02-07 06:49
thanks share project file on mail please check

**Comment by wf9a5m75** [comment] 2018-02-07 06:52
I haven't received any e-mail yet. It's already midnight, so I will check your repo tomorrow.

**Comment by thezakman** [comment] 2018-02-07 14:45
I guess @bhumin3i  has the same problem as mine, try what @wf9a5m75 told me too:

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2049

**Comment by bhandaribhumin** [comment] 2018-02-07 15:00
Thanks @thezakman  yes it is look like same as my issue. but I'm facing new issue while call https //maps.googleapis.com/  http.get on iOS give me on subscribe error Response with status: 0  for URL: null 
can you please help me on this you have some idea ?

**Comment by wf9a5m75** [comment] 2018-02-07 15:19
@bhandaribhumin This plugin does not use the google maps JavaScript API v3. It means you are wrong place to ask your question.

**Comment by bhandaribhumin** [comment] 2018-02-07 15:29
@wf9a5m75 below my issue is not related to your google maps, but if you have any idea about this so can you please suggest me solution my issue is same as https://stackoverflow.com/questions/47741693/ionic-2-http-get-request-null-response

can you please help me on this.
I'm facing issue only on iOS. :(

**Comment by wf9a5m75** [comment] 2018-02-07 15:36
@bhandaribhumin please do not ask about the non-related issue at repository issue. That is out of manners.
Unfortunately, I'm not familiar with ionic. Please ask at https://forum.ionicframework.com/

**Comment by wf9a5m75** [comment] 2018-02-07 17:15
Since @bhumin3i tell me the problem is solved about the original issue by e-mail, I close this thread. The Google Maps JS API is not under the coverage at here.

**Closed by wf9a5m75** 2018-02-07 17:15 UTC
Labels: need more information

**Comment by Mekosam** [comment] 2019-10-15 07:09
> @bhandaribhumin This plugin does not use the google maps JavaScript API v3. It means you are wrong place to ask your question.

https://github.com/Mekosam/maps    please check my repository about the same issue
