### ISSUE TITLE
marker BOUNCE not working!

### ISSUE THREAD

**Issue by miguelcs6** [mapsplugin/cordova-plugin-googlemaps#1617] opened 2017-08-06 00:24 UTC
Hi,

When using the BOUNCE animation the application quits unexpectedly.
//marcadores[ind].setAnimation(plugin.google.maps.Animation.BOUNCE);

When changing the DROP animation type if it works correctly
marcadores[ind].setAnimation(plugin.google.maps.Animation.DROP);

I tried both versions...

Thank you

**Comment by wf9a5m75** [comment] 2017-08-06 00:27
Please tell me more information.


**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ ] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

**Steps to reproduce:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

**Comment by miguelcs6** [comment] 2017-08-06 00:38
plugin version: (check one with "x")
[x] 1.4.x
[x] 2.0.0-beta2

com.telerik.plugins.wkwebview 0.6.10 "WKWebView Polyfill"
cordova-android-play-services-gradle-release 0.0.2 "cordova-android-play-services-gradle-release"
cordova-plugin-android-permissions 0.11.0 "Permissions"
cordova-plugin-camera 2.4.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-googlemaps 1.4.3 "cordova-googlemaps-plugin"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"


                   if (success.data[ind].geofence_id != null) {
                        if (success.data[ind].geofence_alarm === true) {

                          //marcadores[ind].setAnimation(plugin.google.maps.Animation.BOUNCE);
                          marcadores[ind].setAnimation(plugin.google.maps.Animation.DROP);

                        } else {
                          //Normal
                          marcadores[ind].setAnimation(null);
                        }
                      }

Only closes the app unexpectedly when I use Bounce animation

**Comment by wf9a5m75** [comment] 2017-08-06 00:39
If you use the ionic-wrapper, you have to use the plugin v2, not v1.4.3

**Comment by wf9a5m75** [comment] 2017-08-07 14:09
ping

**Comment by wf9a5m75** [comment] 2017-08-08 22:41
Since there is no update, and no enough information is provided, I close this issue.
But you can still reply to this issue thread.

**Closed by wf9a5m75** 2017-08-08 22:41 UTC
Labels: need more information, pending / waiting
