### ISSUE TITLE
Adding bounds to Ground Overlay does not only rotate but translate

### ISSUE THREAD

**Issue by CrisBarreiro** [mapsplugin/cordova-plugin-googlemaps#2413] opened 2018-09-06 12:43 UTC
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report

**OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.4.2 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : "^4.7.0"
@ionic-native/google-maps : "^4.7.0"
```

**Current behavior:**

If creating a ground overlay with `bearing` parameter, the overlay is shown not only rotated, but also translated

**Expected behavior:**
The `bearing` parameter should only rotate the overlay, taking its center as reference, without moving it. This is the observed behavior on older versions (i.e. 2.2.2) or 2.4.2 version on iOS

**Screen capture or video record:**
Actual: 
<img src="https://user-images.githubusercontent.com/6297834/45157824-7a74cb80-b1e2-11e8-9170-5a09f070aa3c.png" width="250">

Expected:
<img src="https://user-images.githubusercontent.com/6297834/45157825-7a74cb80-b1e2-11e8-9c4e-8c073edc55c9.png" width="250">

No bearing:
<img src="https://user-images.githubusercontent.com/6297834/45157826-7a74cb80-b1e2-11e8-82bc-0085b62074ac.png" width="250">

**Related code, data or error log (please format your code or data):**

https://github.com/situmtech/situm-cordova-getting-started/blob/master/src/pages/positioning/positioning.ts

```javascript
  private mountOverlay(loading) {
    let bounds = this.getBounds(this.building);
    let groundOptions: GroundOverlayOptions = {
      url: this.currentFloor.mapUrl,
      bounds: bounds,
      bearing: this.building.rotation * 180 / Math.PI
    }
    this.map.addGroundOverlay(groundOptions).then(() => {
      this.hideLoading(loading);
    }).catch((err: any) => this.handleError(err, loading));
  }
```

**Comment by wf9a5m75** [comment] 2018-09-06 14:32
Um, I wonder. 
There is code in Android part.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/android/plugin/google/maps/PluginGroundOverlay.java#L55-L57

I will check your program later.

**Comment by wf9a5m75** [comment] 2018-09-07 01:17
I tried your project though, but you didn't set API key for your API, I could not confirm your issue.

I also tried to reproduce the issue with more simple code, however it worked (but the result was different that I expected).

![capture](https://user-images.githubusercontent.com/167831/45193065-22998d00-b201-11e8-97e8-e59a2482b770.png)

```typescript
    this.groundOverlay = this.map.addGroundOverlaySync({
      'url': 'assets/imgs/newark_nj_1922_2.jpg',
      'bounds': bounds,
      'opacity': 0.5,
      'bearing': 45,
      'clickable': true  // default = false
    });
```

**Comment by CrisBarreiro** [comment] 2018-09-07 07:51
If you can share an email address, I can send you an API key

**Comment by wf9a5m75** [comment] 2018-09-07 14:18
My email address is open.
https://github.com/wf9a5m75

**Comment by CrisBarreiro** [comment] 2018-09-10 06:28
Ok, I have shared an API Key with you

**Comment by wf9a5m75** [comment] 2018-09-10 17:36
Thank you for sharing the api key.

But I got this error in native log, and `cordova.plugins.Situm.fetchFloorsFromBuilding` does not come back forever
```
09-10 10:30:29.099 17013-17114/es.situm.cordova.gettingstarted D/SitumPlugin: execute: fetchFloorsFromBuilding
09-10 10:30:29.101 17013-17114/es.situm.cordova.gettingstarted E/PluginHelper: Unexpected error in floor response
```

**Comment by wf9a5m75** [comment] 2018-09-10 17:50
Details:

```
09-10 10:49:15.273 30097-30199/es.situm.cordova.gettingstarted D/SitumPlugin: execute: fetchFloorsFromBuilding
09-10 10:49:15.276 30097-30199/es.situm.cordova.gettingstarted E/PluginHelper: Unexpected error in floor response
    org.json.JSONException: Value [{"address":"","bounds":{"northEast":{"latitude":42.872543578339844,"longitude":-8.56281818418898},"northWest":{"latitude":42.872543578339844,"longitude":-8.563690560285774},"southEast":{"latitude":42.872159638832336,"longitude":-8.56281818418898},"southWest":{"latitude":42.872159638832336,"longitude":-8.563690560285774}},"boundsRotated":{"northEast":{"latitude":42.87210354936383,"longitude":-8.563634685970657},"northWest":{"latitude":42.87222236845012,"longitude":-8.562777397366137},"southEast":{"latitude":42.8724808487564,"longitude":-8.563731347015244},"southWest":{"latitude":42.872599667842685,"longitude":-8.56287405836404}},"center":{"latitude":42.8723516085782,"longitude":-8.56325437220903},"dimensions":{"width":71.2814440537621,"height":42.6519223803104},"infoHtml":"","name":"Test building","pictureThumbUrl":"","pictureUrl":"","rotation":2.9553412848927,"userIdentifier":"-1","buildingIdentifier":"4045","customFields":{},"createdAt":"Sun Sep 09 23:21:29 PDT 2018","updatedAt":"Sun Sep 09 23:22:37 PDT 2018"}] at 0 of type org.json.JSONArray cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:101)
        at org.json.JSONArray.getJSONObject(JSONArray.java:525)
        at es.situm.plugin.PluginHelper.fetchFloorsFromBuilding(PluginHelper.java:137)
        at es.situm.plugin.SitumPlugin.execute(SitumPlugin.java:64)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SourceFile:9)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by wf9a5m75** [comment] 2018-09-10 18:00
Ok, I got it.

As I provided an example, you need to specify `anchor` property.

```

    let groundOptions: GroundOverlayOptions = {
      url: this.currentFloor.mapUrl,
      bounds: bounds,
      bearing: this.building.rotation * 180 / Math.PI,
      anchor: [0.5, 0.5]   <--- this.
    }
```

`0.5` means `50%`.

<img src="https://user-images.githubusercontent.com/167831/45315238-b496e380-b4e8-11e8-8d27-5a41f0cb3937.png" width="250">

**Comment by CrisBarreiro** [comment] 2018-09-11 06:13
Are you using the example application as-is? We have fixed mapsplugin to version 2.2.2 as that version is working as intended for us

**Comment by wf9a5m75** [comment] 2018-09-11 06:39
Yes. By the way I don't support older version.

**Comment by CrisBarreiro** [comment] 2018-09-11 06:55
No, what I meant is that I was having that issue using 2.4.2, so I downgraded to 2.2.2 temporarily because that version seemed to work ok. Nevertheless, after checking your messages, it seems that adding the `anchor` property makes it work perfectly on version 2.4.2.

As the lack of this property was causing this issue, would you consider adding it to the documentation? I have looked for it [here](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/GroundOverlay/README.md) but I cannot find the `anchor` property. Sorry if I am not checking the right site. 

According to Google Maps [official documentation](https://developers.google.com/maps/documentation/android-sdk/groundoverlay):

"When you add the image you specify a LatLng to which the anchor will be fixed and the width of the overlay (in meters). The anchor defaults to the center of the image. You can optionally provide the height of the overlay (in meters). If you do not provide the height of the overlay, it will be automatically calculated to preserve the proportions of the image."

So wouldn't the anchor default value be `[0.5, 0.5]`?

Thank you

**Comment by wf9a5m75** [comment] 2018-09-11 07:01
If you doubt, please check the code. If you find something, please send a PR. All source code is open.
Documentation is as well.

**Comment by wf9a5m75** [comment] 2018-09-14 05:26
Do you still need to open this issue thread?

**Comment by wf9a5m75** [comment] 2018-09-16 03:01
Since there is no update fo a while, I close this thread

**Closed by wf9a5m75** 2018-09-16 03:01 UTC
Labels: not bug
