### ISSUE TITLE
Flash hyperzoomed on transition to map

### ISSUE THREAD

**Issue by Textras** [mapsplugin/cordova-plugin-googlemaps#1960] opened 2017-12-20 01:01 UTC
**I'm submitting a ...**  (check one with "x")
[x ] question
[ ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```
Video of the 'hyper-zoomed' in bug that flashed before map markers plot. We are using the most current plugin version on Android w Cordova 6.4.0. We do not destoy our maps, for the record. 

https://www.youtube.com/watch?v=742U8xOwKUA&feature=youtu.be

Wondering if any idea what causes the hyperzoom has anyone experienced this? If you pause at the :26 sec mark and move fwd frame by frame you can see it best. You will see the very zoomed in map marker and street names, before getting back to our original zoom settings. The white flashes are here as well which any-input on is nice, but we may have just resolved that and are testing now. This is more about the zoom flash. If anyone is seeking a clue to the white flash link below may help you. https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1161

**Comment by wf9a5m75** [comment] 2017-12-20 01:44
What is the `hyper-zoomed`? Do you mean high zoom level, such as zoom 20?

And I guess you use css transition, or something. But the maps plugin can not detect it until the css event is finished.

**Comment by wf9a5m75** [comment] 2017-12-20 01:44
If you want me to check your code, please share your project files on github.

**Comment by Textras** [comment] 2017-12-20 02:42
Yes, a high zoom level (just using the term 'hyperzoom' on my own. The map view jumps very quickly (almost a flash) from the start on map.setVisible(true); when user enters map, before correcting to the appropriate zoom level. Almost as if there are 2 zooms occuring and the second fixes the first after 500ms. You can see many examples of the flicker in the YouTube video. Did you see? (link above).

I can post code too, I just thought I might ask with a video example first as perhaps you came across this issue prior and already knew the solution/cause in order to help save your time. Tnx.

**Comment by wf9a5m75** [comment] 2017-12-20 02:49
In order to reproduce your issue, please share your project files on github. Otherwise, please fix it by yourself. (part of code is not acceptable)

If you can not share your project files, please create a demo project that reproduce your issue 100%.

**Comment by wf9a5m75** [comment] 2017-12-24 04:39
ping

**Comment by wf9a5m75** [comment] 2017-12-26 21:14
Since there is no update for a while, I close this thread. But you can reply with new information.

**Closed by wf9a5m75** 2017-12-26 21:14 UTC
Labels: need more information
