### ISSUE TITLE
this.off() in ionic 3 - remove event maps

### ISSUE THREAD

**Issue by IvanMoreFlores** [mapsplugin/cordova-plugin-googlemaps#2046] opened 2018-02-04 17:40 UTC
Someone can help me cancel a map event, previously it was map.off () but that does not work anymore.

**Comment by wf9a5m75** [comment] 2018-02-04 19:34
please share your project files on GitHub

**Comment by wf9a5m75** [comment] 2018-02-05 15:34
ping

**Comment by IvanMoreFlores** [comment] 2018-02-05 16:28
https://github.com/IvanMoreFlores/Evento-Maps/blob/master/src/pages/mapa/mapa.ts

line 520

**Comment by wf9a5m75** [comment] 2018-02-05 17:13
this?
https://github.com/IvanMoreFlores/Evento-Maps/blob/02a5c1b5260f39faf609fc11d07301fc6bf58b9d/src/pages/mapa/mapa.ts#L521

**Comment by IvanMoreFlores** [comment] 2018-02-05 17:20
with that event I want to deactivate the event but the .off does not work





2018-02-05 12:13 GMT-05:00 Masashi Katsumata <notifications@github.com>:

**Comment by wf9a5m75** [comment] 2018-02-05 17:21
In your code, you are wrong from the first.

```
new GoogleMap('map', { ... })
```

is not supported way.

```
this.map = GoogleMaps.create('map', { ...});
```

is only supported way.

-----

You don't need to execute `this.map.refreshLayout()` basically.
This method is for internal use recently.

----

The `MAP_READY` event is fired only at once when you create a map using `GoogleMaps.create()`.

It means you should use `this.map.one(GoogleMapsEvent.MAP_READY).then()` instead of `this.map.on(GoogleMapsEvent.MAP_READY).subscribe()`.

You try `this.map.off()` **after** the event, but it does not work of course, because the event is already fired.

-----

Please read the public documentation well before using the maps plugin.

https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.p

**Comment by IvanMoreFlores** [comment] 2018-02-05 19:31
Then I can not do anything?

**Comment by wf9a5m75** [comment] 2018-02-05 19:35
You just ask me `how to remove the event listener`. Then what else? Please describe **what is your problem with more details**.

**Comment by IvanMoreFlores** [comment] 2018-02-05 19:38
Ok, I have a pin with the event
GoogleMapsEvent.MAP_DRAG_END,

and I want to place a button where cancel this event and when you move the map you no longer use the GoogleMapsEvent.MAP_DRAG_END

**Comment by wf9a5m75** [comment] 2018-02-05 19:39
`this.map.off(GoogleMapsEvent.MAP_DRAG_END)`

**Comment by IvanMoreFlores** [comment] 2018-02-05 19:42
![image](https://user-images.githubusercontent.com/30874644/35825067-b8ccd0d8-0a82-11e8-9273-c39b6520ce70.png)

**Comment by wf9a5m75** [comment] 2018-02-05 19:45
I don't support your editor warning.

**Comment by wf9a5m75** [comment] 2018-02-05 19:46
Did you confirm `console.log(this.map)`? I'm not your teacher or friend. So please do your best as much as possible.

**Comment by IvanMoreFlores** [comment] 2018-02-05 19:53
I'm sorry, it tells me that there is no .off
next to the console.log

![image](https://user-images.githubusercontent.com/30874644/35825557-40c36fb4-0a84-11e8-8847-dbb2b77e37b9.png)

**Comment by wf9a5m75** [comment] 2018-02-05 20:37
As I said, `please do your best as much as possible.`
![screen shot 2018-02-05 at 12 35 01 pm](https://user-images.githubusercontent.com/167831/35827558-4fe2c804-0a71-11e8-972c-ecb65e70b88a.png)

**Comment by IvanMoreFlores** [comment] 2018-02-05 21:35
What happend? :O in the map no off

![image](https://user-images.githubusercontent.com/30874644/35829954-8dc80c58-0a92-11e8-9e9f-9d3bdd35013c.png)

**Comment by wf9a5m75** [comment] 2018-02-05 21:38
https://github.com/IvanMoreFlores/Evento-Maps/blob/master/package.json#L38

Why do you use `2.1.1`. That's too old.

**Comment by IvanMoreFlores** [comment] 2018-02-05 22:24
how update cordova-maps a 2.2.2?

**Comment by wf9a5m75** [comment] 2018-02-05 22:43
You just remove the maps plugin, then install the maps plugin again.

```
$> cordova plugin remove cordova-plugin-googlemaps
$> cordova plugin add cordova-plugin-googlemaps@2.2.2 --variable API_KEY_FOR_ANDROID="..."
```

**Comment by IvanMoreFlores** [comment] 2018-02-06 13:15
Sorry to bother you, but create a new project with maps 2.2.2 but I still do not get the .off

![image](https://user-images.githubusercontent.com/30874644/35861443-bb44b5ea-0b15-11e8-9853-ee9b615b15ad.png)

**Comment by wf9a5m75** [comment] 2018-02-06 14:52
You definitely don't install the latest version, because the map class does not have the addKmlOverlay() method whch is implement from v2.2.0

**Comment by wf9a5m75** [comment] 2018-02-06 18:30
Unfortunately, I cant reproduce your issue so far.

**Comment by IvanMoreFlores** [comment] 2018-02-06 21:33
Sorry for making you angry, but I have in mind that in the folder of @ onic-native in google-maps are not the events that you mention;
![image](https://user-images.githubusercontent.com/30874644/35885270-5654cecc-0b5b-11e8-9c89-4040967732ff.png)

**Comment by wf9a5m75** [comment] 2018-02-06 22:54
ionic-native/google-maps is not my plugin. I just contribute it. If you have a problem, something missing methods, you need to send a PR.

**Comment by wf9a5m75** [comment] 2018-02-07 15:29
Try this.

https://forum.ionicframework.com/t/ionic-native-googlemaps-decodepath-returns-undefined/118624/7

**Comment by wf9a5m75** [comment] 2018-02-08 02:39
ping

**Comment by wf9a5m75** [comment] 2018-02-08 20:02
Since there is no update for a while, I close this thread.

**Closed by wf9a5m75** 2018-02-08 20:02 UTC
Labels: not bug, pending / waiting
