### ISSUE TITLE
error facing

### ISSUE THREAD

**Issue by Hredoy** [mapsplugin/cordova-plugin-googlemaps#1943] opened 2017-12-12 08:20 UTC
![capture](https://user-images.githubusercontent.com/16982572/33874042-91575516-df47-11e7-8285-5dc56dc2b57f.PNG)
why i am facing this problem  i need solution... any one?

**Comment by smark91** [comment] 2017-12-12 14:29
Remove and reinstall both cordova maps plugin and ionic maps plugin

**Comment by wf9a5m75** [comment] 2017-12-12 15:12
And this plguin does not work on browser.

**Comment by Hredoy** [comment] 2017-12-12 16:26
i m  using phonegap build how can i add dis

**Comment by Hredoy** [comment] 2017-12-12 16:47
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Geo Location</title>
  <script type="text/javascript" src="cordova.js"></script>
  <script src="js/index.js"></script>
  <script type="text/javascript">
var map;
document.addEventListener("deviceready", function() {
  var div = document.getElementById("map");

  // Initialize the map view
  map = plugin.google.maps.Map.getMap(div);

  // Wait until the map is ready status.
  map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
}, false);

function onMapReady() {
  var button = document.getElementById("button");
  button.addEventListener("click", onButtonClick);
}

function onButtonClick() {

  // Move to the position with animation
  map.animateCamera({
    target: {lat: 37.422359, lng: -122.084344},
    zoom: 17,
    tilt: 60,
    bearing: 140,
    duration: 5000
  }, function() {

    // Add a maker
    map.addMarker({
      position: {lat: 37.422359, lng: -122.084344},
      title: "Welecome to \n" +
             "Cordova GoogleMaps plugin for iOS and Android",
      snippet: "This plugin is awesome!",
      animation: plugin.google.maps.Animation.BOUNCE
    }, function(marker) {

      // Show the info window
      marker.showInfoWindow();

      // Catch the click event
      marker.on(plugin.google.maps.event.INFO_CLICK, function() {

        // To do something...
        alert("Hello world!");

      });
    });
  });
}
</script>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <style>
    *{
      font-family: 'Roboto', sans-serif;
    }
       #map {
        height: 1000px;
        width: 100%;
       }
       .gmnoprint{
        display: none;
       }
       .gm-fullscreen-control{
        display: none;
       }
      .header{
        padding: 5px;
        text-align: center;
        text-transform: uppercase;
        background: #000;
        color:#fff;
      }
  </style>
  </head>
  <body style="overflow: hidden;margin: 0">
    <div data-role="page" id="page1">
        <div data-role="header" class='header'>
            <h1>Map Page</h1>
        </div>
        <div data-role="content">

        <button id="button">Btn</button>
        <div id="map"></div>
        </div>
    </div>
  </body>
</html>




//config.xml 
<plugin name="cordova-plugin-googlemaps" source="npm" spec="~2.1.1">
        <variable name="API_KEY_FOR_ANDROID" value="i added api here" />
        <variable name="API_KEY_FOR_IOS" value="i added api here" />
        <variable name="LOCATION_WHEN_IN_USE_DESCRIPTION" value="My custom when in use message" />
        <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="My custom always usage message" />
    </plugin>

// plugin list 
![capture](https://user-images.githubusercontent.com/16982572/33896825-086255d4-df8e-11e7-9ede-f362c72e001e.PNG)

//mobile view
![25346365_500979830286414_925347182_o](https://user-images.githubusercontent.com/16982572/33896875-3277a158-df8e-11e7-806c-cdbd881fe723.png)

when i click that button map doesn't showing. 
give me  a proper solution

**Comment by wf9a5m75** [comment] 2017-12-12 17:16
In order to reproduce your issue on my side, please share your git repository.

**Comment by wf9a5m75** [comment] 2017-12-13 17:12
ping

**Comment by wf9a5m75** [comment] 2017-12-14 17:07
ping

**Comment by Hredoy** [comment] 2017-12-14 18:04
I didn't upload it on github.  I will upload it tomorrow and add you okay!

**Comment by wf9a5m75** [comment] 2017-12-18 02:07
ping

**Comment by wf9a5m75** [comment] 2017-12-19 19:09
Since there is no update for a while, I close this thread. But you can still reply with new information.

**Closed by wf9a5m75** 2017-12-19 19:09 UTC
Labels: pending / waiting
