### ISSUE TITLE
Creating 1 map per page; 3rd map doesn't render correctly on Ionic Android build

### ISSUE THREAD

**Issue by ryanhalley** [mapsplugin/cordova-plugin-googlemaps#1629] opened 2017-08-09 19:16 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
com.xmartlabs.cordova.market 1.1 "Market"
cordova-custom-config 3.2.0 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-name 1.0.0 "App Namer"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-contacts 2.3.0 "Contacts"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-email 1.2.6 "EmailComposer"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta3-20170805-2349 "cordova-plugin-googlemaps"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-network-information 1.3.2 "Network Information"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
cordova-sqlite-storage 1.5.3 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.5 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"
```

**Current behavior:**

I am creating a page with a map instance on it, which shows a location, and clicking that location allows you to see it's details, which also has a 'show map' button on it that allows you to create another page which shows a new map, so you can keep nesting the instances further. Under 1.43, this worked fine. With 2.0beta3, the 3rd instance doesn't render correctly - it exhibits the same phenomenon that occurs when you misconfigure or misuse any of the v2 googlemaps functions, which is that the map only shows you the bottom 1cm of the screen, but it is pushed to the top of the screen. Once that occurs, the maps are borked until you kill the app/debug session. Note that maps are not being remove()'d once you leave the page; if I do that as a workaround, the issue will not appear, but it means I have to re-create all of the markers, if the user used the Back navigation. The main issue here, is that the multi-map implementation appears to be unstable after 2 instances - I'm personally ok with the workaround of removing them, but I don't think you should be forced to (like I said, 1.43 had no issue here).

**Expected behavior:**

3rd or more instances should render, like in 1.43

**Steps to reproduce:**
I don't have permission to share the code, but in essence, create a map with these options

                    let mapOptions = {
                        controls: {
                            compass: true,
                            myLocationButton: true,
                            indoorPicker: true,
                            zoom: true
                        },
                        gestures: {
                            scroll: true,
                            tilt: true,
                            rotate: true,
                            zoom: true
                        },
                        camera: cameraPosition
                    };

, and add approx 100 markers (not sure if this is the cause of the presumed render/memory issues), and make each marker have a click event that can push a new instance of the same page (with a unique map id) to the navcontroller, which repeats the above; the 3rd nested instance will not render correctly, and be unresponsive to all gestures.

**Screen capture or video record:**
See below

**Comment by ryanhalley** [comment] 2017-08-09 19:17
![img_1854](https://user-images.githubusercontent.com/13903897/29139681-b1b0bace-7d3f-11e7-9537-ed8dad3ec0e2.JPG)

**Comment by wf9a5m75** [comment] 2017-08-09 19:25
Ah, it's easy. The map div for the third map is null or size is too small.

**Comment by wf9a5m75** [comment] 2017-08-09 19:36
Since you don't want to share your code with me, I'm not sure how you write your code.
But if the map div is removed (such as changing the page), the map is also removed.

If you want to keep the map, you need to detach the map from the map div.

```js
firstMap.setDiv();  // detach the map from the map div

firstMap.setDiv(mapDiv); // re-attach the map to the map div
```

----------

You also have to recognize that creating three maps uses lots of memory.
It means your app spend lots of battery than just one map.

----------

I'm not interested in your product code at all.
But at least you should create an empty app that contains only three maps, and reproduce your issue, then share it.

If you want to help me, you need to help me.
Otherwise, I close this issue because there is no enough information.

**Comment by ryanhalley** [comment] 2017-08-09 20:19
Hi, thanks for the update. Each page is using a unique id, created from a guid function:

<div id="{{mapId}}" class="mapCanvas">

    .mapCanvas {
        height: 100%;
    }

Why will this not be ok for further pages - each page has one map only. It is fine with 1.43

**Comment by wf9a5m75** [comment] 2017-08-09 20:25
How did you write your code around map creating?

**Comment by ryanhalley** [comment] 2017-08-09 20:26
this._map = this._googleMaps.create(this.mapId, mapOptions);

where mapId is say, "gmap_" + guid()

**Comment by ryanhalley** [comment] 2017-08-09 20:28
I tried it like the ionic example, too, no difference of course:

                    let element: HTMLElement = document.getElementById(this.mapId);
                    this._map = this._googleMaps.create(element, mapOptions);

**Comment by wf9a5m75** [comment] 2017-08-09 20:29
I asked 
```
    platform.ready().then(() => {
    });
```

or 

```
  ionViewDidLoad() {
    this.loadMap();
  }
```

**Comment by wf9a5m75** [comment] 2017-08-09 20:29
And did you confirm 
```
let element: HTMLElement = document.getElementById(this.mapId);
console.log(element)
```

**Comment by ryanhalley** [comment] 2017-08-09 20:30
public ionViewWillEnter() {
         if (this._platform.ready() && this._platform.is('cordova')) {
            this.initMap();
        }
    }

I will check the console.log

**Comment by wf9a5m75** [comment] 2017-08-09 20:31
`ionViewWillEnter` means `view is not created yet`.
It means `let element: HTMLElement = document.getElementById(this.mapId);` is null

**Comment by ryanhalley** [comment] 2017-08-09 20:33
Hmm, that makes sense, but I'm surprised it works on the 1st and 2nd instance, and, works fine on all instances once I remove() the map on the page leave.

**Comment by wf9a5m75** [comment] 2017-08-09 20:36
Since you don't share your code with me, I can not answer your situation about that.

**Comment by ryanhalley** [comment] 2017-08-09 20:43
I'll look into it further, I think you've nailed it; thanks for your prompt help. I'll close the ticket.

**Closed** 2017-08-09 20:44 UTC
Labels: need more information
