### ISSUE TITLE
Update all points in the polyline

### ISSUE THREAD

**Issue by wuilmerj24** [mapsplugin/cordova-plugin-googlemaps#1547] opened 2017-07-13 00:25 UTC
Please describe your question, problem or request as much as possible.

- What is your question, problem or request?
Actualizar todos los puntos de la polilinea 

- What version of this plugin do you use? ($> cordova plugin list)
2.0.0-beta2-20170615-1407

- Screen capture or video record?
(you can upload your files with drag & drop)

- Error log (if possible)

```
(here)
```

- provide your app code

Please past your code or share your project files.
You don't want to share your code with public?
You can share with me on a private repository at the bitbucket as free.
Please read https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wf9a5m75** [comment] 2017-07-13 00:28
> Actualizar todos los puntos de la polilinea
Could you write in English?

**Comment by wf9a5m75** [comment] 2017-07-13 00:29
And updating points of the polyline, use `polyline.setPoints()`
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Polyline/setPoints/README.md

**Comment by wuilmerj24** [comment] 2017-07-13 01:13
@wf9a5m75 I have the following `this.mapa.addPolyline({
              'points': me.puntos,
              'color' : '#3e6372',
              'width': 4,
              'geodesic': true
            },function(polilinea){
              me.actualizarPolilinea(polilinea);
            });
actualizarPolilinea(polilinea){
this.updateTrazarRuta=setInterval(()=>{
      this.providerCliente.http.post(this.providerCliente.url,datos,this.providerCliente.options).map(res => res.json()).subscribe(data => {
let request = {
          origin:{lat:parseFloat(me.latitudCliente),lng:parseFloat(me.longitudCliente)},
          destination: {lat:parseFloat(data[0].latitud),lng:parseFloat(data[0].longitud)},
          travelMode: google.maps.TravelMode.DRIVING,
        };
        directionsService.route(request, function(response, status) {
          if (status == google.maps.DirectionsStatus.OK) {
            me.puntos=[];
            let legs = response.routes[0].legs;
            for (let i = 0; i < legs.length; i++) {
              let steps = legs[i].steps;
              for (let j = 0; j < steps.length; j++) {
                let nextSegment = steps[j].path;
                for (let k = 0; k < nextSegment.length; k++) {
                  //console.log(nextSegment[k]);
                  //polyline.getPath().push(nextSegment[k]);
                  //bounds.extend(nextSegment[k]);
                  me.puntos.push({lat:nextSegment[k].lat(),lng:nextSegment[k].lng()});
                }
              }
            }
            me.arrayMarcadoresProfesionales[1].setPosition({lat:parseFloat(data[0].latitud),lng:parseFloat(data[0].longitud)});
            for(let h=0;h<me.arrayMarcadoresProfesionales.length;h++){

              console.log("for polili")
            }
            polilinea.setPoints(me.puntos);
            console.log("actualizando polilinea")
          }else{
            console.log("error: no existen las rutas")
          }
        });
}
,` in the calback I make a call to a function that makes an http request and consult a coordinate and I need to update all the points of the polyline. But at some time the polyline disappears and shows no error

**Comment by wf9a5m75** [comment] 2017-07-13 01:28
>But at some time the polyline disappears and shows no error

It's depends on the result of Google Maps JavaScript API v3. 
Did you confirm what points are added to polyline?

If you provide the data that is 100% reproduce the issue, I will check it.
Otherwise, you need to dive into the issue more deeply.

**Comment by wuilmerj24** [comment] 2017-07-13 01:30
@wf9a5m75 If the polyline works well. And within the function that updates the polyline at any given time, the polyline is removed

**Comment by wf9a5m75** [comment] 2017-07-13 01:32
I couldn't understand your explain.

**Comment by wuilmerj24** [comment] 2017-07-13 01:36
@wf9a5m75 okay. I explain
I have a function that draws a polyline that works well the drawing of the polyline. In the addPolyline calback I call a function that has a setInterval that makes a query to update the start point of the polyline and pass the coordinates that I receive in the result of the query bd and endpoint the location of the device. The first 15 seconds draw the polyline, then the polyline disappears and no more is displayed.

**Comment by wuilmerj24** [comment] 2017-07-13 01:39
@wf9a5m75  how could you update the entire polyline with the result of google maps v3?

**Comment by wf9a5m75** [comment] 2017-07-13 01:40
> The first 15 seconds draw the polyline, then the polyline disappears and no more is displayed.

So it's depends on the points what points did you give.
You need to confirm the results of Google Maps v3.

**Comment by wuilmerj24** [comment] 2017-07-13 01:59
@wf9a5m75 I already

**Comment by wf9a5m75** [comment] 2017-07-13 02:02
But you did not show me the results.

**Comment by wf9a5m75** [comment] 2017-07-13 02:10
And why do you use such an old version `2.0.0-beta2-20170615-1407`.

As you may know, the v2 changes couple of times per week.
You should use the latest version at least.

**Comment by wuilmerj24** [comment] 2017-07-13 02:12
I'll show you

**Comment by wf9a5m75** [comment] 2017-07-13 02:44
In order to confirm your issue, please provide all results that you received through DirectionsService.route() method of Google Maps JavaScript API v3.
If you provide them, I will try to reproduce your issue.

**Comment by wuilmerj24** [comment] 2017-07-13 02:49
ok

**Comment by wuilmerj24** [comment] 2017-07-13 05:19
That is the result of the route
![screenshot_20170713_010303](https://user-images.githubusercontent.com/7539995/28151312-df707302-6767-11e7-98c6-1e2d3da416dc.png)

**Comment by wf9a5m75** [comment] 2017-07-13 05:23
You said you execute `direction.route()` repeatedly.
So, you should get the result of `direction.route()` at least couple of times.
Please share them with JSON format, not screen capture.

**Comment by wuilmerj24** [comment] 2017-07-13 05:37
okay

**Comment by wuilmerj24** [comment] 2017-07-13 05:44
@wf9a5m75  so?
[{"bounds":{"south":27.88182,"west":-82.24334,"north":27.881990000000002,"east":-82.24042},"copyrights":"Datos de mapas ©2017 Google","legs":[{"distance":{"text":"0,2 mi","value":293},"duration":{"text":"1 min","value":55},"end_address":"2314 Kenwick Dr, Valrico, FL 33596, EE. UU.","end_location":{"lat":27.8819743,"lng":-82.2433385},"start_address":"2414-2416 Kenwick Dr, Valrico, FL 33596, EE. UU.","start_location":{"lat":27.8818154,"lng":-82.24041890000001},"steps":[{"distance":{"text":"0,2 mi","value":293},"duration":{"text":"1 min","value":55},"end_location":{"lat":27.8819743,"lng":-82.2433385},"polyline":{"points":"ktdiDrq}tNCDORITC^?|@?jCBlH"},"start_location":{"lat":27.8818154,"lng":-82.24041890000001},"travel_mode":"DRIVING","encoded_lat_lngs":"ktdiDrq}tNCDORITC^?|@?jCBlH","path":[{"lat":27.88182,"lng":-82.24042},{"lat":27.881840000000004,"lng":-82.24045000000001},{"lat":27.88192,"lng":-82.24055000000001},{"lat":27.881970000000003,"lng":-82.24066},{"lat":27.881990000000002,"lng":-82.24082000000001},{"lat":27.881990000000002,"lng":-82.24113000000001},{"lat":27.881990000000002,"lng":-82.24183000000001},{"lat":27.881970000000003,"lng":-82.24334}],"lat_lngs":[{"lat":27.88182,"lng":-82.24042},{"lat":27.881840000000004,"lng":-82.24045000000001},{"lat":27.88192,"lng":-82.24055000000001},{"lat":27.881970000000003,"lng":-82.24066},{"lat":27.881990000000002,"lng":-82.24082000000001},{"lat":27.881990000000002,"lng":-82.24113000000001},{"lat":27.881990000000002,"lng":-82.24183000000001},{"lat":27.881970000000003,"lng":-82.24334}],"instructions":"Dirígete hacia el <b>noroeste</b> en <b>Kenwick Dr</b> hacia <b>Needham Dr</b><div style=\"font-size:0.9em\">El destino está a la derecha.</div>","maneuver":"","start_point":{"lat":27.8818154,"lng":-82.24041890000001},"end_point":{"lat":27.8819743,"lng":-82.2433385}}],"traffic_speed_entry":[],"via_waypoint":[],"via_waypoints":[]}],"overview_polyline":"ktdiDrq}tNSXITC^?hEBlH","summary":"Kenwick Dr","warnings":[],"waypoint_order":[],"overview_path":[{"lat":27.88182,"lng":-82.24042},{"lat":27.88192,"lng":-82.24055000000001},{"lat":27.881970000000003,"lng":-82.24066},{"lat":27.881990000000002,"lng":-82.24082000000001},{"lat":27.881990000000002,"lng":-82.24183000000001},{"lat":27.881970000000003,"lng":-82.24334}]}]

**Comment by wf9a5m75** [comment] 2017-07-13 05:48
Is this the result of the first time?

**Comment by wuilmerj24** [comment] 2017-07-13 05:49
@wf9a5m75  do not. That is the result of the interval

**Comment by wf9a5m75** [comment] 2017-07-13 05:51
I need all results, first, second, third ...N
And I also need to know which times polygon is disappeared.

**Comment by wf9a5m75** [comment] 2017-07-13 05:55
What I want to do is `reproduce your issue with your data` using similar code.

```js
var data = [
   {result of the first time},
   {result of the second time},
   {result of the third time},
   ...
   N
];

map.addPolyline({
   ...
   points : data[0]
}, function(polyline) {
   var idx = 0;
   var timer = setInterval(function() {
       idx++;
       polyline.setPoints(data[idx]);
       if (idx == data.length) {
          clearInterval(timer);
       }
   }, 5000);  //maybe 5 sec in your code?
});
```

**Comment by wuilmerj24** [comment] 2017-07-13 05:55
The polyline appears the first time, after the call to the update function removes the polyline. That result is like the number 15, since I have left it for quite some time and nothing.

**Comment by wf9a5m75** [comment] 2017-07-13 06:05
So without valuable data or way is provided, how can I reproduce your issue?

> after the call to the update function removes the polyline.

I ask what data did you set?

**Comment by wuilmerj24** [comment] 2017-07-13 06:10
I've this
This.mapa.addPolyline ({
              'Points': this points,
              'Color': '# 3e6372',
              'Width': 4,
              'Geodesic': true
            }, Function (polylinea) {
The polyline was correctly drawn this.updatePolylinea (polyline);
            });

UpdatePolyline (polyline) {
After doing
This.puntos = result google maps directions.route
Polilinea.setPoints (this.puntos);
Here the polyline is already eliminated
}

**Comment by wf9a5m75** [comment] 2017-07-13 06:13
No, no ... :(

I ask `data`. It means

```js
This.mapa.addPolyline ({
  'Points': this points,    <------- What points this variable have?
  ..
}, Function (polylinea) {
    
});

Polilinea.setPoints (this.puntos);      <------- What points this variable have?

```

**Comment by wf9a5m75** [comment] 2017-07-13 06:15
Please tell me the result of `console.log(this.points)`,  and `console.log(this.puntos)` when the polyline was disappeared.

**Comment by wuilmerj24** [comment] 2017-07-13 06:18
okay

**Comment by wuilmerj24** [comment] 2017-07-13 06:38
The me is a problem that presents ionic with the scope of the variable this

**Comment by wf9a5m75** [comment] 2017-07-13 06:45
Hey, I don't develop your code.... :(
`me` or `this`? I don't know....

**Comment by wuilmerj24** [comment] 2017-07-13 06:48
In some cases I have to declare a variable inside the function because with this it does not work. Says undefined.

**Comment by wuilmerj24** [comment] 2017-07-13 06:52
this.puntos [{"lat":27.88182,"lng":-82.24042},{"lat":27.881840000000004,"lng":-82.24045000000001},{"lat":27.88192,"lng":-82.24055000000001},{"lat":27.881970000000003,"lng":-82.24066},{"lat":27.881990000000002,"lng":-82.24082000000001},{"lat":27.881990000000002,"lng":-82.24113000000001},{"lat":27.881990000000002,"lng":-82.24183000000001},{"lat":27.881970000000003,"lng":-82.24334}]

**Comment by wf9a5m75** [comment] 2017-07-13 06:56
Does `puntos` points that are disappear the polyline?

**Comment by wuilmerj24** [comment] 2017-07-13 07:10
I use the same variable. Just before filling the clean again.

**Comment by wf9a5m75** [comment] 2017-07-13 17:36
Since you didn't give me enough data set, I can not try to reproduce your issue.

In that case, please share your project files on github or bitbucket. I will check your project files.
(only check)

How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by wuilmerj24** [comment] 2017-07-13 20:57
Or what do you recommend that I do?

**Comment by wf9a5m75** [comment] 2017-07-13 21:00
Since you did not give me enough data set, I can not give you any advice at this time.

**Comment by wuilmerj24** [comment] 2017-07-14 01:08
Ah OK I understand. But in the syntax is fine for the update of the polyline? And what data do you need?

**Comment by wf9a5m75** [comment] 2017-07-14 01:41
Your code syntax **looks** ok.

The necessary data (point of list) is `startPoints` and `updatePoints`.

```js
This.mapa.addPolyline ({
  'points': startPoints,    <------- What points this variable contains?
  ..
}, Function (polylinea) {
    
});

Polilinea.setPoints( updatePoints );      <------- What points this variable contains?
```

**Comment by wuilmerj24** [comment] 2017-07-14 02:45
@wf9a5m75  StarPoints contains the path between 2 points, starting point are the coordinates that are hosted in the database and the end point are of the device.
UpdatePoints stores the new location of start point and endpoint
Is an app similar to uber I am developing part of the client.

**Comment by wf9a5m75** [comment] 2017-07-14 03:11
I already understand about your app.
But I want to know the real data. 

For example, `StarPoints contains the path between 2 points`, so please tell me the exact point list.

**Comment by wf9a5m75** [comment] 2017-07-14 03:13
I already repeated the same thing again and again.
If you don't give me the exact data, I will close this issue because there is no enough data.

**Comment by wuilmerj24** [comment] 2017-07-14 03:18
Friend does not understand itself that requires with the starting point.

**Comment by wf9a5m75** [comment] 2017-07-14 03:19
Very simple question.

```js
This.mapa.addPolyline ({
  'points': startPoints,    <------- What points this variable contains?
  ..
}
```

It should not only one point.

**Comment by wf9a5m75** [comment] 2017-07-14 03:22
The expected answer is like this.

```js
startPoints = [
   {lat : ..., lng: ...},
   {lat : ..., lng: ...},
   {lat : ..., lng: ...},
   ....
   {lat : ..., lng: ...}
];
```

**Comment by wf9a5m75** [comment] 2017-07-14 03:24
I'm not interested in your physical location at all. You can start with dummy location.

But the most important thing is **the points when the polyline is disappeared**. That's all.

**Comment by wf9a5m75** [comment] 2017-07-14 03:30
Can you understand what I'm asking?

**Comment by wuilmerj24** [comment] 2017-07-14 03:35
@wf9a5m75 The update of the points between the location of the device and the coordinates that are in the cloud I do in the function called updatePolyline, after doing the query I do polilinea.setPoints (this.puntos)

**Comment by wf9a5m75** [comment] 2017-07-14 03:36
:(

**Comment by wf9a5m75** [comment] 2017-07-14 03:39
```js
polilinea.setPoints (this.puntos)
```

I want to know the exact data of `this.puntos`.........

I think this is really depends on the data what you set.

Unfortunately, I'm really really really so busy. So I don't want to spend my time to test.
That's why I'm asking to prepare data.

**Comment by wuilmerj24** [comment] 2017-07-14 04:02
@wf9a5m75 I understand my friend. Good friend already verify that the array is filled correctly to update the polyline.

**Comment by wf9a5m75** [comment] 2017-07-14 05:12
Last time. If you provide the point of array you (your friend?) to draw the polyline, I will test with them. No provide them, I will close this issue.
No data, no code, can not help.

**Comment by wuilmerj24** [comment] 2017-07-16 21:29
@wf9a5m75 Hi. Sorry for the delay but I'm doing some tests to give more details about this problem. The proof that I am doing is the following. Step 2 latLng a setPPoints of an already created polyline. My question is a question. Should it appear in a new moth or modify the existing moth?

**Comment by wf9a5m75** [comment] 2017-07-16 21:42
What do you mean `moth`? A bug?

**Comment by wuilmerj24** [comment] 2017-07-18 22:40
@wf9a5m75 Sorry friend give me chance for this weekend that I'm ful of work. But the end I connect and comment all the information

**Comment by wf9a5m75** [comment] 2017-07-18 22:45
Ok.

**Comment by wf9a5m75** [comment] 2017-07-20 02:01
I updated the code of polyline and polygon in order to update ensure. Please reinstall the plugin and try it.

**Comment by wf9a5m75** [comment] 2017-07-22 14:48
ping

**Comment by wf9a5m75** [comment] 2017-07-25 19:56
Since there is no update, and I also updated plugin code, I close this issue.
The problem should not occur.

**Closed by wf9a5m75** 2017-07-25 19:56 UTC
Labels: fixed
