### ISSUE TITLE
remove specified marker

### ISSUE THREAD

**Issue by tuanvuf4** [mapsplugin/cordova-plugin-googlemaps#1977] opened 2018-01-05 04:47 UTC
How can i remove marker that it was added ?
example: i added 10 markers, then i want to remove 1 marker after reload data
this.map.addMarker(markerOption) => this way just add marker on map.
And I try to create new marker instance but i faced a error : "_this._objectInstance.on is not a function"
let marker = new Marker(this.map, markerOption);
How can i resolve this problem ?

**Comment by wf9a5m75** [comment] 2018-01-05 05:03
Please share your project files on GitHub. I will check it.

**Comment by tuanvuf4** [comment] 2018-01-05 07:46
hmm. this is outsource project so i dont have permission

**Comment by wf9a5m75** [comment] 2018-01-05 15:12
In that case, please create a demo project that reproduce your issue 100%, then share it. Otherwise please debug by yourself.

**Comment by wf9a5m75** [comment] 2018-01-08 17:40
ping

**Comment by wf9a5m75** [comment] 2018-01-09 00:34
Since there is no update for a while, I close this thread.

**Closed by wf9a5m75** 2018-01-09 00:34 UTC
Labels: need more information

**Comment by tuanvuf4** [comment] 2018-01-09 04:31
I see setMap() method in google map api for web
https://developers.google.com/maps/documentation/javascript/examples/marker-remove
which method in our plugin work like that ?

**Comment by wf9a5m75** [comment] 2018-01-09 05:42
This plugin does not use the Google Maps API v3

**Comment by wf9a5m75** [comment] 2018-01-09 05:43
All documents are here.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by tuanvuf4** [comment] 2018-01-11 08:15
How can i create Marker instance ?
let marker = new Marker(this.map, {}); -> this cause an error _this._objectInstance.on is not a function

**Comment by wf9a5m75** [comment] 2018-01-11 17:06
Could you ask after more reading documents?
https://docs.google.com/presentation/d/1zlkmoSY4AzDJc_P4IqWLnzct41IqHyzGkLeyhlAxMDE/edit#slide=id.p
