### ISSUE TITLE
Infowindow is lost after setIcon

### ISSUE THREAD

**Issue by karlkilgi** [mapsplugin/cordova-plugin-googlemaps#707] opened 2015-10-30 08:03 UTC
Infowindow is not showing when using setIcon and showInfoWindow together.
Infowindow only flickers and then is lost when icon changes.
   
```javascript

$scope.map.addMarker({
    position: latlng,
    icon: 'www/img/icon_small.png',
    title: 'Info'
}, function (marker) {
    marker.addEventListener(plugin.google.maps.event.MARKER_CLICK, function () {
       $scope.showOnMap(marker);
    });
});

$scope.showOnMap = function (marker) {
    marker.setIcon({
        'url': 'www/img/icon_big.png'
    });
    marker.showInfoWindow();
```

Was working in version 1.2.4.

**Comment by Hirbod** [comment] 2015-10-30 08:06
Why you add a click listener inside the click callback?
Forget about the callback function, just do it like that

```js
$scope.map.addMarker({
    position: latlng,
    icon: 'www/img/icon_small.png',
    title: 'Info',
    markerClick: $scope.showOnMap
});
```

**Comment by karlkilgi** [comment] 2015-10-30 08:33
Yes, it is a nicer way of doing that. But it has no effect of showing the infoWindow correctly after setIcon.

**Comment by karlkilgi** [comment] 2015-11-06 09:27
Was working in version 1.2.4 and broken in 1.2.5. I'm currently using 1.3.4.

**Comment by Richacinas** [comment] 2015-11-10 15:57
I am currently having the same issue. Just trying to do a simple marker.showInfoWindow() in the callback function doesn't work.

I can see that marker comes empty.

**Comment by Hirbod** [comment] 2015-11-10 16:27
iOS/Android ? Both?

**Comment by Richacinas** [comment] 2015-11-10 16:43
IOS at the moment. 

    map.addMarker({
                            'position': location,
                            'draggable': false,
                            'flat': true,
                            'title': value.NOMBRE,
                            'type' : value.ESTADO,
                            'id' : value.ID,
                            'artista' : value.ARTISTA,
                            'icon': iconColor
                        }, function(marker) {
                            

                            marker.addEventListener( plugin.google.maps.event.MARKER_CLICK, function() {
                                marker.showInfoWindow();
    }
    });
    });

**Comment by Richacinas** [comment] 2015-11-10 16:50
Alright. I did some more testing and see that it shows the info windows, but this is the default behaviour which by the way I would like to disable.

This is actually what I'm trying to do:

    marker.addEventListener( plugin.google.maps.event.MARKER_CLICK, function() {
        $rootScope.obra = marker;
        window.location.href = "#/obra";
    }

And I can't get the value of marker inside the function so, later on, in the obraController (AngularJS) the value of $rootScope.obra is an empty object.

**Comment by Hirbod** [comment] 2015-11-10 16:51
Did you try `this, or pass `function(marker)`to the function ?

**Comment by Richacinas** [comment] 2015-11-10 17:04
Yes I did.

I added these 3 alert to the function so I could see if something comes, but everything is empty:

    marker.addEventListener( plugin.google.maps.event.MARKER_CLICK, function(element) {
        alert( JSON.stringify(element) );
        alert( JSON.stringify(this) );
        alert( JSON.stringify(event) );
        $rootScope.obra = marker;
        window.location.href = "#/obra";
    }

The only one that brings "something" is event. It comes with:
     {
         "mydata": [{}],
         "myself": {}
     }

**Comment by Richacinas** [comment] 2015-11-10 17:19
Just in case it helps:

this is wrapped inside an angular.forEach loop:

    angular.forEach(array, function(value, key) { 
                    if (key !== 'datos') {

                        var iconColor = $rootScope.pines[ value.ESTADO];
                        var location = new plugin.google.maps.LatLng( Number(value.latitud), Number(value.longitud) );

                        map.addMarker({
                            'position': location,
                            'draggable': false,
                            'flat': true,
                            'title': value.NOMBRE,
                            'type' : value.ESTADO,
                            'id' : value.ID,
                            'artista' : value.ARTISTA,
                            'icon': iconColor
                            //markerClick: markerHandler
                        }, function(marker) {
                            
                            marker.addEventListener( plugin.google.maps.event.MARKER_CLICK, function(element) {

                                alert( JSON.stringify(element) );
                                alert( JSON.stringify(this) );
                                alert( JSON.stringify(event) );

                                $rootScope.obra = marker;
                                window.location.href = "#/obra"
                                
                            });

                            if(value.ESTADO === "V"){
                                $rootScope.markersVivas.push(marker)
                            } else {
                                $rootScope.markersMuertas.push(marker);
                            }
                        });
                    }

                    });

It should change anything because this is a synchronous operation (angular.forEach) so I can't really figure out what the problem is here.

The markers are being displayed on the map, and they seem to have the proper data stored because when I click on one of them, the map center goes to this marker and I can see the info window containing the title property.

Thanks so much

**Comment by Hirbod** [comment] 2015-11-10 17:21
You could try to to wrap the event listener inside of a closure, or bind this to it

```js
                        marker.addEventListener( plugin.google.maps.event.MARKER_CLICK, function(element) {

                            alert( JSON.stringify(element) );
                            alert( JSON.stringify(this) );
                            alert( JSON.stringify(event) );

                            $rootScope.obra = marker;
                            window.location.href = "#/obra"

                        }.bind(this)); // or bind(marker)
```

or wrap the function inside of a closure
http://stackoverflow.com/questions/111102/how-do-javascript-closures-work

**Comment by Richacinas** [comment] 2015-11-10 18:09
But, why is element coming as an empty object?
Even if I bind this value, everything is empty.

**Comment by Richacinas** [comment] 2015-11-11 10:54
I created a REALLY simple and empty CORDOVA project to test the plugin without any other "distraction" or possible source of error.

Here is my deviceReady handler:

    onDeviceReady: function() {

        // Define a div tag with id="map_canvas"
        var mapDiv = document.getElementById("map_canvas");

        // Initialize the map plugin
        var map = plugin.google.maps.Map.getMap(mapDiv);

        // You have to wait the MAP_READY event.
        map.on(plugin.google.maps.event.MAP_READY, onMapInit);

        function onMapInit(map) {

            map.addMarker({
              'position': new plugin.google.maps.LatLng(0, 0),
              'title': ["Hello Google Map for", "Cordova!"].join("\n"),
              'snippet': "This plugin is awesome!"
            }, function(marker) {

              marker.showInfoWindow();
              alert( JSON.stringify(marker));

            });
        }
        },

And I still see the alert throwing an empty object. The callback function is not bringing anything.

**Comment by Richacinas** [comment] 2015-11-12 12:50
Finally I found out that marker comes with information.

So, I could access any property through marker.blabla or marker.get('blablabla')

The only problem is that JSON.stringify doesn't show anything, just an empty object which is weird. I'm sure somebody will have the answer for this behaviour.

**Comment by Hirbod** [comment] 2015-11-15 23:22
`marker` is an real object, it's not a JSON - therefore it can't be converted into a string. My bad, I did not recognize this while reading your code. Yeah, you need to use `.get()` to grab the informations the marker holds.

You could also use
```js
map.addMarker({
  params: {
     value1: "foo",
     value2: "bar"
  },
  ...
  ...
})
```

and grab the informations with `marker.getParams()` (JSON.stringify on this would work)

It's actually the same like getting single keys, but when you store everything inside of the params object, you could be more flexible.

So you found a working solution, hopefully this will also work for @karlkilgi 

I'm going to close this one here now!

**Comment by karlkilgi** [comment] 2015-11-16 09:31
@Hirbod i don't understand where is the working solution. Problem is that when setIcon is called, showInfoWindow does not work anymore.

Following code is not working, infowindow is not showing or flickers only a fraction:
```javascript
$scope.map.addMarker({
    position: latlng,
    icon: 'www/img/icon_small.png',
    title: 'Info',
    markerClick: function (marker) {
        $scope.showOnMap(marker);
    }
});

$scope.showOnMap = function (marker) {
    marker.setIcon({
        'url': 'www/img/icon_big.png'
    });
    marker.showInfoWindow();
});
```

Without setIcon, showInfoWindow works correctly (info window is showing).
```javascript
$scope.map.addMarker({
    position: latlng,
    icon: 'www/img/icon_small.png',
    title: 'Info',
    markerClick: function (marker) {
        $scope.showOnMap(marker);
    }
});

$scope.showOnMap = function (marker) {
    marker.showInfoWindow();
});
```

**Comment by Hirbod** [comment] 2015-11-17 08:27
Which OS? @karlkilgi

**Comment by Hirbod** [comment] 2015-11-17 08:31
And could you try a marker.setTitle('test') one line before you call showInfoWindow? Looks like the title will be deleted and therefore no infoWindow

**Comment by Hirbod** [comment] 2015-11-17 08:46
From what I see here (iOS)
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/dd87c6ac58b76f1e49e8337f6ff4e43bb1aee927/src/ios/GoogleMaps/Marker.m#L422

the whole icon property of that marker will be overwritten when calling setIcon. I can't imagine that this worked ever before. I'm sure, calling 

setIcon({
   url: {...},
   title: marker.get('title')
})

Should work as a temp-fix, till I've investigated more

**Comment by karlkilgi** [comment] 2015-11-17 09:09
Bug is in both - ios&android and it worked in 1.2.4 version. Something went wrong in 1.2.4 -> 1.2.5 update.

I have tried 
```javascript
    marker.setIcon({
        'url': 'www/img/icon_big.png'
    });
    marker.setTitle("title");
    marker.showInfoWindow();
```

but it does not work. 

I tried setIcon together with title, but it's not working either.
 
```javascript
setIcon({
url: 'www/img/icon_big.png',
title: "Title"
})
```

**Comment by githubkyo** [comment] 2015-11-17 10:30
You can fix it like this
$timeout(function () {
marker.showInfoWindow();
},50);

**Comment by githubkyo** [comment] 2015-11-17 10:31
I think  it is  a  bug.

**Comment by Hirbod** [comment] 2015-11-28 05:41
@karlkilgi can you confirm @githubkyo "workaround" ?

**Comment by karlkilgi** [comment] 2015-12-08 13:19
It kind of works. But sometimes, when the setIcon takes too much time, it does not (phone lags and setIcon is finished later than showInfoWindow). 

Increasing the timeout value will make it safer, but it doesn't guarantee that it will work every time on slower phones. Therefore i would not consider this as a workaround. Why did you close this issue? is it resolved in 1.3.5?

**Comment by kwiateusz** [comment] 2016-01-08 14:44
Problem is still present and it's annooying

**Comment by Hirbod** [comment] 2016-01-08 18:09
So please fix it and provide a PR

**Comment by Hirbod** [comment] 2016-03-29 18:18
@wf9a5m75 tried to dig into this some while ago, any ideas? I will reopen that

**Comment by wf9a5m75** [comment] 2016-03-29 18:52
@Hirbod did you reproduce this issue?

**Comment by Hirbod** [comment] 2016-03-29 19:24
yes

**Closed** 2016-04-05 01:13 UTC
Labels: bug

**Comment by wf9a5m75** [comment] 2016-04-05 01:24
![issue_707](https://cloud.githubusercontent.com/assets/167831/14268657/624caad2-fa92-11e5-9af5-ed8d0ab5cd1c.gif)


```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <script type="text/javascript" src="cordova.js"></script>
      <script type="text/javascript">
        var map;

        document.addEventListener("deviceready", function() {
          var div = document.getElementById("map_canvas");


          // Initialize the map view
          var position = {lat: 35.432656, lng: 139.616858};
          map = plugin.google.maps.Map.getMap(div, {
            camera: {
              target: position,
              zoom: 15
            }
          });

          // Wait until the map is ready status.
          map.addEventListener(plugin.google.maps.event.MAP_READY, function() {
            map.addMarker({
              position: position,
              title: "test",
              icon: "https://iai-dojo.jp/modules/dojo/img/flag9.gif"
            }, function(marker) {
              marker.showInfoWindow();
              setTimeout(function() {
                marker.setIcon({
                  'url': "https://iai-dojo.jp/modules/dojo/img/flag15over.gif"
                })
              }, 3000);
            });
          });
        }, false);


      </script>
      </head>
  <body>
    <h3>PhoneGap-GoogleMaps-Plugin</h3>
    <div style="width:100%;height:500px" id="map_canvas"></div>
  </body>
</html>
```
