### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined     at Map.<anonymous> (Map.js:1330)

### ISSUE THREAD

**Issue by lekidybeloha** [mapsplugin/cordova-plugin-googlemaps#1911] opened 2017-11-23 07:58 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[* ] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[* ] **Android**
[ ] **iOS**

**Comment by wf9a5m75** [comment] 2017-11-23 08:30
Please provide more information. At least you should share your project files on GitHub.

**Comment by lekidybeloha** [comment] 2017-11-23 10:07
Sorry for my bad english,  but when i Call the fucntion map.addMarker, the application bug. Here my js code : 
var map;
    var adr;
    document.addEventListener("deviceready", function() {
      var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    }, false);

    function onBackKeyDown() {
      window.location.href = 'kid.html'; 
    }

    function onMapReady() {
        var options = {
      enableHighAccuracy: true
      //maximumAge: 3600000
   }
   var watchID = navigator.geolocation.getCurrentPosition(onSuccess, onError, options);

   function onSuccess(position) {
    console.log(position);
    map.animateCamera({
    target: {lat: position.coords.latitude, lng: position.coords.longitude},
    zoom: 17,
    tilt: 60,
    bearing: 140,
    duration: 3000
  }, function() {

    // Add a maker
    map.addMarker({
      position: {lat: position.coords.latitude, lng: position.coords.longitude},
      title: "Vous êtes ici",
      snippet: "",
      animation: plugin.google.maps.Animation.BOUNCE
    }, function(marker) {

      // Show the info window
      // Latitude, longitude -> address
        plugin.google.maps.Geocoder.geocode({
          "position": {lat: position.coords.latitude, lng: position.coords.longitude}
        }, function(results) {

          if (results.length === 0) {
            // Not found
            alert('no location');
            return;
          }

          var address = [
            results[0].subThoroughfare || "",
            results[0].thoroughfare || "",
            results[0].locality || "",
            results[0].adminArea || "",
            results[0].postalCode || "",
            results[0].country || ""].join(", ");
          marker.setTitle(address)
                .showInfoWindow();
        });
    });
  });
   };

   function onError(error) {
      alert('code: '    + error.code    + '\n' + 'message: ' + error.message + '\n');
   }
      // Move to the position with animation
  
    }



But I get this error on map.addMarker : Uncaught TypeError: Cannot read property 'id' of undefined at Map.<anonymous> (Map.js:1330)

And thank you for reply me so fast

**Comment by wf9a5m75** [comment] 2017-11-23 13:57
And what version do you use? (`$> cordova plugin list`)

**Comment by lekidybeloha** [comment] 2017-11-23 20:49
I used this version : 2.1.1, note that the plugins works pefectly last week, but i've just want to update a feature for my application, and I've got this error. I don't now why

**Comment by wf9a5m75** [comment] 2017-11-23 21:01
Is the above code **exactly the same as your project code**?

**Comment by wf9a5m75** [comment] 2017-11-23 21:21
Looks like, the code should be fine. Possible problem is 
```
{lat: position.coords.latitude, lng: position.coords.longitude}
```
are incorrect values

**Comment by wf9a5m75** [comment] 2017-11-23 21:22
Use `map.getMyLocation()` instead of `navigator.geolocation.getCurrentPosition`

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/Map/getMyLocation/README.md

**Comment by lekidybeloha** [comment] 2017-11-24 04:33
Yes, the code above are exactly the same as in my project. Ok, I'll try this

**Comment by wf9a5m75** [comment] 2017-11-25 23:42
ping

**Comment by wf9a5m75** [comment] 2017-11-26 15:56
Since there is no update, and I could not reproduce your issue, I close this thread.
But you can reply anytime with new information.

**Closed by wf9a5m75** 2017-11-26 15:56 UTC
