### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by bigbossmaher** [mapsplugin/cordova-plugin-googlemaps#1876] opened 2017-11-12 21:33 UTC
i suppose that all markers are in this variable : parking_Markers
how can i change a marker icon (  that have a specific titl )  with for loop

**Comment by wf9a5m75** [comment] 2017-11-12 22:24
marker.setIcon()

**Comment by bigbossmaher** [comment] 2017-11-12 22:30
i konw this , but how to make the loop

**Comment by wf9a5m75** [comment] 2017-11-13 00:56
Just loop with the for statement, or use BaseArrayClass.

Did you find the document pages? 

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/forEach/README.md

**Comment by wf9a5m75** [comment] 2017-11-13 07:12
So how did you try by yourself?

**Comment by bigbossmaher** [comment] 2017-11-13 11:04
I'm a javascript beginner, can you please give me the code directly, and i will be very thankful

**Comment by wf9a5m75** [comment] 2017-11-13 16:05
Please study JavaScript first.
https://www.w3schools.com/js/js_loop_for.asp

**Comment by bigbossmaher** [comment] 2017-11-13 16:55
Yes i know this, but i could not implement in this situation

**Comment by wf9a5m75** [comment] 2017-11-13 17:07
So how did you implement? Please show me your code.
The important thing is to resolve this (easy) situation by yourself.

**Comment by wf9a5m75** [comment] 2017-11-13 23:03
ping

**Comment by bigbossmaher** [comment] 2017-11-13 23:04
Sorry , i can't find any solution , can you help me ?

**Comment by wf9a5m75** [comment] 2017-11-13 23:05
So how did you write your code? I haven't seen your code anything. So how can I help you?

**Comment by wf9a5m75** [comment] 2017-11-13 23:08
Please share your project files on github. Then I will check your code.

**Comment by bigbossmaher** [comment] 2017-11-13 23:10
i suppose that all markers are in this variable : parking_Markers
I want simply to show all title of markers
How exacly

**Comment by wf9a5m75** [comment] 2017-11-13 23:11
This plugin (native APIs) is able to display only one InfoWindow.
If you don't want to share your code, I can not help you further. Because too less information.

**Comment by bigbossmaher** [comment] 2017-11-13 23:14
It is so simple
I want some thing like this 
For ( i==0;i<markers.length;i++){
       alert(Markers[i].getTitle());
}

**Comment by wf9a5m75** [comment] 2017-11-13 23:16
Do you want to display 10 alerts?

**Comment by bigbossmaher** [comment] 2017-11-13 23:18
Just i want to code that make this and i will modify it

**Comment by bigbossmaher** [comment] 2017-11-13 23:18
Just to make to. Make you understand my situation

**Comment by wf9a5m75** [comment] 2017-11-13 23:25
If you manage the marker instances correctly, your code should work
```
For ( i==0;i<markers.length;i++){
alert(Markers[i].getTitle());
}
```

If it doesn't work, your code is wrong in somewhere.

**Comment by wf9a5m75** [comment] 2017-11-14 17:20
ping

**Comment by bigbossmaher** [comment] 2017-11-15 01:02
i get unlimited undifined alert windows
and this in console
11-15 01:00:43.779 21874-21908/com.parking.tunisie D/EGL_emulation: eglMakeCurrent: 0x93246c80: ver 2 0 (tinfo 0xa1a1f200)
this is the code i used
    for( i=0;i<parking_Markers.length;i++){
        alert(parking_Markers[i].getTitle());
    }

the app is working and markers are showed on the map

**Comment by wf9a5m75** [comment] 2017-11-15 01:43
>i get unlimited undifined alert windows

Yes, I think so.
Your code is the same as this.

```js
for (var i = 0; i < 10; i++) {
  alert(i);
}
```

**Comment by bigbossmaher** [comment] 2017-11-15 01:44
You told me that it will work :flushed:

**Comment by wf9a5m75** [comment] 2017-11-15 01:45
Yes. It worked, isn't it?

**Comment by wf9a5m75** [comment] 2017-11-15 01:47
I haven't seen your code overall, so I can not give proper advices.

For example, I don't know how you put marker instances into the `parking_Markers` variable.

That's why I asked `Please share your project files on github. Then I will check your code.`

**Comment by wf9a5m75** [comment] 2017-11-15 01:57
If you don't know how to share your project files on github, read here.
https://guides.github.com/activities/hello-world/

**Comment by bigbossmaher** [comment] 2017-11-15 02:00
this is what you sent me in another ticket .
You need to manage marker instances by yourself.

For example,

var _globalMarkerList = [];
...

map.addMarker({
   ...
}, function(marker) {
    _globalMarkerList.push(marker);
});


function removeLastMarker() {
   var lastMarker =  _globalMarkerList.pop();
   if (lastMarker) {
      lastMarker.remove();
   }   
}

**Comment by bigbossmaher** [comment] 2017-11-15 02:00
And i used this method

**Comment by wf9a5m75** [comment] 2017-11-15 02:08
Try this.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/constructor/README.md

**Comment by wf9a5m75** [comment] 2017-11-15 22:04
Did you solve this?

**Comment by bigbossmaher** [comment] 2017-11-16 16:43
just give me 1 day :)
thanks

**Comment by wf9a5m75** [comment] 2017-11-16 17:09
Of course.

**Comment by bigbossmaher** [comment] 2017-11-18 00:33
var positionList = new plugin.google.maps.BaseArrayClass(parking_Markers);

    positionList.map(function() {

    }, function(markers) {
        alert(markers[0].getTitle());
    });

    });

and it is not working , should i upload to git ?

**Comment by wf9a5m75** [comment] 2017-11-18 00:42
>should i upload to git the full project?

Yes! (I repeated so many times)

If no, I don't help you anymore. Because you are rude for me. Hiding your information, and spending my private times a lot.

**Comment by bigbossmaher** [comment] 2017-11-18 00:50
i'm very sorry ,  i just work as full time , and i develop my app in the night , now it it 2 AM . i will upload it ASAP
and sorry again

**Comment by wf9a5m75** [comment] 2017-11-18 00:54
Understand, but that's why I asked to share your code on github. I can check your code while you are sleeping.

**Comment by bigbossmaher** [comment] 2017-11-19 02:08
the full project is uploaded here
https://github.com/bigbossmaher/Parking2017
but the most important things are here in the JS file
https://github.com/bigbossmaher/Parking2017/blob/master/www/js/my-app.js ( line 782 is for creating markers )

my question is how can i access to markers data like titles etc , and show them in loop for exemple.
thnaks a lot for your effort

**Comment by wf9a5m75** [comment] 2017-11-19 04:39
Thank you for sharing the code.

And this plugin keeps own properties you set when you create a marker.
For example, if you want to hold "store_id", you can do this.

```js
map.addMarker({
   'position': {
     lat: storedData.lat,
     lng: storedData.lng
   },
   'title': "Votre Voiture est ici",
   'icon' : 'www/icons/car.png',
   'animation': plugin.google.maps.Animation.DROP,
   'store_id' : "store_38"  // <--- set your own property
}, function(marker) {

  marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
    alert(marker.get('store_id'));
  });
});
```

Marker class extends [BaseClass](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseClass/README.md). The BaseClass has [set() and get()](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseClass/get_set/README.md) methods. 
You can set your data, and get it anytime.

```js
marker.set("store_id", "store_32");
var store_id = marker.get("store_id");
```

------

In your code, you hold the marker instances in `position_mark_car` variable.
So, you can access the marker data like this.

```js
position_mark_car.forEach(function(marker) {
  console.log(marker.get("store_id"));
});
```

If you want to get all values of all markers, you can use [Array.map()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

```js
var store_ids = position_mark_car.forEach(function(marker) {
  return marker.get("store_id");
});
```

**Comment by bigbossmaher** [comment] 2017-11-19 23:42
i'm very thankful , but i can't manage icons using own properties. may be i should explain to you what i want to do exacly.
this is an app for parking. it shows all parkings in tunisia . each marker

 should show how much  is filled ( 0 / 25 / 50 / 75 / 100% ) , and i used 5 icons each icon for specific pourcentage.
![parking75](https://user-images.githubusercontent.com/15154710/32997052-3dd18f92-cd8b-11e7-932b-d35507103940.png)
![parking100](https://user-images.githubusercontent.com/15154710/32997053-3df1da68-cd8b-11e7-9db8-816b50c35a2e.png)

as you know the pourcentage is changing , so every 30 i'm getting the new values , and i should change the icons to fit the new value.
my current solutions is to clear all markers and recreate them with the new icons . and is see it too a lot of memory . 
i'm looking for a solution like going throw each marker and change it icon only if he has a diferent icon.
thnaks

**Comment by wf9a5m75** [comment] 2017-11-20 00:06
Is that all information? No more hiding information?

**Comment by bigbossmaher** [comment] 2017-11-20 00:09
yes this is all infromations :)

**Comment by bigbossmaher** [comment] 2017-11-20 00:11
i want to create a seperate function that will execute each 30 seconds and go throw each marker , and change the icon if the parking pourcentage is changed.

**Comment by wf9a5m75** [comment] 2017-11-20 00:19
Ok, I will show you the example code later.
But you should explain like above from the first. Then we could save lots of time and stressful.

**Time is money**

This is common idiom in world wide.
You should consider how you can save the time of other person who you ask your question.

-----

During the waiting time, please read this page deeply, and understand as much as possible.
If you have some questions, post here.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseClass/get_set/README.md

**Comment by bigbossmaher** [comment] 2017-11-20 00:42
yes , i will read it , and thanks for your time and your tips.

**Comment by wf9a5m75** [comment] 2017-11-21 00:16
@bigbossmaher Please give me the `write` permission. I will commit the fixed & cleaned-up code on a new branch.

**Comment by wf9a5m75** [comment] 2017-11-21 01:03
I changed your code (a lot).
There are many things I advice to you, but I only explain the logic of marker update at here.

-----------

Your logic:

1. Get parking list from your server
2. then add markers (`addMarkers() function`) onto the map.
3. After that, remove the markers after 15 sec, then go back to step 1.

------------

The problem is `cost of adding marker`. Adding markers / removing markers takes time, and use memory.
So key point is **to update only changed parking lots**.

In your code, the `etat_actuelle` field contains the usage percent of the packing lot.
Other fields are always the same as before.
So you only need to monitor the `etat_actuelle` value.

![screen shot 2017-11-20 at 4 51 38 pm](https://user-images.githubusercontent.com/167831/33049049-1bec2012-ce13-11e7-85be-8b18c2a27dab.png)

---------

As I mentioned yesterday, this plugin can contains extra data, and if the value is changed, `(key)_changed` event is occurred (I believe you already understand this if you read the page).

So you can store all fields & values into makers.

```js
var mvcArray = new plugin.google.maps.BaseArrayClass(data);
//-------------------------------------
// Create markers for the first time
//-------------------------------------
mvcArray.map(function(markerOptions, cb) {
  map.addMarker(markerOptions, cb);
}, function(markers) {

  markers.forEach(function(marker) {
    var idparking = marker.get("idparking");
    parking_Markers[idparking] = marker;
    marker.on("etat_actuelle_changed", onEtatActuelle_change);
    marker.on(plugin.google.maps.event.MARKER_CLICK, onParkingMarker_click);
  });
  callback();
});
```

In the above code, key point is this line.
If the value of `etat_actuelle` field is changed, `etat_actuelle_changed` event is occurred.

```js
marker.on("etat_actuelle_changed", onEtatActuelle_change);
```
-----

After 15 sec, you get the updated data from server, then you just need to update the `etat_actuelle_changed` field.
(I think 60 sec is enough for parking. Save the battery usage)

```js
//-------------------------------------
// From second time, and after...
//-------------------------------------
mvcArray.map(function(markerOptions, cb) {
  var keys = Object.keys(markerOptions);
  var idparking = markerOptions.idparking;
  var marker = parking_Markers[idparking];
  marker.set("etat_actuelle", markerOptions.etat_actuelle);
  cb();
}, callback);
```

If the value is updated, you can get the notification.
Then you can set new icon for only updated parking spots.

```js
function onEtatActuelle_change(oldValue, newValue, marker) {
  console.log(marker.get("idparking", oldValue + " -> " + newValue));
  newValue = newValue || "0";
  marker.setIcon("www/icons/parking" + newValue + ".png");
}
```

**Comment by bigbossmaher** [comment] 2017-11-21 01:07
Really , i want to hug you. 
Just give me some time to check your answer completly
Thanks a lot man :)

**Comment by wf9a5m75** [comment] 2017-11-21 17:23
ping

**Comment by wf9a5m75** [comment] 2017-11-21 19:22
I committed the code to the `fixes` branch.

**Comment by bigbossmaher** [comment] 2017-11-21 19:27
hello , thank  you ,
1 - you are now a collabrator
after deleting the data variable in the ferst line and callback() function the code is not showing markers , do you think those propositions can cause the issue 
A - maybe the https://parking.tn/app/parking.php is not in a good format , i suggest replacing 
"lat":xx.xx,"long":xx.xx
with
"position": {
    {"lat": xx.xx, "lng": xx.xx}
  }
B - we haven't used the varible ParkingData that contains the json format of https://parking.tn/app/parking.php

**Comment by wf9a5m75** [comment] 2017-11-21 19:30
>after deleting the data variable in the ferst line and callback() function the code is not showing markers 

Where are you taking about?

**Comment by bigbossmaher** [comment] 2017-11-21 19:51
the code in the brach is working
AWESOME
for(i=0;i<5000;i++){
alert("thanks a lot");
}
give some time to try it

**Comment by wf9a5m75** [comment] 2017-11-21 19:53
Sounds good. Is that all you need to help?

**Comment by wf9a5m75** [comment] 2017-11-21 20:00
If you have further problems, please make another issue thread. I will help you.

By the way, I appreciate if you support for this project. 
This is not mandatory asking, but I appreciate if you donate some amount to keep this plugin as free.

[This is $5 donation link at paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=SQPLZJ672HJ9N&lc=US&item_name=Cordova%2dGoogleMaps%2dPlugin&amount=5%2e00&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)

**Closed by wf9a5m75** 2017-11-21 20:00 UTC
Labels: question

**Comment by bigbossmaher** [comment] 2017-11-21 20:10
donation sent :)

**Comment by wf9a5m75** [comment] 2017-11-21 20:12
Thank you for your kindness!

**Comment by bigbossmaher** [comment] 2017-11-21 20:59
in your function 
function onEtatActuelle_change(oldValue, newValue, marker) {
    //console.log(marker.get("idparking", oldValue + " -> " + newValue));
    newValue = newValue || "0";
    marker.setIcon("www/icons/parking" + newValue + ".png");
}
i get this in the console 
Uncaught TypeError: marker.setIcon is not a function", source: file:///android_asset/www/js/my-app.js (895)

**Comment by wf9a5m75** [comment] 2017-11-21 21:22
How about this?

```
function onEtatActuelle_change(oldValue, newValue) {
  var marker = this;
  //console.log(marker.get("idparking", oldValue + " -> " + newValue));
  newValue = newValue || "0";
  marker.setIcon("www/icons/parking" + newValue + ".png");
}
```
