### ISSUE TITLE
[iOS] local custom marker icons not working

### ISSUE THREAD

**Issue by MichaelMassalas** [mapsplugin/cordova-plugin-googlemaps#1601] opened 2017-07-31 15:40 UTC
**I'm submitting a ...**  (check one with "x")
[ ] question
[ X ] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[ X ] **2.0.0-beta2** 

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-name 1.0.0 "App Namer"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-googlemaps 2.0.0-beta2-20170729-1650 "cordova-plugin-googlemaps"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
es6-promise-plugin 4.1.0 "Promise"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"
{}
```

**Current behavior:**
Custom Marker Icons located in projects directory (not from the web) do not work on iOS only. They work on Android.

**Expected behavior:**
They should show fine

**Steps to reproduce:**
The issue is caused because I have a space in my app name. If I remove it, the images show fine. I would really prefer it to avoid using another plugin in order to *fake* my app name without spaces and then change it. Is there a way for this to be fixed otherwise?

**Related code, data or error log (please format your code or data):**

```
insert any relevant code, data, or error log here
```

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment] 2017-07-31 16:05
Please share your project files on github or bitbucket.

How and why?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/articles/before_post_your_issue#6-provide-your-code

**Comment by MichaelMassalas** [comment] 2017-07-31 16:33
Thank you for your reply.
It will take ages to get the agreement from the director for NDA.
Since we know the problem, I guess the code does not make any difference. You can use the demo app you have created (specifically the setIcon() function part) and if your app contains spaces in the app name, the issue will appear for you too. This is probably happening because xCode tries to use %20 instead of space, and cannot find the images

**Comment by wf9a5m75** [comment] 2017-07-31 16:50
I see. I haven't considered the space character. So I haven't checked it.
I will check this later.

> It will take ages to get the agreement from the director for NDA.

Since this plugin version is still in beta (becoming stable though), you may face issues.
So I recommend you send me the NDA, or create an empty project that is for reproducing your issue (most people who don't want to share the real code love this way).
Thank you for considering.

Basically, I'm not interested in other people code.
So I don't leak your code.
But important thing is that reproduce the issues and fix them.
(Or giving enough information such as crash log, debug code)

**Comment by wf9a5m75** [comment] 2017-08-03 16:31
Sorry, I haven't reached this issue yet. Terribly busy...

**Comment by MichaelMassalas** [comment] 2017-08-07 12:24
No problem. I totally understand.

If you have some time to go over it, please, let me know how it goes.

Thanks

**Comment by wf9a5m75** [comment] 2017-08-09 19:14
You use `cordova-plugin-googlemaps 2.0.0-beta2-20170729-1650`, but I updated a lot after that version.
(Actually almost everyday...)

These are small fixes or small improvements. Not critical issues, but I recommend reinstall the latest version.
Probably performance is better.

---

If you still face the same issue, please create an empty project that reproduce your issue, then share it on github or bitbucket.

I'm not interested in your product code at all. Please don't include it.
Only the map page please.

If you help me, I will help you. If you don't help me, I can't help you.

**Comment by wf9a5m75** [comment] 2017-08-09 20:26
I found I posted different issue thread.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1614#issuecomment-320868931

**Comment by wf9a5m75** [comment] 2017-08-10 14:05
ping

**Comment by wf9a5m75** [comment] 2017-08-13 17:05
Since there is no update, I close this issue thread.

But I updated the code around the marker, please try the latest version. It may fix your issue.

**Closed by wf9a5m75** 2017-08-13 17:05 UTC
Labels: need more information, pending / waiting
