### ISSUE TITLE
Error with PluginLocationService when building on iOS

### ISSUE THREAD

**Issue by mhilland** [mapsplugin/cordova-plugin-googlemaps#2061] opened 2018-02-08 04:32 UTC
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.2.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic 3.1.1 "IonicCordova"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.2.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

cli packages: (/Users/maxhilland/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1
    ios-sim           : 5.0.13
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : OS X El Capitan
    Xcode             : Xcode 7.3.1 Build version 7D1014
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

ionic-native/core ^4.3.2
ionic-native/google-maps ^4.5.2

**Current behavior:**

When building for iOS, I get the following build error. On the other hand, Android builds just fine.

**Expected behavior:**

I expect the build to succeed.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
/var/www/passport-ionic/platforms/ios/Passeport en fut/Plugins/cordova-plugin-googlemaps/PluginLocationService.m:109:20: No known class method for selector 'scheduledTimerWithTimeInterval:repeats:block:'
```

**Comment by wf9a5m75** [comment] 2018-02-08 04:35
In order to reproduce your issue, please share your project files(everything) on github.

**Comment by mhilland** [comment] 2018-02-08 04:38
I'm sorry but I'm unable to share the project via git as its a private repository.

**Comment by wf9a5m75** [comment] 2018-02-08 04:41
In that case, please create an example app that reproduce your issue, then share it.

**Comment by wf9a5m75** [comment] 2018-02-08 05:31
Tentatively, please try to reinstall the plugin. Without sharing the code, this is the suggestion that I can give you.

**Comment by wf9a5m75** [comment] 2018-02-08 15:50
ping

**Comment by wf9a5m75** [comment] 2018-02-09 03:18
@mhilland Did you solve your problem?

**Comment by wf9a5m75** [comment] 2018-02-09 04:44
@pratikTH Please share your project files on github. Nobody contribute me, no help.

**Comment by pratikTH** [comment] 2018-02-09 05:32
Thank you for reply sorry but i can't share all files but can share some specific file which would help.

**Comment by wf9a5m75** [comment] 2018-02-09 07:02
warn : if no body provides example project, I will close this thread.

**Comment by pratikTH** [comment] 2018-02-09 09:06
wf9a5m75 can you try this --->>https://www.joshmorony.com/integrating-native-google-maps-into-an-ionic-2-application/

use this ionic platform add ios instead of ionic platform add ios@3.9.0

**Comment by wf9a5m75** [comment] 2018-02-09 16:08
ios@3 is not supported.

```

    <engines>
      <engine name="cordova-android" version=">=5.1.0" />
      <engine name="cordova-ios" version=">=4.0.0" />
    </engines>

```

**Comment by wf9a5m75** [comment] 2018-02-09 20:06
`cordova-ios@4.0.0` is released in 2015, that is enough old.

`cordova-ios@3.x` is too old.

**Comment by wf9a5m75** [comment] 2018-02-09 22:53
**scheduledTimerWithTimeInterval:repeats:block:**
https://developer.apple.com/documentation/foundation/nstimer/2091889-scheduledtimerwithtimeinterval

I guess @mhilland and @pratikTH you are trying to build for iOS9, because the method was added at iOS10.
No longer supported for iOS9.

**Comment by pratikTH** [comment] 2018-02-10 07:34
@wf9a5m75 i am using macOS Sierra (version 10.12)

**Comment by wf9a5m75** [comment] 2018-02-10 08:30
I didn't talk about mac os version

**Comment by pratikTH** [comment] 2018-02-10 09:44
@wf9a5m75 sorry:) need to check with it i'll get back to you

**Comment by pratikTH** [comment] 2018-02-12 08:59
@wf9a5m75 Thank you i updated my xcode to 9.2 its working for me.

**Comment by wf9a5m75** [comment] 2018-02-12 17:01
Congratus!

**Closed by wf9a5m75** 2018-02-12 17:01 UTC
Labels: need more information
