### ISSUE TITLE
GoogleMapsEvent.MAP_READY Unresolved variable MAP_READY

### ISSUE THREAD

**Issue by ThalesMatoso** [mapsplugin/cordova-plugin-googlemaps#1746] opened 2017-09-17 22:43 UTC
**I'm submitting a ...**  (check one with "x")
[ X] question
[ ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **2.0-beta3 (github)** 
[ X] **2.0 (npm)** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ X] **Android**
[ ] **iOS**

The variable within GoogleMapsEvent is not recognized, returning error in the code how to proceed?

**Comment by wf9a5m75** [comment] 2017-09-17 23:10
Sorry, after the discussion with Mike, ionic team, I don't support the `@ionic-native/google-maps` anymore. Please ask to the ionic-native repository.

**Comment by wf9a5m75** [comment] 2017-09-19 00:33
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1749

**Comment by wf9a5m75** [comment] 2017-09-21 16:18
Since the fundraising is reached to the end, I reply your answer.

The MAP_READY event is defined at here.
I guess you have mistake in your code.
(such as you don't import the GoogleMapsEvent class)

Please double check your code.

https://github.com/ionic-team/ionic-native/blob/ef898efcc6c71093902c40bbe71dcd8e1044a005/src/%40ionic-native/plugins/google-maps/index.ts#L447

I think this is not a bug, so I close this issue at once.
But if you have further problems, please reply to this thread.

**Closed by wf9a5m75** 2017-09-21 16:18 UTC
Labels: @ionic-native/googlemaps
